/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface Cfo {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type string
    */
    code: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type boolean
    */
    isActive: boolean;
}