/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CfoStatusValue2 } from "./CfoStatusValue2";
import type { Correction } from "./Correction";
import type { CorrectionType } from "./CorrectionType";
import type { Filial } from "./Filial";
import type { UserSummary } from "./UserSummary";

export type CorrectionListItem = (Correction & {
    /**
     * @type object
    */
    filial: Filial;
    /**
     * @type object
    */
    correctionType: CorrectionType;
    /**
     * @type object
    */
    author: UserSummary;
    /**
     * @description Заполняется только для роли CFO
    */
    myCfoStatus?: (CfoStatusValue2 | null);
});