/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserSummary } from "./UserSummary";

export interface CorrectionHistoryEntry2 {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type integer
    */
    correctionId: number;
    /**
     * @type string, date-time
    */
    timestamp: string;
    /**
     * @type integer,null
    */
    userId?: number | null;
    user?: (UserSummary | null);
    /**
     * @type string
    */
    text: string;
}