/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CfoStatusValue2 } from "./CfoStatusValue2";

export interface CorrectionCfoStatus {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type integer
    */
    correctionId: number;
    /**
     * @type integer
    */
    cfoId: number;
    /**
     * @type string
    */
    status: CfoStatusValue2;
    /**
     * @type boolean
    */
    isRequired: boolean;
    /**
     * @type integer,null
    */
    decidedById?: number | null;
    /**
     * @type string,null, date-time
    */
    decidedAt?: string | null;
}