/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileVersion2 } from "./FileVersion2";

export interface DocumentSlot2 {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type integer
    */
    correctionId: number;
    /**
     * @description null — основной Excel-файл корректировки
     * @type integer,null
    */
    requirementId: number | null;
    /**
     * @type string
    */
    label: string;
    /**
     * @type boolean
    */
    isFilled: boolean;
    currentVersion?: (FileVersion2 | null);
}