/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface ErrorResponse {
    /**
     * @type integer
    */
    statusCode: number;
    message: (string | string[]);
    /**
     * @type string | undefined
    */
    error?: string;
}