/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Для пакета, созданного Филиалом, cfoIds обязателен (кому направить на проверку). Для пакета, созданного ЦФО, cfoIds не нужен — пакет уходит сразу в ДТОиР.\n
*/
export interface FactPackageSubmitInput {
    /**
     * @type array | undefined
    */
    cfoIds?: number[];
}