/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactCfoStatusValue2 } from "./FactCfoStatusValue2";
import type { FactPackage } from "./FactPackage";
import type { Filial } from "./Filial";
import type { UserSummary } from "./UserSummary";

export type FactPackageListItem = (FactPackage & {
    /**
     * @type object
    */
    filial: Filial;
    /**
     * @type object
    */
    author: UserSummary;
    /**
     * @description Заполняется только для роли CFO
    */
    myCfoStatus?: (FactCfoStatusValue2 | null);
});