/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface FileVersion2 {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type integer
    */
    slotId: number;
    /**
     * @type integer
    */
    versionNumber: number;
    /**
     * @type string
    */
    fileName: string;
    /**
     * @type integer
    */
    fileSize: number;
    /**
     * @type string | undefined
    */
    mimeType?: string;
    /**
     * @type integer
    */
    uploadedById: number;
    /**
     * @type string, date-time
    */
    uploadedAt: string;
    /**
     * @type integer,null
    */
    remarkId?: number | null;
    /**
     * @type string | undefined
    */
    note?: string;
}