/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface FilialInput {
    /**
     * @type string
    */
    code: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
}