/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface FilialCfoLinkInput {
    /**
     * @type integer
    */
    filialId: number;
    /**
     * @type integer
    */
    cfoId: number;
    /**
     * @default true
     * @type boolean | undefined
    */
    isActive?: boolean;
}