/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface LoginRequest {
    /**
     * @type string, email
    */
    email: string;
    /**
     * @type string, password
    */
    password: string;
}