/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface LoginRequest {
    /**
     * @type string
    */
    username: string;
    /**
     * @type string, password
    */
    password: string;
}