/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface Notification {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type integer
    */
    userId: number;
    /**
     * @type integer
    */
    correctionId: number;
    /**
     * @type string | undefined
    */
    correctionHumanId?: string;
    /**
     * @type string
    */
    text: string;
    /**
     * @type boolean
    */
    isRead: boolean;
    /**
     * @type string, date-time
    */
    createdAt: string;
}