/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Уведомление относится ровно к одной сущности — либо к корректировке\n(correctionId), либо к факт-пакету (factPackageId); в паре полей заполнено\nровно одно, второе — null (openspec/changes/fact-package-review).\n
*/
export interface Notification2 {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type integer
    */
    userId: number;
    /**
     * @type integer,null
    */
    correctionId: number | null;
    /**
     * @type string | undefined
    */
    correctionHumanId?: string;
    /**
     * @type integer,null
    */
    factPackageId: number | null;
    /**
     * @type string | undefined
    */
    factPackageHumanId?: string;
    /**
     * @type string
    */
    text: string;
    /**
     * @type boolean
    */
    isRead: boolean;
    /**
     * @type string, date-time
    */
    createdAt: string;
}