/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PackageRequirementKind2 } from "./PackageRequirementKind2";

export interface PackageRequirement {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type integer
    */
    correctionTypeId: number;
    /**
     * @type string
    */
    kind: PackageRequirementKind2;
    /**
     * @type string
    */
    name: string;
    /**
     * @type boolean
    */
    isRequired: boolean;
    /**
     * @type integer,null
    */
    responsibleCfoId?: number | null;
    /**
     * @type string | undefined
    */
    namePattern?: string;
    /**
     * @type string | undefined
    */
    fileFormat?: string;
    /**
     * @type integer
    */
    order: number;
}