/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanListItem } from "./PlanListItem";

export interface PaginatedPlans {
    /**
     * @type array
    */
    items: PlanListItem[];
    /**
     * @type integer
    */
    total: number;
    /**
     * @type integer
    */
    page: number;
    /**
     * @type integer
    */
    pageSize: number;
}