/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactPackageListItem } from "./FactPackageListItem";

export interface PaginatedFactPackages {
    /**
     * @type array
    */
    items: FactPackageListItem[];
    /**
     * @type integer
    */
    total: number;
    /**
     * @type integer
    */
    page: number;
    /**
     * @type integer
    */
    pageSize: number;
}