/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionListItem } from "./CorrectionListItem";

export interface PaginatedCorrections {
    /**
     * @type array
    */
    items: CorrectionListItem[];
    /**
     * @type integer
    */
    total: number;
    /**
     * @type integer
    */
    page: number;
    /**
     * @type integer
    */
    pageSize: number;
}