/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanPackageRequirementKind2 } from "./PlanPackageRequirementKind2";

export interface PlanPackageRequirementInput {
    /**
     * @type string
    */
    kind: PlanPackageRequirementKind2;
    /**
     * @type string
    */
    name: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    isRequired?: boolean;
    /**
     * @type integer,null
    */
    responsibleCfoId?: number | null;
    /**
     * @type string | undefined
    */
    namePattern?: string;
    /**
     * @type string | undefined
    */
    fileFormat?: string;
    /**
     * @default 0
     * @type integer | undefined
    */
    order?: number;
    /**
     * @type string,null
    */
    choiceGroupKey?: string | null;
    /**
     * @type string,null
    */
    groupLabel?: string | null;
}