/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Cfo } from "./Cfo";
import type { PlanFileVersion2 } from "./PlanFileVersion2";

export interface PlanDocumentSlot2 {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type integer
    */
    planId: number;
    /**
     * @description null — основной Excel-файл плана
     * @type integer,null
    */
    requirementId: number | null;
    /**
     * @type string
    */
    label: string;
    /**
     * @type boolean
    */
    isFilled: boolean;
    /**
     * @description Пока не заполнены все обязательные слоты, направить план нельзя
     * @type boolean
    */
    isRequired: boolean;
    /**
     * @description null — элемент проверяют все ЦФО маршрута, а не конкретное подразделение
    */
    responsibleCfo: (Cfo | null);
    currentVersion?: (PlanFileVersion2 | null);
    /**
     * @description Общий ключ для слотов-альтернатив («выбери один из группы»); null — слот не входит в группу
     * @type string,null
    */
    choiceGroupKey?: string | null;
    /**
     * @description Заголовок группы для UI; null — слот не входит в группу
     * @type string,null
    */
    groupLabel?: string | null;
}