/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface PlanRemarkReopenInput {
    /**
     * @type string
    */
    description: string;
    /**
     * @type string
    */
    requiredAction: string;
}