/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description FILIAL/CFO/DTOE — роли из старого Django-проекта (accounts.Role). ADMIN — эквивалент is_staff/is_superuser (управление справочниками и пользователями).\n
*/
export type Role = ("FILIAL" | "CFO" | "DTOE" | "ADMIN");