/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface UserSummary {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type string
    */
    username: string;
    /**
     * @type string
    */
    fullName: string;
}