/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Role2 } from "./Role2";

export interface UserCreateInput {
    /**
     * @type string
    */
    username: string;
    /**
     * @minLength 9
     * @type string, password
    */
    password: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    firstName?: string;
    /**
     * @type string | undefined
    */
    lastName?: string;
    /**
     * @description FILIAL/CFO/DTOE — роли из старого Django-проекта (accounts.Role). ADMIN — эквивалент is_staff/is_superuser (управление справочниками и пользователями).\n
     * @type string
    */
    role: Role2;
    /**
     * @type integer,null
    */
    filialId?: number | null;
    /**
     * @type integer,null
    */
    cfoId?: number | null;
    /**
     * @type string | undefined
    */
    position?: string;
    /**
     * @type string | undefined
    */
    phone?: string;
}