/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";
import type { FactPackageDetail } from "../FactPackageDetail";

export interface ApproveFactPackageByCfoPathParams {
    /**
     * @type string
    */
    humanId: string;
    /**
     * @type integer
    */
    cfoId: number;
}

/**
 * @description Согласовано
*/
export type ApproveFactPackageByCfo200 = FactPackageDetail;

/**
 * @description Решение по этому факт-пакету уже принято этим ЦФО
*/
export type ApproveFactPackageByCfo400 = ErrorResponse2;

/**
 * @description Нет доступа
*/
export type ApproveFactPackageByCfo403 = ErrorResponse2;

export type ApproveFactPackageByCfoMutationResponse = ApproveFactPackageByCfo200;

export type ApproveFactPackageByCfoMutation = {
    Response: ApproveFactPackageByCfo200;
    PathParams: ApproveFactPackageByCfoPathParams;
    Errors: ApproveFactPackageByCfo400 | ApproveFactPackageByCfo403;
};