/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";
import type { FactFinalDecision } from "../FactFinalDecision";
import type { FactPackageDetail } from "../FactPackageDetail";

export interface DecideFactPackageByDtoePathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Решение принято
*/
export type DecideFactPackageByDtoe200 = FactPackageDetail;

/**
 * @description Факт-пакет не на проверке ДТОиР, либо RETURN без открытого замечания
*/
export type DecideFactPackageByDtoe400 = ErrorResponse2;

/**
 * @description Нет доступа
*/
export type DecideFactPackageByDtoe403 = ErrorResponse2;

export type DecideFactPackageByDtoeMutationRequest = FactFinalDecision;

export type DecideFactPackageByDtoeMutationResponse = DecideFactPackageByDtoe200;

export type DecideFactPackageByDtoeMutation = {
    Response: DecideFactPackageByDtoe200;
    Request: DecideFactPackageByDtoeMutationRequest;
    PathParams: DecideFactPackageByDtoePathParams;
    Errors: DecideFactPackageByDtoe400 | DecideFactPackageByDtoe403;
};