/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";

export interface DeleteFactPackageRemarkPathParams {
    /**
     * @type string
    */
    humanId: string;
    /**
     * @type integer
    */
    remarkId: number;
}

/**
 * @description Замечание удалено
*/
export type DeleteFactPackageRemark204 = unknown;

/**
 * @description Замечание не в статусе OPEN
*/
export type DeleteFactPackageRemark400 = ErrorResponse2;

/**
 * @description Не автор замечания
*/
export type DeleteFactPackageRemark403 = ErrorResponse2;

export type DeleteFactPackageRemarkMutationResponse = DeleteFactPackageRemark204;

export type DeleteFactPackageRemarkMutation = {
    Response: DeleteFactPackageRemark204;
    PathParams: DeleteFactPackageRemarkPathParams;
    Errors: DeleteFactPackageRemark400 | DeleteFactPackageRemark403;
};