/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";

export interface DownloadFactFormVersionPathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Бинарное содержимое файла
*/
export type DownloadFactFormVersion200 = Blob;

/**
 * @description Нет доступа
*/
export type DownloadFactFormVersion403 = ErrorResponse2;

export type DownloadFactFormVersionQueryResponse = DownloadFactFormVersion200;

export type DownloadFactFormVersionQuery = {
    Response: DownloadFactFormVersion200;
    PathParams: DownloadFactFormVersionPathParams;
    Errors: DownloadFactFormVersion403;
};