/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Direction2 } from "../Direction2";
import type { ErrorResponse2 } from "../ErrorResponse2";
import type { FactPackageDetail } from "../FactPackageDetail";

export interface GetOrCreateFactPackageByDirectionPathParams {
    /**
     * @type string
    */
    direction: Direction2;
}

/**
 * @description Факт-пакет получен либо создан
*/
export type GetOrCreateFactPackageByDirection200 = FactPackageDetail;

/**
 * @description Доступно только роли FILIAL
*/
export type GetOrCreateFactPackageByDirection403 = ErrorResponse2;

export type GetOrCreateFactPackageByDirectionQueryResponse = GetOrCreateFactPackageByDirection200;

export type GetOrCreateFactPackageByDirectionQuery = {
    Response: GetOrCreateFactPackageByDirection200;
    PathParams: GetOrCreateFactPackageByDirectionPathParams;
    Errors: GetOrCreateFactPackageByDirection403;
};