/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CfoSelectionInput } from "../CfoSelectionInput";
import type { ErrorResponse2 } from "../ErrorResponse2";
import type { FactPackageDetail } from "../FactPackageDetail";

export interface SubmitFactPackagePathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Направлено
*/
export type SubmitFactPackage200 = FactPackageDetail;

/**
 * @description Пакет не укомплектован, ЦФО не выбраны/не привязаны, либо есть неисправленные замечания
*/
export type SubmitFactPackage400 = ErrorResponse2;

export type SubmitFactPackageMutationRequest = CfoSelectionInput;

export type SubmitFactPackageMutationResponse = SubmitFactPackage200;

export type SubmitFactPackageMutation = {
    Response: SubmitFactPackage200;
    Request: SubmitFactPackageMutationRequest;
    PathParams: SubmitFactPackagePathParams;
    Errors: SubmitFactPackage400;
};