/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";
import type { FactFormCode2 } from "../FactFormCode2";
import type { FactFormVersion2 } from "../FactFormVersion2";

export interface UploadFactFormVersionPathParams {
    /**
     * @type string
    */
    humanId: string;
    /**
     * @type string
    */
    formCode: FactFormCode2;
}

/**
 * @description Новая версия формы добавлена
*/
export type UploadFactFormVersion201 = FactFormVersion2;

/**
 * @description Факт-пакет в финальном статусе либо formCode не входит в каталог направления
*/
export type UploadFactFormVersion400 = ErrorResponse2;

/**
 * @description Нет доступа (не автор/не владелец филиала)
*/
export type UploadFactFormVersion403 = ErrorResponse2;

export interface UploadFactFormVersionMutationRequest {
    /**
     * @type string, binary
    */
    file: Blob;
    /**
     * @type string | undefined
    */
    note?: string;
    /**
     * @description Если файл загружен в ответ на замечание
     * @type integer | undefined
    */
    remarkId?: number;
}

export type UploadFactFormVersionMutationResponse = UploadFactFormVersion201;

export type UploadFactFormVersionMutation = {
    Response: UploadFactFormVersion201;
    Request: UploadFactFormVersionMutationRequest;
    PathParams: UploadFactFormVersionPathParams;
    Errors: UploadFactFormVersion400 | UploadFactFormVersion403;
};