/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreatePackageRequirementMutationRequest, CreatePackageRequirementMutationResponse, CreatePackageRequirementPathParams } from "../../types/orgController/CreatePackageRequirement";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { createPackageRequirement } from "../../clients/orgController/createPackageRequirement";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createPackageRequirementMutationKey = () => [{ url: '/org/correction-types/:id/requirements' }] as const

export type CreatePackageRequirementMutationKey = ReturnType<typeof createPackageRequirementMutationKey>

export function createPackageRequirementMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreatePackageRequirementMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = createPackageRequirementMutationKey()
        return mutationOptions<CreatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePackageRequirementPathParams["id"], data: CreatePackageRequirementMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return createPackageRequirement({ id, data }, config)
          },
        })

}

/**
 * @summary Добавить требование в пакет типа корректировки
 * {@link /org/correction-types/:id/requirements}
 */
export function useCreatePackageRequirement<TContext>(options: 
{
  mutation?: UseMutationOptions<CreatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePackageRequirementPathParams["id"], data: CreatePackageRequirementMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreatePackageRequirementMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? createPackageRequirementMutationKey()

          const baseOptions = createPackageRequirementMutationOptions(config) as UseMutationOptions<CreatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePackageRequirementPathParams["id"], data: CreatePackageRequirementMutationRequest}, TContext>
          

          return useMutation<CreatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePackageRequirementPathParams["id"], data: CreatePackageRequirementMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CreatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePackageRequirementPathParams["id"], data: CreatePackageRequirementMutationRequest}, TContext>
      
}