/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreatePlanPackageRequirementMutationRequest, CreatePlanPackageRequirementMutationResponse, CreatePlanPackageRequirementPathParams } from "../../types/orgController/CreatePlanPackageRequirement";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { createPlanPackageRequirement } from "../../clients/orgController/createPlanPackageRequirement";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createPlanPackageRequirementMutationKey = () => [{ url: '/org/plan-types/:id/requirements' }] as const

export type CreatePlanPackageRequirementMutationKey = ReturnType<typeof createPlanPackageRequirementMutationKey>

export function createPlanPackageRequirementMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreatePlanPackageRequirementMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = createPlanPackageRequirementMutationKey()
        return mutationOptions<CreatePlanPackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePlanPackageRequirementPathParams["id"], data: CreatePlanPackageRequirementMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return createPlanPackageRequirement({ id, data }, config)
          },
        })

}

/**
 * @summary Добавить требование в пакет типа плана
 * {@link /org/plan-types/:id/requirements}
 */
export function useCreatePlanPackageRequirement<TContext>(options: 
{
  mutation?: UseMutationOptions<CreatePlanPackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePlanPackageRequirementPathParams["id"], data: CreatePlanPackageRequirementMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreatePlanPackageRequirementMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? createPlanPackageRequirementMutationKey()

          const baseOptions = createPlanPackageRequirementMutationOptions(config) as UseMutationOptions<CreatePlanPackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePlanPackageRequirementPathParams["id"], data: CreatePlanPackageRequirementMutationRequest}, TContext>
          

          return useMutation<CreatePlanPackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePlanPackageRequirementPathParams["id"], data: CreatePlanPackageRequirementMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CreatePlanPackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: CreatePlanPackageRequirementPathParams["id"], data: CreatePlanPackageRequirementMutationRequest}, TContext>
      
}