/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreatePlanTypeMutationRequest, CreatePlanTypeMutationResponse } from "../../types/orgController/CreatePlanType";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { createPlanType } from "../../clients/orgController/createPlanType";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createPlanTypeMutationKey = () => [{ url: '/org/plan-types' }] as const

export type CreatePlanTypeMutationKey = ReturnType<typeof createPlanTypeMutationKey>

export function createPlanTypeMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreatePlanTypeMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = createPlanTypeMutationKey()
        return mutationOptions<CreatePlanTypeMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanTypeMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return createPlanType({ data }, config)
          },
        })

}

/**
 * @summary Создать тип плана
 * {@link /org/plan-types}
 */
export function useCreatePlanType<TContext>(options: 
{
  mutation?: UseMutationOptions<CreatePlanTypeMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanTypeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreatePlanTypeMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? createPlanTypeMutationKey()

          const baseOptions = createPlanTypeMutationOptions(config) as UseMutationOptions<CreatePlanTypeMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanTypeMutationRequest}, TContext>
          

          return useMutation<CreatePlanTypeMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanTypeMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CreatePlanTypeMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanTypeMutationRequest}, TContext>
      
}