/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreateFilialMutationRequest, CreateFilialMutationResponse } from "../../types/orgController/CreateFilial";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { createFilial } from "../../clients/orgController/createFilial";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createFilialMutationKey = () => [{ url: '/org/filials' }] as const

export type CreateFilialMutationKey = ReturnType<typeof createFilialMutationKey>

export function createFilialMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreateFilialMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = createFilialMutationKey()
        return mutationOptions<CreateFilialMutationResponse, ResponseErrorConfig<Error>, {data: CreateFilialMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return createFilial({ data }, config)
          },
        })

}

/**
 * @summary Создать филиал
 * {@link /org/filials}
 */
export function useCreateFilial<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateFilialMutationResponse, ResponseErrorConfig<Error>, {data: CreateFilialMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateFilialMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? createFilialMutationKey()

          const baseOptions = createFilialMutationOptions(config) as UseMutationOptions<CreateFilialMutationResponse, ResponseErrorConfig<Error>, {data: CreateFilialMutationRequest}, TContext>
          

          return useMutation<CreateFilialMutationResponse, ResponseErrorConfig<Error>, {data: CreateFilialMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CreateFilialMutationResponse, ResponseErrorConfig<Error>, {data: CreateFilialMutationRequest}, TContext>
      
}