/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeleteCorrectionTypeMutationResponse, DeleteCorrectionTypePathParams } from "../../types/orgController/DeleteCorrectionType";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteCorrectionType } from "../../clients/orgController/deleteCorrectionType";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteCorrectionTypeMutationKey = () => [{ url: '/org/correction-types/:id' }] as const

export type DeleteCorrectionTypeMutationKey = ReturnType<typeof deleteCorrectionTypeMutationKey>

export function deleteCorrectionTypeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteCorrectionTypeMutationKey()
        return mutationOptions<DeleteCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCorrectionTypePathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteCorrectionType({ id }, config)
          },
        })

}

/**
 * @summary Удалить тип корректировки
 * {@link /org/correction-types/:id}
 */
export function useDeleteCorrectionType<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCorrectionTypePathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteCorrectionTypeMutationKey()

          const baseOptions = deleteCorrectionTypeMutationOptions(config) as UseMutationOptions<DeleteCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCorrectionTypePathParams["id"]}, TContext>
          

          return useMutation<DeleteCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCorrectionTypePathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCorrectionTypePathParams["id"]}, TContext>
      
}