/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeleteFilialCfoLinkMutationResponse, DeleteFilialCfoLinkPathParams } from "../../types/orgController/DeleteFilialCfoLink";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteFilialCfoLink } from "../../clients/orgController/deleteFilialCfoLink";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteFilialCfoLinkMutationKey = () => [{ url: '/org/filial-cfo-links/:id' }] as const

export type DeleteFilialCfoLinkMutationKey = ReturnType<typeof deleteFilialCfoLinkMutationKey>

export function deleteFilialCfoLinkMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteFilialCfoLinkMutationKey()
        return mutationOptions<DeleteFilialCfoLinkMutationResponse, ResponseErrorConfig<Error>, {id: DeleteFilialCfoLinkPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteFilialCfoLink({ id }, config)
          },
        })

}

/**
 * @summary Удалить связь филиал-ЦФО
 * {@link /org/filial-cfo-links/:id}
 */
export function useDeleteFilialCfoLink<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteFilialCfoLinkMutationResponse, ResponseErrorConfig<Error>, {id: DeleteFilialCfoLinkPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteFilialCfoLinkMutationKey()

          const baseOptions = deleteFilialCfoLinkMutationOptions(config) as UseMutationOptions<DeleteFilialCfoLinkMutationResponse, ResponseErrorConfig<Error>, {id: DeleteFilialCfoLinkPathParams["id"]}, TContext>
          

          return useMutation<DeleteFilialCfoLinkMutationResponse, ResponseErrorConfig<Error>, {id: DeleteFilialCfoLinkPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteFilialCfoLinkMutationResponse, ResponseErrorConfig<Error>, {id: DeleteFilialCfoLinkPathParams["id"]}, TContext>
      
}