/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeleteCfoMutationResponse, DeleteCfoPathParams } from "../../types/orgController/DeleteCfo";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteCfo } from "../../clients/orgController/deleteCfo";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteCfoMutationKey = () => [{ url: '/org/cfos/:id' }] as const

export type DeleteCfoMutationKey = ReturnType<typeof deleteCfoMutationKey>

export function deleteCfoMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteCfoMutationKey()
        return mutationOptions<DeleteCfoMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCfoPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteCfo({ id }, config)
          },
        })

}

/**
 * @summary Удалить ЦФО
 * {@link /org/cfos/:id}
 */
export function useDeleteCfo<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteCfoMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCfoPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteCfoMutationKey()

          const baseOptions = deleteCfoMutationOptions(config) as UseMutationOptions<DeleteCfoMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCfoPathParams["id"]}, TContext>
          

          return useMutation<DeleteCfoMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCfoPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteCfoMutationResponse, ResponseErrorConfig<Error>, {id: DeleteCfoPathParams["id"]}, TContext>
      
}