/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCfosQueryResponse, GetCfosQueryParams } from "../../types/orgController/GetCfos";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getCfos } from "../../clients/orgController/getCfos";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCfosSuspenseQueryKey = (params?: GetCfosQueryParams) => [{ url: '/org/cfos' }, ...(params ? [params] : [])] as const

export type GetCfosSuspenseQueryKey = ReturnType<typeof getCfosSuspenseQueryKey>

export function getCfosSuspenseQueryOptions({ params }: { params?: GetCfosQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCfosSuspenseQueryKey(params)
        return queryOptions<GetCfosQueryResponse, ResponseErrorConfig<Error>, GetCfosQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getCfos({ params: params }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Список ЦФО
 * {@link /org/cfos}
 */
export function useGetCfosSuspense<TData = GetCfosQueryResponse, TQueryKey extends QueryKey = GetCfosSuspenseQueryKey>({ params }: { params?: GetCfosQueryParams } = {}, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetCfosQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCfosSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getCfosSuspenseQueryOptions({ params }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}