/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCfosQueryResponse, GetCfosQueryParams } from "../../types/orgController/GetCfos";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getCfos } from "../../clients/orgController/getCfos";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCfosQueryKey = (params?: GetCfosQueryParams) => [{ url: '/org/cfos' }, ...(params ? [params] : [])] as const

export type GetCfosQueryKey = ReturnType<typeof getCfosQueryKey>

export function getCfosQueryOptions({ params }: { params?: GetCfosQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCfosQueryKey(params)
        return queryOptions<GetCfosQueryResponse, ResponseErrorConfig<Error>, GetCfosQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getCfos({ params: params }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Список ЦФО
 * {@link /org/cfos}
 */
export function useGetCfos<TData = GetCfosQueryResponse, TQueryData = GetCfosQueryResponse, TQueryKey extends QueryKey = GetCfosQueryKey>({ params }: { params?: GetCfosQueryParams } = {}, options: 
{
  query?: Partial<QueryObserverOptions<GetCfosQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCfosQueryKey(params)
         

         const query = useQuery({
          ...getCfosQueryOptions({ params }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}