/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFilialsQueryResponse, GetFilialsQueryParams } from "../../types/orgController/GetFilials";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getFilials } from "../../clients/orgController/getFilials";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getFilialsSuspenseQueryKey = (params?: GetFilialsQueryParams) => [{ url: '/org/filials' }, ...(params ? [params] : [])] as const

export type GetFilialsSuspenseQueryKey = ReturnType<typeof getFilialsSuspenseQueryKey>

export function getFilialsSuspenseQueryOptions({ params }: { params?: GetFilialsQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFilialsSuspenseQueryKey(params)
        return queryOptions<GetFilialsQueryResponse, ResponseErrorConfig<Error>, GetFilialsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getFilials({ params: params }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Список филиалов
 * {@link /org/filials}
 */
export function useGetFilialsSuspense<TData = GetFilialsQueryResponse, TQueryKey extends QueryKey = GetFilialsSuspenseQueryKey>({ params }: { params?: GetFilialsQueryParams } = {}, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetFilialsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFilialsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getFilialsSuspenseQueryOptions({ params }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}