/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFilialCfoLinksQueryResponse, GetFilialCfoLinksQueryParams } from "../../types/orgController/GetFilialCfoLinks";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getFilialCfoLinks } from "../../clients/orgController/getFilialCfoLinks";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getFilialCfoLinksSuspenseQueryKey = (params?: GetFilialCfoLinksQueryParams) => [{ url: '/org/filial-cfo-links' }, ...(params ? [params] : [])] as const

export type GetFilialCfoLinksSuspenseQueryKey = ReturnType<typeof getFilialCfoLinksSuspenseQueryKey>

export function getFilialCfoLinksSuspenseQueryOptions({ params }: { params?: GetFilialCfoLinksQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFilialCfoLinksSuspenseQueryKey(params)
        return queryOptions<GetFilialCfoLinksQueryResponse, ResponseErrorConfig<Error>, GetFilialCfoLinksQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getFilialCfoLinks({ params: params }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Список связей филиал-ЦФО
 * {@link /org/filial-cfo-links}
 */
export function useGetFilialCfoLinksSuspense<TData = GetFilialCfoLinksQueryResponse, TQueryKey extends QueryKey = GetFilialCfoLinksSuspenseQueryKey>({ params }: { params?: GetFilialCfoLinksQueryParams } = {}, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetFilialCfoLinksQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFilialCfoLinksSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getFilialCfoLinksSuspenseQueryOptions({ params }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}