/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionTypesQueryResponse, GetCorrectionTypesQueryParams } from "../../types/orgController/GetCorrectionTypes";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getCorrectionTypes } from "../../clients/orgController/getCorrectionTypes";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCorrectionTypesSuspenseQueryKey = (params?: GetCorrectionTypesQueryParams) => [{ url: '/org/correction-types' }, ...(params ? [params] : [])] as const

export type GetCorrectionTypesSuspenseQueryKey = ReturnType<typeof getCorrectionTypesSuspenseQueryKey>

export function getCorrectionTypesSuspenseQueryOptions({ params }: { params?: GetCorrectionTypesQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCorrectionTypesSuspenseQueryKey(params)
        return queryOptions<GetCorrectionTypesQueryResponse, ResponseErrorConfig<Error>, GetCorrectionTypesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getCorrectionTypes({ params: params }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Список типов корректировок
 * {@link /org/correction-types}
 */
export function useGetCorrectionTypesSuspense<TData = GetCorrectionTypesQueryResponse, TQueryKey extends QueryKey = GetCorrectionTypesSuspenseQueryKey>({ params }: { params?: GetCorrectionTypesQueryParams } = {}, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetCorrectionTypesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCorrectionTypesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getCorrectionTypesSuspenseQueryOptions({ params }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}