/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionTypeQueryResponse, GetCorrectionTypePathParams } from "../../types/orgController/GetCorrectionType";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getCorrectionType } from "../../clients/orgController/getCorrectionType";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCorrectionTypeQueryKey = ({ id }: { id: GetCorrectionTypePathParams["id"] | undefined }) => [{ url: '/org/correction-types/:id', params: {id:id} }] as const

export type GetCorrectionTypeQueryKey = ReturnType<typeof getCorrectionTypeQueryKey>

export function getCorrectionTypeQueryOptions({ id }: { id: GetCorrectionTypePathParams["id"] | undefined }, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCorrectionTypeQueryKey({ id })
        return queryOptions<GetCorrectionTypeQueryResponse, ResponseErrorConfig<Error>, GetCorrectionTypeQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return getCorrectionType({ id: id! }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Тип корректировки с требованиями пакета
 * {@link /org/correction-types/:id}
 */
export function useGetCorrectionType<TData = GetCorrectionTypeQueryResponse, TQueryData = GetCorrectionTypeQueryResponse, TQueryKey extends QueryKey = GetCorrectionTypeQueryKey>({ id }: { id: GetCorrectionTypePathParams["id"] | undefined }, options: 
{
  query?: Partial<QueryObserverOptions<GetCorrectionTypeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCorrectionTypeQueryKey({ id })
         

         const query = useQuery({
          ...getCorrectionTypeQueryOptions({ id }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}