/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlanTypesQueryResponse, GetPlanTypesQueryParams } from "../../types/orgController/GetPlanTypes";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getPlanTypes } from "../../clients/orgController/getPlanTypes";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPlanTypesQueryKey = (params?: GetPlanTypesQueryParams) => [{ url: '/org/plan-types' }, ...(params ? [params] : [])] as const

export type GetPlanTypesQueryKey = ReturnType<typeof getPlanTypesQueryKey>

export function getPlanTypesQueryOptions({ params }: { params?: GetPlanTypesQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPlanTypesQueryKey(params)
        return queryOptions<GetPlanTypesQueryResponse, ResponseErrorConfig<Error>, GetPlanTypesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getPlanTypes({ params: params }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Список типов планов
 * {@link /org/plan-types}
 */
export function useGetPlanTypes<TData = GetPlanTypesQueryResponse, TQueryData = GetPlanTypesQueryResponse, TQueryKey extends QueryKey = GetPlanTypesQueryKey>({ params }: { params?: GetPlanTypesQueryParams } = {}, options: 
{
  query?: Partial<QueryObserverOptions<GetPlanTypesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPlanTypesQueryKey(params)
         

         const query = useQuery({
          ...getPlanTypesQueryOptions({ params }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}