/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { UpdatePackageRequirementMutationRequest, UpdatePackageRequirementMutationResponse, UpdatePackageRequirementPathParams } from "../../types/orgController/UpdatePackageRequirement";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updatePackageRequirement } from "../../clients/orgController/updatePackageRequirement";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updatePackageRequirementMutationKey = () => [{ url: '/org/requirements/:id' }] as const

export type UpdatePackageRequirementMutationKey = ReturnType<typeof updatePackageRequirementMutationKey>

export function updatePackageRequirementMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdatePackageRequirementMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updatePackageRequirementMutationKey()
        return mutationOptions<UpdatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: UpdatePackageRequirementPathParams["id"], data: UpdatePackageRequirementMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return updatePackageRequirement({ id, data }, config)
          },
        })

}

/**
 * @summary Обновить требование пакета
 * {@link /org/requirements/:id}
 */
export function useUpdatePackageRequirement<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: UpdatePackageRequirementPathParams["id"], data: UpdatePackageRequirementMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdatePackageRequirementMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updatePackageRequirementMutationKey()

          const baseOptions = updatePackageRequirementMutationOptions(config) as UseMutationOptions<UpdatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: UpdatePackageRequirementPathParams["id"], data: UpdatePackageRequirementMutationRequest}, TContext>
          

          return useMutation<UpdatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: UpdatePackageRequirementPathParams["id"], data: UpdatePackageRequirementMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdatePackageRequirementMutationResponse, ResponseErrorConfig<Error>, {id: UpdatePackageRequirementPathParams["id"], data: UpdatePackageRequirementMutationRequest}, TContext>
      
}