/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { UpdateFilialMutationRequest, UpdateFilialMutationResponse, UpdateFilialPathParams } from "../../types/orgController/UpdateFilial";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateFilial } from "../../clients/orgController/updateFilial";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateFilialMutationKey = () => [{ url: '/org/filials/:id' }] as const

export type UpdateFilialMutationKey = ReturnType<typeof updateFilialMutationKey>

export function updateFilialMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateFilialMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateFilialMutationKey()
        return mutationOptions<UpdateFilialMutationResponse, ResponseErrorConfig<Error>, {id: UpdateFilialPathParams["id"], data: UpdateFilialMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return updateFilial({ id, data }, config)
          },
        })

}

/**
 * @summary Обновить филиал
 * {@link /org/filials/:id}
 */
export function useUpdateFilial<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateFilialMutationResponse, ResponseErrorConfig<Error>, {id: UpdateFilialPathParams["id"], data: UpdateFilialMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateFilialMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateFilialMutationKey()

          const baseOptions = updateFilialMutationOptions(config) as UseMutationOptions<UpdateFilialMutationResponse, ResponseErrorConfig<Error>, {id: UpdateFilialPathParams["id"], data: UpdateFilialMutationRequest}, TContext>
          

          return useMutation<UpdateFilialMutationResponse, ResponseErrorConfig<Error>, {id: UpdateFilialPathParams["id"], data: UpdateFilialMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateFilialMutationResponse, ResponseErrorConfig<Error>, {id: UpdateFilialPathParams["id"], data: UpdateFilialMutationRequest}, TContext>
      
}