/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { UpdateCorrectionTypeMutationRequest, UpdateCorrectionTypeMutationResponse, UpdateCorrectionTypePathParams } from "../../types/orgController/UpdateCorrectionType";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateCorrectionType } from "../../clients/orgController/updateCorrectionType";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateCorrectionTypeMutationKey = () => [{ url: '/org/correction-types/:id' }] as const

export type UpdateCorrectionTypeMutationKey = ReturnType<typeof updateCorrectionTypeMutationKey>

export function updateCorrectionTypeMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateCorrectionTypeMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateCorrectionTypeMutationKey()
        return mutationOptions<UpdateCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: UpdateCorrectionTypePathParams["id"], data: UpdateCorrectionTypeMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return updateCorrectionType({ id, data }, config)
          },
        })

}

/**
 * @summary Обновить тип корректировки
 * {@link /org/correction-types/:id}
 */
export function useUpdateCorrectionType<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: UpdateCorrectionTypePathParams["id"], data: UpdateCorrectionTypeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateCorrectionTypeMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateCorrectionTypeMutationKey()

          const baseOptions = updateCorrectionTypeMutationOptions(config) as UseMutationOptions<UpdateCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: UpdateCorrectionTypePathParams["id"], data: UpdateCorrectionTypeMutationRequest}, TContext>
          

          return useMutation<UpdateCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: UpdateCorrectionTypePathParams["id"], data: UpdateCorrectionTypeMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateCorrectionTypeMutationResponse, ResponseErrorConfig<Error>, {id: UpdateCorrectionTypePathParams["id"], data: UpdateCorrectionTypeMutationRequest}, TContext>
      
}