/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Notification2 } from "../Notification2";

/**
 * @description Уведомления текущего пользователя
*/
export type GetNotifications200 = Notification2[];

export type GetNotificationsQueryResponse = GetNotifications200;

export type GetNotificationsQuery = {
    Response: GetNotifications200;
    Errors: any;
};