/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface MarkNotificationsReadByFactPackagePathParams {
    /**
     * @type integer
    */
    factPackageId: number;
}

/**
 * @description Уведомления помечены прочитанными
*/
export interface MarkNotificationsReadByFactPackage200 {
    /**
     * @description Число записей, реально переведённых из непрочитанных в прочитанные
     * @type integer
    */
    updatedCount: number;
}

export type MarkNotificationsReadByFactPackageMutationResponse = MarkNotificationsReadByFactPackage200;

export type MarkNotificationsReadByFactPackageMutation = {
    Response: MarkNotificationsReadByFactPackage200;
    PathParams: MarkNotificationsReadByFactPackagePathParams;
    Errors: any;
};