/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Уведомления помечены прочитанными
*/
export interface MarkAllNotificationsRead200 {
    /**
     * @description Число записей, реально переведённых из непрочитанных в прочитанные
     * @type integer
    */
    updatedCount: number;
}

export type MarkAllNotificationsReadMutationResponse = MarkAllNotificationsRead200;

export type MarkAllNotificationsReadMutation = {
    Response: MarkAllNotificationsRead200;
    Errors: any;
};