/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface MarkNotificationsReadByCorrectionPathParams {
    /**
     * @type integer
    */
    correctionId: number;
}

/**
 * @description Уведомления помечены прочитанными
*/
export interface MarkNotificationsReadByCorrection200 {
    /**
     * @description Число записей, реально переведённых из непрочитанных в прочитанные
     * @type integer
    */
    updatedCount: number;
}

export type MarkNotificationsReadByCorrectionMutationResponse = MarkNotificationsReadByCorrection200;

export type MarkNotificationsReadByCorrectionMutation = {
    Response: MarkNotificationsReadByCorrection200;
    PathParams: MarkNotificationsReadByCorrectionPathParams;
    Errors: any;
};