/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPlanStatsFilial200, GetPlanStatsFilial403, GetPlanStatsFilialQueryResponse } from "../../types/plansController/GetPlanStatsFilial";
import { createErrorResponse2 } from "../createErrorResponse2";
import { createPlanStats2 } from "../createPlanStats2";
import { faker } from "@faker-js/faker";

/**
 * @description Агрегированные счётчики в рамках видимости роли FILIAL
 */
export function createGetPlanStatsFilial200(data?: Partial<GetPlanStatsFilial200>): GetPlanStatsFilial200 {

  return createPlanStats2(data)
}

/**
 * @description У пользователя не роль FILIAL
 */
export function createGetPlanStatsFilial403(data?: Partial<GetPlanStatsFilial403>): GetPlanStatsFilial403 {

  return createErrorResponse2(data)
}

export function createGetPlanStatsFilialQueryResponse(data?: Partial<GetPlanStatsFilialQueryResponse>): GetPlanStatsFilialQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetPlanStatsFilial200()])
}