/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReopenPlanRemark200, ReopenPlanRemarkMutationRequest, ReopenPlanRemarkMutationResponse, ReopenPlanRemarkPathParams } from "../../types/plansController/ReopenPlanRemark";
import { createPlanRemark } from "../createPlanRemark";
import { createPlanRemarkReopenInput } from "../createPlanRemarkReopenInput";
import { faker } from "@faker-js/faker";

export function createReopenPlanRemarkPathParams(data?: Partial<ReopenPlanRemarkPathParams>): ReopenPlanRemarkPathParams {

  return {
    ...{"humanId": faker.string.alpha(),"remarkId": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Замечание переоткрыто
 */
export function createReopenPlanRemark200(data?: Partial<ReopenPlanRemark200>): ReopenPlanRemark200 {

  return createPlanRemark(data)
}

export function createReopenPlanRemarkMutationRequest(data?: Partial<ReopenPlanRemarkMutationRequest>): ReopenPlanRemarkMutationRequest {

  return createPlanRemarkReopenInput(data)
}

export function createReopenPlanRemarkMutationResponse(data?: Partial<ReopenPlanRemarkMutationResponse>): ReopenPlanRemarkMutationResponse {

  return data || faker.helpers.arrayElement<any>([createReopenPlanRemark200()])
}