/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReturnPlanByDtoe200, ReturnPlanByDtoeMutationResponse, ReturnPlanByDtoePathParams } from "../../types/plansController/ReturnPlanByDtoe";
import { createPlanDetail } from "../createPlanDetail";
import { faker } from "@faker-js/faker";

export function createReturnPlanByDtoePathParams(data?: Partial<ReturnPlanByDtoePathParams>): ReturnPlanByDtoePathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Возвращено ДТОиР на доработку
 */
export function createReturnPlanByDtoe200(data?: Partial<ReturnPlanByDtoe200>): ReturnPlanByDtoe200 {

  return createPlanDetail(data)
}

export function createReturnPlanByDtoeMutationResponse(data?: Partial<ReturnPlanByDtoeMutationResponse>): ReturnPlanByDtoeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createReturnPlanByDtoe200()])
}