/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPlan200, GetPlan403, GetPlan404, GetPlanPathParams, GetPlanQueryResponse } from "../../types/plansController/GetPlan";
import { createErrorResponse2 } from "../createErrorResponse2";
import { createPlanDetail } from "../createPlanDetail";
import { faker } from "@faker-js/faker";

export function createGetPlanPathParams(data?: Partial<GetPlanPathParams>): GetPlanPathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Детальная карточка плана
 */
export function createGetPlan200(data?: Partial<GetPlan200>): GetPlan200 {

  return createPlanDetail(data)
}

/**
 * @description Нет доступа к этому плану
 */
export function createGetPlan403(data?: Partial<GetPlan403>): GetPlan403 {

  return createErrorResponse2(data)
}

/**
 * @description Не найдено
 */
export function createGetPlan404(data?: Partial<GetPlan404>): GetPlan404 {

  return createErrorResponse2(data)
}

export function createGetPlanQueryResponse(data?: Partial<GetPlanQueryResponse>): GetPlanQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetPlan200()])
}