/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreatePlan201, CreatePlanMutationRequest, CreatePlanMutationResponse } from "../../types/plansController/CreatePlan";
import { createPlanCreateInput } from "../createPlanCreateInput";
import { createPlanDetail } from "../createPlanDetail";
import { faker } from "@faker-js/faker";

/**
 * @description План создан
 */
export function createCreatePlan201(data?: Partial<CreatePlan201>): CreatePlan201 {

  return createPlanDetail(data)
}

export function createCreatePlanMutationRequest(data?: Partial<CreatePlanMutationRequest>): CreatePlanMutationRequest {

  return createPlanCreateInput(data)
}

export function createCreatePlanMutationResponse(data?: Partial<CreatePlanMutationResponse>): CreatePlanMutationResponse {

  return data || faker.helpers.arrayElement<any>([createCreatePlan201()])
}