/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UploadPlanFileVersion201, UploadPlanFileVersionMutationRequest, UploadPlanFileVersionMutationResponse, UploadPlanFileVersionPathParams } from "../../types/plansController/UploadPlanFileVersion";
import { createPlanFileVersion2 } from "../createPlanFileVersion2";
import { faker } from "@faker-js/faker";

export function createUploadPlanFileVersionPathParams(data?: Partial<UploadPlanFileVersionPathParams>): UploadPlanFileVersionPathParams {

  return {
    ...{"humanId": faker.string.alpha(),"slotId": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Новая версия файла добавлена в ячейку
 */
export function createUploadPlanFileVersion201(data?: Partial<UploadPlanFileVersion201>): UploadPlanFileVersion201 {

  return createPlanFileVersion2(data)
}

export function createUploadPlanFileVersionMutationRequest(data?: Partial<UploadPlanFileVersionMutationRequest>): UploadPlanFileVersionMutationRequest {

  return {
    ...{"file": faker.image.url() as unknown as Blob,"note": faker.string.alpha(),"remarkId": faker.number.int()},
    ...data || {}
  }
}

export function createUploadPlanFileVersionMutationResponse(data?: Partial<UploadPlanFileVersionMutationResponse>): UploadPlanFileVersionMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUploadPlanFileVersion201()])
}