/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPlanStatsDtoe200, GetPlanStatsDtoe403, GetPlanStatsDtoeQueryResponse } from "../../types/plansController/GetPlanStatsDtoe";
import { createErrorResponse2 } from "../createErrorResponse2";
import { createPlanStats2 } from "../createPlanStats2";
import { faker } from "@faker-js/faker";

/**
 * @description Агрегированные счётчики в рамках видимости роли DTOE
 */
export function createGetPlanStatsDtoe200(data?: Partial<GetPlanStatsDtoe200>): GetPlanStatsDtoe200 {

  return createPlanStats2(data)
}

/**
 * @description У пользователя не роль DTOE
 */
export function createGetPlanStatsDtoe403(data?: Partial<GetPlanStatsDtoe403>): GetPlanStatsDtoe403 {

  return createErrorResponse2(data)
}

export function createGetPlanStatsDtoeQueryResponse(data?: Partial<GetPlanStatsDtoeQueryResponse>): GetPlanStatsDtoeQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetPlanStatsDtoe200()])
}