/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SendPlan200, SendPlan400, SendPlanMutationRequest, SendPlanMutationResponse, SendPlanPathParams } from "../../types/plansController/SendPlan";
import { createErrorResponse2 } from "../createErrorResponse2";
import { createPlanCfoSelectionInput } from "../createPlanCfoSelectionInput";
import { createPlanDetail } from "../createPlanDetail";
import { faker } from "@faker-js/faker";

export function createSendPlanPathParams(data?: Partial<SendPlanPathParams>): SendPlanPathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Направлено
 */
export function createSendPlan200(data?: Partial<SendPlan200>): SendPlan200 {

  return createPlanDetail(data)
}

/**
 * @description Пакет не укомплектован либо ЦФО не выбраны/не привязаны
 */
export function createSendPlan400(data?: Partial<SendPlan400>): SendPlan400 {

  return createErrorResponse2(data)
}

export function createSendPlanMutationRequest(data?: Partial<SendPlanMutationRequest>): SendPlanMutationRequest {

  return createPlanCfoSelectionInput(data)
}

export function createSendPlanMutationResponse(data?: Partial<SendPlanMutationResponse>): SendPlanMutationResponse {

  return data || faker.helpers.arrayElement<any>([createSendPlan200()])
}