/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { factPackageDetailSchema } from "../factPackageDetailSchema";

export const approveFactPackageByCfoPathParamsSchema = z.object({
    "humanId": z.string(),
"cfoId": z.int()
    })

/**
 * @description Согласовано
 */
export const approveFactPackageByCfo200Schema = z.lazy(() => factPackageDetailSchema)

/**
 * @description Решение по этому факт-пакету уже принято этим ЦФО
 */
export const approveFactPackageByCfo400Schema = z.lazy(() => errorResponse2Schema)

/**
 * @description Нет доступа
 */
export const approveFactPackageByCfo403Schema = z.lazy(() => errorResponse2Schema)

export const approveFactPackageByCfoMutationResponseSchema = z.lazy(() => approveFactPackageByCfo200Schema)