/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { factPackageCreateInputSchema } from "../factPackageCreateInputSchema";
import { factPackageDetailSchema } from "../factPackageDetailSchema";

/**
 * @description Факт-пакет создан
 */
export const createFactPackage201Schema = z.lazy(() => factPackageDetailSchema)

/**
 * @description Доступно только роли FILIAL
 */
export const createFactPackage403Schema = z.lazy(() => errorResponse2Schema)

export const createFactPackageMutationRequestSchema = z.lazy(() => factPackageCreateInputSchema)

export const createFactPackageMutationResponseSchema = z.lazy(() => createFactPackage201Schema)