/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { factFinalDecisionSchema } from "../factFinalDecisionSchema";
import { factPackageDetailSchema } from "../factPackageDetailSchema";

export const decideFactPackageByDtoePathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Решение принято
 */
export const decideFactPackageByDtoe200Schema = z.lazy(() => factPackageDetailSchema)

/**
 * @description Факт-пакет не на проверке ДТОиР, либо RETURN без открытого замечания
 */
export const decideFactPackageByDtoe400Schema = z.lazy(() => errorResponse2Schema)

/**
 * @description Нет доступа
 */
export const decideFactPackageByDtoe403Schema = z.lazy(() => errorResponse2Schema)

export const decideFactPackageByDtoeMutationRequestSchema = z.lazy(() => factFinalDecisionSchema)

export const decideFactPackageByDtoeMutationResponseSchema = z.lazy(() => decideFactPackageByDtoe200Schema)