/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { factPackageRemarkSchema } from "../factPackageRemarkSchema";

export const fixFactPackageRemarkPathParamsSchema = z.object({
    "humanId": z.string(),
"remarkId": z.int()
    })

/**
 * @description Замечание отмечено исправленным
 */
export const fixFactPackageRemark200Schema = z.lazy(() => factPackageRemarkSchema)

/**
 * @description Нет доступа
 */
export const fixFactPackageRemark403Schema = z.lazy(() => errorResponse2Schema)

export const fixFactPackageRemarkMutationResponseSchema = z.lazy(() => fixFactPackageRemark200Schema)