/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { factPackageStatsSchema } from "../factPackageStatsSchema";

/**
 * @description Агрегированные счётчики в рамках видимости роли FILIAL
 */
export const getFactPackageStatsFilial200Schema = z.lazy(() => factPackageStatsSchema)

/**
 * @description У пользователя не роль FILIAL
 */
export const getFactPackageStatsFilial403Schema = z.lazy(() => errorResponse2Schema)

export const getFactPackageStatsFilialQueryResponseSchema = z.lazy(() => getFactPackageStatsFilial200Schema)