/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { factPackageStatsSchema } from "../factPackageStatsSchema";

/**
 * @description Агрегированные счётчики для карточек дашборда (в рамках видимости роли)
 */
export const getFactPackageStats200Schema = z.lazy(() => factPackageStatsSchema)

export const getFactPackageStatsQueryResponseSchema = z.lazy(() => getFactPackageStats200Schema)