/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { factPackageStatsSchema } from "../factPackageStatsSchema";

/**
 * @description Агрегированные счётчики в рамках видимости роли CFO
 */
export const getFactPackageStatsCfo200Schema = z.lazy(() => factPackageStatsSchema)

/**
 * @description У пользователя не роль CFO
 */
export const getFactPackageStatsCfo403Schema = z.lazy(() => errorResponse2Schema)

export const getFactPackageStatsCfoQueryResponseSchema = z.lazy(() => getFactPackageStatsCfo200Schema)