/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { direction2Schema } from "../direction2Schema";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { factPackageDetailSchema } from "../factPackageDetailSchema";

export const getOrCreateFactPackageByDirectionPathParamsSchema = z.object({
    get "direction"(){
                return direction2Schema
              }
    })

/**
 * @description Факт-пакет получен либо создан
 */
export const getOrCreateFactPackageByDirection200Schema = z.lazy(() => factPackageDetailSchema)

/**
 * @description Доступно только роли FILIAL
 */
export const getOrCreateFactPackageByDirection403Schema = z.lazy(() => errorResponse2Schema)

export const getOrCreateFactPackageByDirectionQueryResponseSchema = z.lazy(() => getOrCreateFactPackageByDirection200Schema)