/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { factFormCode2Schema } from "../factFormCode2Schema";
import { factFormVersion2Schema } from "../factFormVersion2Schema";

export const uploadFactFormVersionPathParamsSchema = z.object({
    "humanId": z.string(),
get "formCode"(){
                return factFormCode2Schema
              }
    })

/**
 * @description Новая версия формы добавлена
 */
export const uploadFactFormVersion201Schema = z.lazy(() => factFormVersion2Schema)

/**
 * @description Факт-пакет в финальном статусе либо formCode не входит в каталог направления
 */
export const uploadFactFormVersion400Schema = z.lazy(() => errorResponse2Schema)

/**
 * @description Нет доступа (не автор/не владелец филиала)
 */
export const uploadFactFormVersion403Schema = z.lazy(() => errorResponse2Schema)

export const uploadFactFormVersionMutationRequestSchema = z.object({
    "file": z.instanceof(File),
"note": z.optional(z.string()),
"remarkId": z.optional(z.int())
    })

export const uploadFactFormVersionMutationResponseSchema = z.lazy(() => uploadFactFormVersion201Schema)