/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Текущая сессия завершена, cookie очищена
*/
export type Logout204 = unknown;

export type LogoutMutationResponse = Logout204;

export type LogoutMutation = {
    Response: Logout204;
    Errors: any;
};