/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";

/**
 * @description Все сессии пользователя завершены, куки текущей сессии очищены
*/
export type LogoutAll204 = unknown;

/**
 * @description Не авторизован
*/
export type LogoutAll401 = ErrorResponse2;

export type LogoutAllMutationResponse = LogoutAll204;

export type LogoutAllMutation = {
    Response: LogoutAll204;
    Errors: LogoutAll401;
};