/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanDetail } from "../PlanDetail";

export interface ApprovePlanByDtoePathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Согласовано ДТОиР
*/
export type ApprovePlanByDtoe200 = PlanDetail;

export type ApprovePlanByDtoeMutationResponse = ApprovePlanByDtoe200;

export type ApprovePlanByDtoeMutation = {
    Response: ApprovePlanByDtoe200;
    PathParams: ApprovePlanByDtoePathParams;
    Errors: any;
};