/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanDetail } from "../PlanDetail";

export interface ApprovePlanByCfoPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Согласовано
*/
export type ApprovePlanByCfo200 = PlanDetail;

export type ApprovePlanByCfoMutationResponse = ApprovePlanByCfo200;

export type ApprovePlanByCfoMutation = {
    Response: ApprovePlanByCfo200;
    PathParams: ApprovePlanByCfoPathParams;
    Errors: any;
};