/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";
import type { PlanDetail } from "../PlanDetail";

export interface CancelPlanCfoDecisionPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Решение ЦФО отменено, статус возвращён в PENDING
*/
export type CancelPlanCfoDecision200 = PlanDetail;

/**
 * @description Нечего отменять или план уже вне зоны ответственности ЦФО
*/
export type CancelPlanCfoDecision400 = ErrorResponse2;

export type CancelPlanCfoDecisionMutationResponse = CancelPlanCfoDecision200;

export type CancelPlanCfoDecisionMutation = {
    Response: CancelPlanCfoDecision200;
    PathParams: CancelPlanCfoDecisionPathParams;
    Errors: CancelPlanCfoDecision400;
};