/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";
import type { PlanDetail } from "../PlanDetail";
import type { PlanTypeChangeInput } from "../PlanTypeChangeInput";

export interface ChangePlanTypePathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Тип изменён
*/
export type ChangePlanType200 = PlanDetail;

/**
 * @description План не в статусе «Черновик»
*/
export type ChangePlanType400 = ErrorResponse2;

/**
 * @description Нет доступа (не автор/не владелец филиала)
*/
export type ChangePlanType403 = ErrorResponse2;

/**
 * @description План или тип плана не найдены
*/
export type ChangePlanType404 = ErrorResponse2;

export type ChangePlanTypeMutationRequest = PlanTypeChangeInput;

export type ChangePlanTypeMutationResponse = ChangePlanType200;

export type ChangePlanTypeMutation = {
    Response: ChangePlanType200;
    Request: ChangePlanTypeMutationRequest;
    PathParams: ChangePlanTypePathParams;
    Errors: ChangePlanType400 | ChangePlanType403 | ChangePlanType404;
};