/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface DeletePlanRemarkPathParams {
    /**
     * @type string
    */
    humanId: string;
    /**
     * @type integer
    */
    remarkId: number;
}

/**
 * @description Замечание удалено
*/
export type DeletePlanRemark204 = unknown;

export type DeletePlanRemarkMutationResponse = DeletePlanRemark204;

export type DeletePlanRemarkMutation = {
    Response: DeletePlanRemark204;
    PathParams: DeletePlanRemarkPathParams;
    Errors: any;
};