/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";

export interface DeletePlanPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description План удалён
*/
export type DeletePlan204 = unknown;

/**
 * @description План не в статусе «Черновик»
*/
export type DeletePlan400 = ErrorResponse2;

/**
 * @description Нет доступа (не автор/не владелец филиала)
*/
export type DeletePlan403 = ErrorResponse2;

/**
 * @description Не найдено
*/
export type DeletePlan404 = ErrorResponse2;

export type DeletePlanMutationResponse = DeletePlan204;

export type DeletePlanMutation = {
    Response: DeletePlan204;
    PathParams: DeletePlanPathParams;
    Errors: DeletePlan400 | DeletePlan403 | DeletePlan404;
};