/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";
import type { PlanDetail } from "../PlanDetail";

export interface GetPlanPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Детальная карточка плана
*/
export type GetPlan200 = PlanDetail;

/**
 * @description Нет доступа к этому плану
*/
export type GetPlan403 = ErrorResponse2;

/**
 * @description Не найдено
*/
export type GetPlan404 = ErrorResponse2;

export type GetPlanQueryResponse = GetPlan200;

export type GetPlanQuery = {
    Response: GetPlan200;
    PathParams: GetPlanPathParams;
    Errors: GetPlan403 | GetPlan404;
};