/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedPlans } from "../PaginatedPlans";
import type { PlanStatus2 } from "../PlanStatus2";

export interface GetPlansQueryParams {
    /**
     * @type string | undefined
    */
    status?: PlanStatus2;
    /**
     * @type integer | undefined
    */
    filialId?: number;
    /**
     * @type integer | undefined
    */
    cfoId?: number;
    /**
     * @type integer | undefined
    */
    planTypeId?: number;
    /**
     * @description Поиск по ID плана
     * @type string | undefined
    */
    q?: string;
    /**
     * @type boolean | undefined
    */
    onlyWithRemarks?: boolean;
    /**
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @default 20
     * @type integer | undefined
    */
    pageSize?: number;
}

/**
 * @description Страница планов
*/
export type GetPlans200 = PaginatedPlans;

export type GetPlansQueryResponse = GetPlans200;

export type GetPlansQuery = {
    Response: GetPlans200;
    QueryParams: GetPlansQueryParams;
    Errors: any;
};