/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";
import type { PlanStats2 } from "../PlanStats2";

/**
 * @description Агрегированные счётчики в рамках видимости роли FILIAL
*/
export type GetPlanStatsFilial200 = PlanStats2;

/**
 * @description У пользователя не роль FILIAL
*/
export type GetPlanStatsFilial403 = ErrorResponse2;

export type GetPlanStatsFilialQueryResponse = GetPlanStatsFilial200;

export type GetPlanStatsFilialQuery = {
    Response: GetPlanStatsFilial200;
    Errors: GetPlanStatsFilial403;
};