/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanRemark } from "../PlanRemark";
import type { PlanRemarkReopenInput } from "../PlanRemarkReopenInput";

export interface ReopenPlanRemarkPathParams {
    /**
     * @type string
    */
    humanId: string;
    /**
     * @type integer
    */
    remarkId: number;
}

/**
 * @description Замечание переоткрыто
*/
export type ReopenPlanRemark200 = PlanRemark;

export type ReopenPlanRemarkMutationRequest = PlanRemarkReopenInput;

export type ReopenPlanRemarkMutationResponse = ReopenPlanRemark200;

export type ReopenPlanRemarkMutation = {
    Response: ReopenPlanRemark200;
    Request: ReopenPlanRemarkMutationRequest;
    PathParams: ReopenPlanRemarkPathParams;
    Errors: any;
};