/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanDetail } from "../PlanDetail";

export interface ReturnPlanByDtoePathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Возвращено ДТОиР на доработку
*/
export type ReturnPlanByDtoe200 = PlanDetail;

export type ReturnPlanByDtoeMutationResponse = ReturnPlanByDtoe200;

export type ReturnPlanByDtoeMutation = {
    Response: ReturnPlanByDtoe200;
    PathParams: ReturnPlanByDtoePathParams;
    Errors: any;
};