/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";
import type { PlanDetail } from "../PlanDetail";

export interface SendPlanToDtoePathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Отправлено в ДТОиР
*/
export type SendPlanToDtoe200 = PlanDetail;

/**
 * @description Не все обязательные ЦФО согласовали пакет
*/
export type SendPlanToDtoe400 = ErrorResponse2;

export type SendPlanToDtoeMutationResponse = SendPlanToDtoe200;

export type SendPlanToDtoeMutation = {
    Response: SendPlanToDtoe200;
    PathParams: SendPlanToDtoePathParams;
    Errors: SendPlanToDtoe400;
};