/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";
import type { PlanCfoSelectionInput } from "../PlanCfoSelectionInput";
import type { PlanDetail } from "../PlanDetail";

export interface SendPlanPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Направлено
*/
export type SendPlan200 = PlanDetail;

/**
 * @description Пакет не укомплектован либо ЦФО не выбраны/не привязаны
*/
export type SendPlan400 = ErrorResponse2;

export type SendPlanMutationRequest = PlanCfoSelectionInput;

export type SendPlanMutationResponse = SendPlan200;

export type SendPlanMutation = {
    Response: SendPlan200;
    Request: SendPlanMutationRequest;
    PathParams: SendPlanPathParams;
    Errors: SendPlan400;
};