/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanFileVersion2 } from "../PlanFileVersion2";

export interface UploadPlanFileVersionPathParams {
    /**
     * @type string
    */
    humanId: string;
    /**
     * @type integer
    */
    slotId: number;
}

/**
 * @description Новая версия файла добавлена в ячейку
*/
export type UploadPlanFileVersion201 = PlanFileVersion2;

export interface UploadPlanFileVersionMutationRequest {
    /**
     * @type string, binary
    */
    file: Blob;
    /**
     * @type string | undefined
    */
    note?: string;
    /**
     * @description Если файл загружен в ответ на замечание
     * @type integer | undefined
    */
    remarkId?: number;
}

export type UploadPlanFileVersionMutationResponse = UploadPlanFileVersion201;

export type UploadPlanFileVersionMutation = {
    Response: UploadPlanFileVersion201;
    Request: UploadPlanFileVersionMutationRequest;
    PathParams: UploadPlanFileVersionPathParams;
    Errors: any;
};