/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { correctionDetailSchema } from "../correctionDetailSchema";

export const approveCorrectionByCfoPathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Согласовано
 */
export const approveCorrectionByCfo200Schema = z.lazy(() => correctionDetailSchema)

export const approveCorrectionByCfoMutationResponseSchema = z.lazy(() => approveCorrectionByCfo200Schema)