/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const deleteCorrectionPathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Корректировка удалена
 */
export const deleteCorrection204Schema = z.unknown()

export const deleteCorrectionMutationResponseSchema = z.lazy(() => deleteCorrection204Schema)