/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { correctionDetailSchema } from "../correctionDetailSchema";
import { errorResponse2Schema } from "../errorResponse2Schema";

export const getCorrectionPathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Детальная карточка корректировки
 */
export const getCorrection200Schema = z.lazy(() => correctionDetailSchema)

/**
 * @description Нет доступа к этой корректировке
 */
export const getCorrection403Schema = z.lazy(() => errorResponse2Schema)

/**
 * @description Не найдено
 */
export const getCorrection404Schema = z.lazy(() => errorResponse2Schema)

export const getCorrectionQueryResponseSchema = z.lazy(() => getCorrection200Schema)