/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { correctionStats2Schema } from "../correctionStats2Schema";
import { errorResponse2Schema } from "../errorResponse2Schema";

/**
 * @description Агрегированные счётчики в рамках видимости роли FILIAL
 */
export const getCorrectionStatsFilial200Schema = z.lazy(() => correctionStats2Schema)

/**
 * @description У пользователя не роль FILIAL
 */
export const getCorrectionStatsFilial403Schema = z.lazy(() => errorResponse2Schema)

export const getCorrectionStatsFilialQueryResponseSchema = z.lazy(() => getCorrectionStatsFilial200Schema)