/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { correctionStats2Schema } from "../correctionStats2Schema";
import { errorResponse2Schema } from "../errorResponse2Schema";

/**
 * @description Агрегированные счётчики в рамках видимости роли CFO
 */
export const getCorrectionStatsCfo200Schema = z.lazy(() => correctionStats2Schema)

/**
 * @description У пользователя не роль CFO
 */
export const getCorrectionStatsCfo403Schema = z.lazy(() => errorResponse2Schema)

export const getCorrectionStatsCfoQueryResponseSchema = z.lazy(() => getCorrectionStatsCfo200Schema)