/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { remarkSchema } from "../remarkSchema";

export const markRemarkFixedPathParamsSchema = z.object({
    "humanId": z.string(),
"remarkId": z.int()
    })

/**
 * @description Отмечено исправленным
 */
export const markRemarkFixed200Schema = z.lazy(() => remarkSchema)

export const markRemarkFixedMutationResponseSchema = z.lazy(() => markRemarkFixed200Schema)