/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { remarkReopenInputSchema } from "../remarkReopenInputSchema";
import { remarkSchema } from "../remarkSchema";

export const reopenRemarkPathParamsSchema = z.object({
    "humanId": z.string(),
"remarkId": z.int()
    })

/**
 * @description Замечание переоткрыто
 */
export const reopenRemark200Schema = z.lazy(() => remarkSchema)

export const reopenRemarkMutationRequestSchema = z.lazy(() => remarkReopenInputSchema)

export const reopenRemarkMutationResponseSchema = z.lazy(() => reopenRemark200Schema)