/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { correctionDetailSchema } from "../correctionDetailSchema";

export const resubmitCorrectionToDtoePathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Повторно направлено в ДТОиР
 */
export const resubmitCorrectionToDtoe200Schema = z.lazy(() => correctionDetailSchema)

export const resubmitCorrectionToDtoeMutationResponseSchema = z.lazy(() => resubmitCorrectionToDtoe200Schema)