/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { correctionDetailSchema } from "../correctionDetailSchema";

export const returnCorrectionByDtoePathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Возвращено ДТОиР на доработку
 */
export const returnCorrectionByDtoe200Schema = z.lazy(() => correctionDetailSchema)

export const returnCorrectionByDtoeMutationResponseSchema = z.lazy(() => returnCorrectionByDtoe200Schema)