/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { fileVersion2Schema } from "../fileVersion2Schema";

export const uploadFileVersionPathParamsSchema = z.object({
    "humanId": z.string(),
"slotId": z.int()
    })

/**
 * @description Новая версия файла добавлена в ячейку
 */
export const uploadFileVersion201Schema = z.lazy(() => fileVersion2Schema)

export const uploadFileVersionMutationRequestSchema = z.object({
    "file": z.instanceof(File),
"note": z.optional(z.string()),
"remarkId": z.optional(z.int())
    })

export const uploadFileVersionMutationResponseSchema = z.lazy(() => uploadFileVersion201Schema)