/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Role2 } from "../Role2";
import type { User } from "../User";

export interface GetUsersQueryParams {
    /**
     * @description FILIAL/CFO/DTOE — роли из старого Django-проекта (accounts.Role). ADMIN — эквивалент is_staff/is_superuser (управление справочниками и пользователями).\n
     * @type string | undefined
    */
    role?: Role2;
    /**
     * @type integer | undefined
    */
    filialId?: number;
    /**
     * @type integer | undefined
    */
    cfoId?: number;
    /**
     * @description Поиск по логину/ФИО
     * @type string | undefined
    */
    q?: string;
}

/**
 * @description Список пользователей
*/
export type GetUsers200 = User[];

export type GetUsersQueryResponse = GetUsers200;

export type GetUsersQuery = {
    Response: GetUsers200;
    QueryParams: GetUsersQueryParams;
    Errors: any;
};