/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "../User";
import type { UserUpdateInput } from "../UserUpdateInput";

export interface UpdateUserPathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Пользователь обновлён
*/
export type UpdateUser200 = User;

export type UpdateUserMutationRequest = UserUpdateInput;

export type UpdateUserMutationResponse = UpdateUser200;

export type UpdateUserMutation = {
    Response: UpdateUser200;
    Request: UpdateUserMutationRequest;
    PathParams: UpdateUserPathParams;
    Errors: any;
};