/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CancelPlanCfoDecisionMutationResponse, CancelPlanCfoDecisionPathParams, CancelPlanCfoDecision400 } from "../../types/plansController/CancelPlanCfoDecision";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { cancelPlanCfoDecision } from "../../clients/plansController/cancelPlanCfoDecision";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const cancelPlanCfoDecisionMutationKey = () => [{ url: '/plans/:humanId/cfo-cancel' }] as const

export type CancelPlanCfoDecisionMutationKey = ReturnType<typeof cancelPlanCfoDecisionMutationKey>

export function cancelPlanCfoDecisionMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = cancelPlanCfoDecisionMutationKey()
        return mutationOptions<CancelPlanCfoDecisionMutationResponse, ResponseErrorConfig<CancelPlanCfoDecision400>, {humanId: CancelPlanCfoDecisionPathParams["humanId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId }) => {
            return cancelPlanCfoDecision({ humanId }, config)
          },
        })

}

/**
 * @description Роль CFO. Возвращает статус этого ЦФО (APPROVED или RETURNED) обратно в
 * PENDING — страховка от случайного клика по «Согласовать»/«Вернуть на
 * доработку». Оставленные замечания не удаляются и не меняются, это часть
 * истории — откатывается только статус ЦФО. Недоступно, если план уже
 * передан в ДТОиР (`UNDER_DTOE_REVIEW`/`RETURNED_BY_DTOE`/`APPROVED_BY_DTOE`)
 * — тогда `400`.
 * @summary Отменить собственное решение ЦФО по плану
 * {@link /plans/:humanId/cfo-cancel}
 */
export function useCancelPlanCfoDecision<TContext>(options: 
{
  mutation?: UseMutationOptions<CancelPlanCfoDecisionMutationResponse, ResponseErrorConfig<CancelPlanCfoDecision400>, {humanId: CancelPlanCfoDecisionPathParams["humanId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? cancelPlanCfoDecisionMutationKey()

          const baseOptions = cancelPlanCfoDecisionMutationOptions(config) as UseMutationOptions<CancelPlanCfoDecisionMutationResponse, ResponseErrorConfig<CancelPlanCfoDecision400>, {humanId: CancelPlanCfoDecisionPathParams["humanId"]}, TContext>
          

          return useMutation<CancelPlanCfoDecisionMutationResponse, ResponseErrorConfig<CancelPlanCfoDecision400>, {humanId: CancelPlanCfoDecisionPathParams["humanId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CancelPlanCfoDecisionMutationResponse, ResponseErrorConfig<CancelPlanCfoDecision400>, {humanId: CancelPlanCfoDecisionPathParams["humanId"]}, TContext>
      
}