/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreatePlanMutationRequest, CreatePlanMutationResponse } from "../../types/plansController/CreatePlan";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { createPlan } from "../../clients/plansController/createPlan";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createPlanMutationKey = () => [{ url: '/plans' }] as const

export type CreatePlanMutationKey = ReturnType<typeof createPlanMutationKey>

export function createPlanMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreatePlanMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = createPlanMutationKey()
        return mutationOptions<CreatePlanMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return createPlan({ data }, config)
          },
        })

}

/**
 * @description Доступно только роли FILIAL. Создаёт план и ячейки пакета по типу.
 * @summary Создать план
 * {@link /plans}
 */
export function useCreatePlan<TContext>(options: 
{
  mutation?: UseMutationOptions<CreatePlanMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreatePlanMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? createPlanMutationKey()

          const baseOptions = createPlanMutationOptions(config) as UseMutationOptions<CreatePlanMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanMutationRequest}, TContext>
          

          return useMutation<CreatePlanMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CreatePlanMutationResponse, ResponseErrorConfig<Error>, {data: CreatePlanMutationRequest}, TContext>
      
}