/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeletePlanRemarkMutationResponse, DeletePlanRemarkPathParams } from "../../types/plansController/DeletePlanRemark";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deletePlanRemark } from "../../clients/plansController/deletePlanRemark";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deletePlanRemarkMutationKey = () => [{ url: '/plans/:humanId/remarks/:remarkId' }] as const

export type DeletePlanRemarkMutationKey = ReturnType<typeof deletePlanRemarkMutationKey>

export function deletePlanRemarkMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deletePlanRemarkMutationKey()
        return mutationOptions<DeletePlanRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: DeletePlanRemarkPathParams["humanId"], remarkId: DeletePlanRemarkPathParams["remarkId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, remarkId }) => {
            return deletePlanRemark({ humanId, remarkId }, config)
          },
        })

}

/**
 * @description Только автор замечания и только пока оно в статусе OPEN.
 * @summary Удалить замечание плана (только автор, только пока OPEN)
 * {@link /plans/:humanId/remarks/:remarkId}
 */
export function useDeletePlanRemark<TContext>(options: 
{
  mutation?: UseMutationOptions<DeletePlanRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: DeletePlanRemarkPathParams["humanId"], remarkId: DeletePlanRemarkPathParams["remarkId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deletePlanRemarkMutationKey()

          const baseOptions = deletePlanRemarkMutationOptions(config) as UseMutationOptions<DeletePlanRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: DeletePlanRemarkPathParams["humanId"], remarkId: DeletePlanRemarkPathParams["remarkId"]}, TContext>
          

          return useMutation<DeletePlanRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: DeletePlanRemarkPathParams["humanId"], remarkId: DeletePlanRemarkPathParams["remarkId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeletePlanRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: DeletePlanRemarkPathParams["humanId"], remarkId: DeletePlanRemarkPathParams["remarkId"]}, TContext>
      
}