/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeletePlanMutationResponse, DeletePlanPathParams, DeletePlan400, DeletePlan403, DeletePlan404 } from "../../types/plansController/DeletePlan";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deletePlan } from "../../clients/plansController/deletePlan";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deletePlanMutationKey = () => [{ url: '/plans/:humanId' }] as const

export type DeletePlanMutationKey = ReturnType<typeof deletePlanMutationKey>

export function deletePlanMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deletePlanMutationKey()
        return mutationOptions<DeletePlanMutationResponse, ResponseErrorConfig<DeletePlan400 | DeletePlan403 | DeletePlan404>, {humanId: DeletePlanPathParams["humanId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId }) => {
            return deletePlan({ humanId }, config)
          },
        })

}

/**
 * @description Роль FILIAL, только автор/владелец. Доступно только для плана в статусе
 * `DRAFT` — направленный (любой другой статус) удалить нельзя, `400`.
 * Удаляет план целиком: слоты, версии файлов, замечания, статусы ЦФО,
 * историю и уведомления по каскаду. `DRAFT`-план не может иметь ни одного
 * статуса ЦФО (они создаются только `POST .../send`), поэтому удаление
 * черновика не затрагивает решений проверяющих и не требует их уведомления.
 * @summary Удалить план
 * {@link /plans/:humanId}
 */
export function useDeletePlan<TContext>(options: 
{
  mutation?: UseMutationOptions<DeletePlanMutationResponse, ResponseErrorConfig<DeletePlan400 | DeletePlan403 | DeletePlan404>, {humanId: DeletePlanPathParams["humanId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deletePlanMutationKey()

          const baseOptions = deletePlanMutationOptions(config) as UseMutationOptions<DeletePlanMutationResponse, ResponseErrorConfig<DeletePlan400 | DeletePlan403 | DeletePlan404>, {humanId: DeletePlanPathParams["humanId"]}, TContext>
          

          return useMutation<DeletePlanMutationResponse, ResponseErrorConfig<DeletePlan400 | DeletePlan403 | DeletePlan404>, {humanId: DeletePlanPathParams["humanId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeletePlanMutationResponse, ResponseErrorConfig<DeletePlan400 | DeletePlan403 | DeletePlan404>, {humanId: DeletePlanPathParams["humanId"]}, TContext>
      
}