/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlanStatsFilialQueryResponse, GetPlanStatsFilial403 } from "../../types/plansController/GetPlanStatsFilial";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getPlanStatsFilial } from "../../clients/plansController/getPlanStatsFilial";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getPlanStatsFilialSuspenseQueryKey = () => [{ url: '/plans/stats/filial' }] as const

export type GetPlanStatsFilialSuspenseQueryKey = ReturnType<typeof getPlanStatsFilialSuspenseQueryKey>

export function getPlanStatsFilialSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPlanStatsFilialSuspenseQueryKey()
        return queryOptions<GetPlanStatsFilialQueryResponse, ResponseErrorConfig<GetPlanStatsFilial403>, GetPlanStatsFilialQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getPlanStatsFilial({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Доступно только пользователю роли FILIAL.
 * @summary Статистика по планам для раздела филиала
 * {@link /plans/stats/filial}
 */
export function useGetPlanStatsFilialSuspense<TData = GetPlanStatsFilialQueryResponse, TQueryKey extends QueryKey = GetPlanStatsFilialSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPlanStatsFilialQueryResponse, ResponseErrorConfig<GetPlanStatsFilial403>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPlanStatsFilialSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getPlanStatsFilialSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetPlanStatsFilial403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}