/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlanStatsQueryResponse } from "../../types/plansController/GetPlanStats";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getPlanStats } from "../../clients/plansController/getPlanStats";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPlanStatsQueryKey = () => [{ url: '/plans/stats' }] as const

export type GetPlanStatsQueryKey = ReturnType<typeof getPlanStatsQueryKey>

export function getPlanStatsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPlanStatsQueryKey()
        return queryOptions<GetPlanStatsQueryResponse, ResponseErrorConfig<Error>, GetPlanStatsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getPlanStats({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Статистика по планам для карточек дашборда
 * {@link /plans/stats}
 */
export function useGetPlanStats<TData = GetPlanStatsQueryResponse, TQueryData = GetPlanStatsQueryResponse, TQueryKey extends QueryKey = GetPlanStatsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetPlanStatsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPlanStatsQueryKey()
         

         const query = useQuery({
          ...getPlanStatsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}