/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlanStatsCfoQueryResponse, GetPlanStatsCfo403 } from "../../types/plansController/GetPlanStatsCfo";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getPlanStatsCfo } from "../../clients/plansController/getPlanStatsCfo";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPlanStatsCfoQueryKey = () => [{ url: '/plans/stats/cfo' }] as const

export type GetPlanStatsCfoQueryKey = ReturnType<typeof getPlanStatsCfoQueryKey>

export function getPlanStatsCfoQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPlanStatsCfoQueryKey()
        return queryOptions<GetPlanStatsCfoQueryResponse, ResponseErrorConfig<GetPlanStatsCfo403>, GetPlanStatsCfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getPlanStatsCfo({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Доступно только пользователю роли CFO.
 * @summary Статистика по планам для раздела ЦФО
 * {@link /plans/stats/cfo}
 */
export function useGetPlanStatsCfo<TData = GetPlanStatsCfoQueryResponse, TQueryData = GetPlanStatsCfoQueryResponse, TQueryKey extends QueryKey = GetPlanStatsCfoQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetPlanStatsCfoQueryResponse, ResponseErrorConfig<GetPlanStatsCfo403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPlanStatsCfoQueryKey()
         

         const query = useQuery({
          ...getPlanStatsCfoQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPlanStatsCfo403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}