/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlansQueryResponse, GetPlansQueryParams } from "../../types/plansController/GetPlans";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getPlans } from "../../clients/plansController/getPlans";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPlansQueryKey = (params?: GetPlansQueryParams) => [{ url: '/plans' }, ...(params ? [params] : [])] as const

export type GetPlansQueryKey = ReturnType<typeof getPlansQueryKey>

export function getPlansQueryOptions({ params }: { params?: GetPlansQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPlansQueryKey(params)
        return queryOptions<GetPlansQueryResponse, ResponseErrorConfig<Error>, GetPlansQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getPlans({ params: params }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Список автоматически ограничен ролью: FILIAL видит свои, CFO — направленные его ЦФО, DTOE/ADMIN — все.
 * @summary Список планов (в рамках видимости роли)
 * {@link /plans}
 */
export function useGetPlans<TData = GetPlansQueryResponse, TQueryData = GetPlansQueryResponse, TQueryKey extends QueryKey = GetPlansQueryKey>({ params }: { params?: GetPlansQueryParams } = {}, options: 
{
  query?: Partial<QueryObserverOptions<GetPlansQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPlansQueryKey(params)
         

         const query = useQuery({
          ...getPlansQueryOptions({ params }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}