/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlanStatsQueryResponse } from "../../types/plansController/GetPlanStats";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getPlanStats } from "../../clients/plansController/getPlanStats";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getPlanStatsSuspenseQueryKey = () => [{ url: '/plans/stats' }] as const

export type GetPlanStatsSuspenseQueryKey = ReturnType<typeof getPlanStatsSuspenseQueryKey>

export function getPlanStatsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPlanStatsSuspenseQueryKey()
        return queryOptions<GetPlanStatsQueryResponse, ResponseErrorConfig<Error>, GetPlanStatsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getPlanStats({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Статистика по планам для карточек дашборда
 * {@link /plans/stats}
 */
export function useGetPlanStatsSuspense<TData = GetPlanStatsQueryResponse, TQueryKey extends QueryKey = GetPlanStatsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPlanStatsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPlanStatsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getPlanStatsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}