/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlanQueryResponse, GetPlanPathParams, GetPlan403, GetPlan404 } from "../../types/plansController/GetPlan";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getPlan } from "../../clients/plansController/getPlan";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPlanQueryKey = ({ humanId }: { humanId: GetPlanPathParams["humanId"] | undefined }) => [{ url: '/plans/:humanId', params: {humanId:humanId} }] as const

export type GetPlanQueryKey = ReturnType<typeof getPlanQueryKey>

export function getPlanQueryOptions({ humanId }: { humanId: GetPlanPathParams["humanId"] | undefined }, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getPlanQueryKey({ humanId })
        return queryOptions<GetPlanQueryResponse, ResponseErrorConfig<GetPlan403 | GetPlan404>, GetPlanQueryResponse, typeof queryKey>({
         enabled: !!(humanId),
         queryKey,
         queryFn: async ({ signal }) => {
            return getPlan({ humanId: humanId! }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Детальная карточка плана
 * {@link /plans/:humanId}
 */
export function useGetPlan<TData = GetPlanQueryResponse, TQueryData = GetPlanQueryResponse, TQueryKey extends QueryKey = GetPlanQueryKey>({ humanId }: { humanId: GetPlanPathParams["humanId"] | undefined }, options: 
{
  query?: Partial<QueryObserverOptions<GetPlanQueryResponse, ResponseErrorConfig<GetPlan403 | GetPlan404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getPlanQueryKey({ humanId })
         

         const query = useQuery({
          ...getPlanQueryOptions({ humanId }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPlan403 | GetPlan404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}