/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { MarkPlanRemarkFixedMutationResponse, MarkPlanRemarkFixedPathParams } from "../../types/plansController/MarkPlanRemarkFixed";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { markPlanRemarkFixed } from "../../clients/plansController/markPlanRemarkFixed";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const markPlanRemarkFixedMutationKey = () => [{ url: '/plans/:humanId/remarks/:remarkId/fix' }] as const

export type MarkPlanRemarkFixedMutationKey = ReturnType<typeof markPlanRemarkFixedMutationKey>

export function markPlanRemarkFixedMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = markPlanRemarkFixedMutationKey()
        return mutationOptions<MarkPlanRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkPlanRemarkFixedPathParams["humanId"], remarkId: MarkPlanRemarkFixedPathParams["remarkId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, remarkId }) => {
            return markPlanRemarkFixed({ humanId, remarkId }, config)
          },
        })

}

/**
 * @description Роль FILIAL (владелец). Отмечает замечание исправленным, не закрывает его.
 * @summary Отметить замечание плана исправленным
 * {@link /plans/:humanId/remarks/:remarkId/fix}
 */
export function useMarkPlanRemarkFixed<TContext>(options: 
{
  mutation?: UseMutationOptions<MarkPlanRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkPlanRemarkFixedPathParams["humanId"], remarkId: MarkPlanRemarkFixedPathParams["remarkId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? markPlanRemarkFixedMutationKey()

          const baseOptions = markPlanRemarkFixedMutationOptions(config) as UseMutationOptions<MarkPlanRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkPlanRemarkFixedPathParams["humanId"], remarkId: MarkPlanRemarkFixedPathParams["remarkId"]}, TContext>
          

          return useMutation<MarkPlanRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkPlanRemarkFixedPathParams["humanId"], remarkId: MarkPlanRemarkFixedPathParams["remarkId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MarkPlanRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkPlanRemarkFixedPathParams["humanId"], remarkId: MarkPlanRemarkFixedPathParams["remarkId"]}, TContext>
      
}