/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ResubmitPlanToDtoeMutationResponse, ResubmitPlanToDtoePathParams } from "../../types/plansController/ResubmitPlanToDtoe";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { resubmitPlanToDtoe } from "../../clients/plansController/resubmitPlanToDtoe";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const resubmitPlanToDtoeMutationKey = () => [{ url: '/plans/:humanId/resubmit-to-dtoe' }] as const

export type ResubmitPlanToDtoeMutationKey = ReturnType<typeof resubmitPlanToDtoeMutationKey>

export function resubmitPlanToDtoeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = resubmitPlanToDtoeMutationKey()
        return mutationOptions<ResubmitPlanToDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanToDtoePathParams["humanId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId }) => {
            return resubmitPlanToDtoe({ humanId }, config)
          },
        })

}

/**
 * @description После исправления замечаний ДТОиР — направление напрямую, минуя ЦФО.
 * @summary Повторно направить в ДТОиР после исправления замечаний ДТОиР
 * {@link /plans/:humanId/resubmit-to-dtoe}
 */
export function useResubmitPlanToDtoe<TContext>(options: 
{
  mutation?: UseMutationOptions<ResubmitPlanToDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanToDtoePathParams["humanId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? resubmitPlanToDtoeMutationKey()

          const baseOptions = resubmitPlanToDtoeMutationOptions(config) as UseMutationOptions<ResubmitPlanToDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanToDtoePathParams["humanId"]}, TContext>
          

          return useMutation<ResubmitPlanToDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanToDtoePathParams["humanId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ResubmitPlanToDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanToDtoePathParams["humanId"]}, TContext>
      
}