/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ResubmitPlanMutationRequest, ResubmitPlanMutationResponse, ResubmitPlanPathParams } from "../../types/plansController/ResubmitPlan";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { resubmitPlan } from "../../clients/plansController/resubmitPlan";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const resubmitPlanMutationKey = () => [{ url: '/plans/:humanId/resubmit' }] as const

export type ResubmitPlanMutationKey = ReturnType<typeof resubmitPlanMutationKey>

export function resubmitPlanMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ResubmitPlanMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = resubmitPlanMutationKey()
        return mutationOptions<ResubmitPlanMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanPathParams["humanId"], data: ResubmitPlanMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, data }) => {
            return resubmitPlan({ humanId, data }, config)
          },
        })

}

/**
 * @description Повторное направление только тем ЦФО, которые вернули замечания.
 * @summary Повторно направить ЦФО после исправления замечаний
 * {@link /plans/:humanId/resubmit}
 */
export function useResubmitPlan<TContext>(options: 
{
  mutation?: UseMutationOptions<ResubmitPlanMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanPathParams["humanId"], data: ResubmitPlanMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ResubmitPlanMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? resubmitPlanMutationKey()

          const baseOptions = resubmitPlanMutationOptions(config) as UseMutationOptions<ResubmitPlanMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanPathParams["humanId"], data: ResubmitPlanMutationRequest}, TContext>
          

          return useMutation<ResubmitPlanMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanPathParams["humanId"], data: ResubmitPlanMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ResubmitPlanMutationResponse, ResponseErrorConfig<Error>, {humanId: ResubmitPlanPathParams["humanId"], data: ResubmitPlanMutationRequest}, TContext>
      
}