/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { SendPlanMutationRequest, SendPlanMutationResponse, SendPlanPathParams, SendPlan400 } from "../../types/plansController/SendPlan";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { sendPlan } from "../../clients/plansController/sendPlan";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const sendPlanMutationKey = () => [{ url: '/plans/:humanId/send' }] as const

export type SendPlanMutationKey = ReturnType<typeof sendPlanMutationKey>

export function sendPlanMutationOptions<TContext = unknown>(config: Partial<RequestConfig<SendPlanMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = sendPlanMutationKey()
        return mutationOptions<SendPlanMutationResponse, ResponseErrorConfig<SendPlan400>, {humanId: SendPlanPathParams["humanId"], data: SendPlanMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, data }) => {
            return sendPlan({ humanId, data }, config)
          },
        })

}

/**
 * @description Филиал направляет укомплектованный пакет выбранным ЦФО.
 * @summary Направить план на проверку выбранным ЦФО
 * {@link /plans/:humanId/send}
 */
export function useSendPlan<TContext>(options: 
{
  mutation?: UseMutationOptions<SendPlanMutationResponse, ResponseErrorConfig<SendPlan400>, {humanId: SendPlanPathParams["humanId"], data: SendPlanMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<SendPlanMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? sendPlanMutationKey()

          const baseOptions = sendPlanMutationOptions(config) as UseMutationOptions<SendPlanMutationResponse, ResponseErrorConfig<SendPlan400>, {humanId: SendPlanPathParams["humanId"], data: SendPlanMutationRequest}, TContext>
          

          return useMutation<SendPlanMutationResponse, ResponseErrorConfig<SendPlan400>, {humanId: SendPlanPathParams["humanId"], data: SendPlanMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<SendPlanMutationResponse, ResponseErrorConfig<SendPlan400>, {humanId: SendPlanPathParams["humanId"], data: SendPlanMutationRequest}, TContext>
      
}