/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreateFactPackageMutationRequest, CreateFactPackageMutationResponse, CreateFactPackage403 } from "../../types/factPackagesController/CreateFactPackage";
import { createFactPackageMutationResponseSchema, createFactPackageMutationRequestSchema } from "../../zod/factPackagesController/createFactPackageSchema";

function getCreateFactPackageUrl() {
  const res = { method: 'POST', url: `/fact-packages` as const }
  return res
}

/**
 * @description Доступно только роли FILIAL. Каждый вызов создаёт новый факт-пакет своего филиала для указанного направления в статусе DRAFT вместе со всеми формами каталога направления (без версий файлов) — по аналогии с созданием корректировки: один филиал может иметь одновременно несколько факт-пакетов одного направления (разных периодов), «Файлы» — точка входа для создания нового, существующие смотрят на «Рабочем столе».
 * @summary Создать факт-пакет по направлению
 * {@link /fact-packages}
 */
export async function createFactPackage({ data }: { data: CreateFactPackageMutationRequest }, config: Partial<RequestConfig<CreateFactPackageMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = createFactPackageMutationRequestSchema.parse(data)

  const res = await request<CreateFactPackageMutationResponse, ResponseErrorConfig<CreateFactPackage403>, CreateFactPackageMutationRequest>({ method : "POST", url : getCreateFactPackageUrl().url.toString(), data : requestData, ... requestConfig })
  return createFactPackageMutationResponseSchema.parse(res.data)
}