/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DecideFactPackageByDtoeMutationRequest, DecideFactPackageByDtoeMutationResponse, DecideFactPackageByDtoePathParams, DecideFactPackageByDtoe400, DecideFactPackageByDtoe403 } from "../../types/factPackagesController/DecideFactPackageByDtoe";
import { decideFactPackageByDtoeMutationResponseSchema, decideFactPackageByDtoeMutationRequestSchema } from "../../zod/factPackagesController/decideFactPackageByDtoeSchema";

function getDecideFactPackageByDtoeUrl({ humanId }: { humanId: DecideFactPackageByDtoePathParams["humanId"] }) {
  const res = { method: 'POST', url: `/fact-packages/${humanId}/final-decision` as const }
  return res
}

/**
 * @description Роль DTOE. Факт-пакет должен быть в статусе UNDER_DTOE_REVIEW.
 * decision=APPROVE переводит факт-пакет в финальный неизменяемый статус
 * APPROVED. decision=RETURN требует хотя бы одного открытого замечания от
 * ДТОиР и переводит факт-пакет в RETURNED_BY_DTOE.
 * @summary Финальное решение ДТОиР по факт-пакету
 * {@link /fact-packages/:humanId/final-decision}
 */
export async function decideFactPackageByDtoe({ humanId, data }: { humanId: DecideFactPackageByDtoePathParams["humanId"]; data: DecideFactPackageByDtoeMutationRequest }, config: Partial<RequestConfig<DecideFactPackageByDtoeMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = decideFactPackageByDtoeMutationRequestSchema.parse(data)

  const res = await request<DecideFactPackageByDtoeMutationResponse, ResponseErrorConfig<DecideFactPackageByDtoe400 | DecideFactPackageByDtoe403>, DecideFactPackageByDtoeMutationRequest>({ method : "POST", url : getDecideFactPackageByDtoeUrl({ humanId }).url.toString(), data : requestData, ... requestConfig })
  return decideFactPackageByDtoeMutationResponseSchema.parse(res.data)
}