/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeleteFactPackageRemarkMutationResponse, DeleteFactPackageRemarkPathParams, DeleteFactPackageRemark400, DeleteFactPackageRemark403 } from "../../types/factPackagesController/DeleteFactPackageRemark";
import { deleteFactPackageRemarkMutationResponseSchema } from "../../zod/factPackagesController/deleteFactPackageRemarkSchema";

function getDeleteFactPackageRemarkUrl({ humanId, remarkId }: { humanId: DeleteFactPackageRemarkPathParams["humanId"]; remarkId: DeleteFactPackageRemarkPathParams["remarkId"] }) {
  const res = { method: 'DELETE', url: `/fact-packages/${humanId}/remarks/${remarkId}` as const }
  return res
}

/**
 * @description Только автор замечания и только пока оно в статусе OPEN.
 * @summary Удалить замечание (только автор, только пока OPEN)
 * {@link /fact-packages/:humanId/remarks/:remarkId}
 */
export async function deleteFactPackageRemark({ humanId, remarkId }: { humanId: DeleteFactPackageRemarkPathParams["humanId"]; remarkId: DeleteFactPackageRemarkPathParams["remarkId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteFactPackageRemarkMutationResponse, ResponseErrorConfig<DeleteFactPackageRemark400 | DeleteFactPackageRemark403>, unknown>({ method : "DELETE", url : getDeleteFactPackageRemarkUrl({ humanId, remarkId }).url.toString(), ... requestConfig })
  return deleteFactPackageRemarkMutationResponseSchema.parse(res.data)
}