/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { FixFactPackageRemarkMutationResponse, FixFactPackageRemarkPathParams, FixFactPackageRemark403 } from "../../types/factPackagesController/FixFactPackageRemark";
import { fixFactPackageRemarkMutationResponseSchema } from "../../zod/factPackagesController/fixFactPackageRemarkSchema";

function getFixFactPackageRemarkUrl({ humanId, remarkId }: { humanId: FixFactPackageRemarkPathParams["humanId"]; remarkId: FixFactPackageRemarkPathParams["remarkId"] }) {
  const res = { method: 'POST', url: `/fact-packages/${humanId}/remarks/${remarkId}/fix` as const }
  return res
}

/**
 * @description Роль FILIAL, только владелец факт-пакета.
 * @summary Отметить замечание исправленным
 * {@link /fact-packages/:humanId/remarks/:remarkId/fix}
 */
export async function fixFactPackageRemark({ humanId, remarkId }: { humanId: FixFactPackageRemarkPathParams["humanId"]; remarkId: FixFactPackageRemarkPathParams["remarkId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<FixFactPackageRemarkMutationResponse, ResponseErrorConfig<FixFactPackageRemark403>, unknown>({ method : "POST", url : getFixFactPackageRemarkUrl({ humanId, remarkId }).url.toString(), ... requestConfig })
  return fixFactPackageRemarkMutationResponseSchema.parse(res.data)
}