/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFactPackagesQueryResponse, GetFactPackagesQueryParams } from "../../types/factPackagesController/GetFactPackages";
import { getFactPackagesQueryResponseSchema } from "../../zod/factPackagesController/getFactPackagesSchema";

function getGetFactPackagesUrl() {
  const res = { method: 'GET', url: `/fact-packages` as const }
  return res
}

/**
 * @description Список автоматически ограничен ролью: FILIAL видит свои, CFO — направленные его ЦФО, DTOE/ADMIN — все (аудит).
 * @summary Список факт-пакетов (в рамках видимости роли)
 * {@link /fact-packages}
 */
export async function getFactPackages({ params }: { params?: GetFactPackagesQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetFactPackagesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetFactPackagesUrl().url.toString(), params, ... requestConfig })
  return getFactPackagesQueryResponseSchema.parse(res.data)
}