/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFactPackageStatsDtoeQueryResponse, GetFactPackageStatsDtoe403 } from "../../types/factPackagesController/GetFactPackageStatsDtoe";
import { getFactPackageStatsDtoeQueryResponseSchema } from "../../zod/factPackagesController/getFactPackageStatsDtoeSchema";

function getGetFactPackageStatsDtoeUrl() {
  const res = { method: 'GET', url: `/fact-packages/stats/dtoe` as const }
  return res
}

/**
 * @description Доступно только пользователю роли DTOE.
 * @summary Статистика по факт-пакетам для «Рабочего стола» ДТОиР
 * {@link /fact-packages/stats/dtoe}
 */
export async function getFactPackageStatsDtoe(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetFactPackageStatsDtoeQueryResponse, ResponseErrorConfig<GetFactPackageStatsDtoe403>, unknown>({ method : "GET", url : getGetFactPackageStatsDtoeUrl().url.toString(), ... requestConfig })
  return getFactPackageStatsDtoeQueryResponseSchema.parse(res.data)
}