/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetOrCreateFactPackageByDirectionQueryResponse, GetOrCreateFactPackageByDirectionPathParams, GetOrCreateFactPackageByDirection403 } from "../../types/factPackagesController/GetOrCreateFactPackageByDirection";
import { getOrCreateFactPackageByDirectionQueryResponseSchema } from "../../zod/factPackagesController/getOrCreateFactPackageByDirectionSchema";

function getGetOrCreateFactPackageByDirectionUrl({ direction }: { direction: GetOrCreateFactPackageByDirectionPathParams["direction"] }) {
  const res = { method: 'GET', url: `/fact-packages/by-direction/${direction}` as const }
  return res
}

/**
 * @description Доступно только роли FILIAL. Один факт-пакет на пару «Филиал × Направление»
 * без периода: если пакета для (свой филиал, направление) ещё нет, он
 * создаётся атомарно в статусе DRAFT вместе со всеми формами каталога
 * направления (без версий файлов), и возвращается. Повторные вызовы для той
 * же пары идемпотентны и возвращают тот же факт-пакет.
 * @summary Получить (или создать) факт-пакет своего филиала по направлению
 * {@link /fact-packages/by-direction/:direction}
 */
export async function getOrCreateFactPackageByDirection({ direction }: { direction: GetOrCreateFactPackageByDirectionPathParams["direction"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetOrCreateFactPackageByDirectionQueryResponse, ResponseErrorConfig<GetOrCreateFactPackageByDirection403>, unknown>({ method : "GET", url : getGetOrCreateFactPackageByDirectionUrl({ direction }).url.toString(), ... requestConfig })
  return getOrCreateFactPackageByDirectionQueryResponseSchema.parse(res.data)
}