/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { LeaveFactPackageRemarkMutationRequest, LeaveFactPackageRemarkMutationResponse, LeaveFactPackageRemarkPathParams, LeaveFactPackageRemark400, LeaveFactPackageRemark403 } from "../../types/factPackagesController/LeaveFactPackageRemark";
import { leaveFactPackageRemarkMutationResponseSchema, leaveFactPackageRemarkMutationRequestSchema } from "../../zod/factPackagesController/leaveFactPackageRemarkSchema";

function getLeaveFactPackageRemarkUrl({ humanId }: { humanId: LeaveFactPackageRemarkPathParams["humanId"] }) {
  const res = { method: 'POST', url: `/fact-packages/${humanId}/remarks` as const }
  return res
}

/**
 * @description Роли CFO и DTOE. Доступно только пока факт-пакет находится на проверке у
 * автора замечания (для ЦФО — его статус проверки PENDING; для ДТОиР —
 * статус факт-пакета UNDER_DTOE_REVIEW). Атомарно переводит факт-пакет в
 * RETURNED_FOR_REVISION и статус проверки автора — в RETURNED.
 * @summary Оставить замечание к форме факт-пакета
 * {@link /fact-packages/:humanId/remarks}
 */
export async function leaveFactPackageRemark({ humanId, data }: { humanId: LeaveFactPackageRemarkPathParams["humanId"]; data: LeaveFactPackageRemarkMutationRequest }, config: Partial<RequestConfig<LeaveFactPackageRemarkMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = leaveFactPackageRemarkMutationRequestSchema.parse(data)

  const res = await request<LeaveFactPackageRemarkMutationResponse, ResponseErrorConfig<LeaveFactPackageRemark400 | LeaveFactPackageRemark403>, LeaveFactPackageRemarkMutationRequest>({ method : "POST", url : getLeaveFactPackageRemarkUrl({ humanId }).url.toString(), data : requestData, ... requestConfig })
  return leaveFactPackageRemarkMutationResponseSchema.parse(res.data)
}