/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { SendFactPackageToDtoeMutationResponse, SendFactPackageToDtoePathParams, SendFactPackageToDtoe400, SendFactPackageToDtoe403 } from "../../types/factPackagesController/SendFactPackageToDtoe";
import { sendFactPackageToDtoeMutationResponseSchema } from "../../zod/factPackagesController/sendFactPackageToDtoeSchema";

function getSendFactPackageToDtoeUrl({ humanId }: { humanId: SendFactPackageToDtoePathParams["humanId"] }) {
  const res = { method: 'POST', url: `/fact-packages/${humanId}/send-to-dtoe` as const }
  return res
}

/**
 * @description Доступно любому согласовавшему ЦФО этого факт-пакета, когда все обязательные ЦФО согласовали (canSendToDtoe).
 * @summary Отправить факт-пакет в ДТОиР
 * {@link /fact-packages/:humanId/send-to-dtoe}
 */
export async function sendFactPackageToDtoe({ humanId }: { humanId: SendFactPackageToDtoePathParams["humanId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<SendFactPackageToDtoeMutationResponse, ResponseErrorConfig<SendFactPackageToDtoe400 | SendFactPackageToDtoe403>, unknown>({ method : "POST", url : getSendFactPackageToDtoeUrl({ humanId }).url.toString(), ... requestConfig })
  return sendFactPackageToDtoeMutationResponseSchema.parse(res.data)
}