/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { SubmitFactPackageMutationRequest, SubmitFactPackageMutationResponse, SubmitFactPackagePathParams, SubmitFactPackage400 } from "../../types/factPackagesController/SubmitFactPackage";
import { submitFactPackageMutationResponseSchema, submitFactPackageMutationRequestSchema } from "../../zod/factPackagesController/submitFactPackageSchema";

function getSubmitFactPackageUrl({ humanId }: { humanId: SubmitFactPackagePathParams["humanId"] }) {
  const res = { method: 'POST', url: `/fact-packages/${humanId}/submit` as const }
  return res
}

/**
 * @description Филиал направляет укомплектованный пакет выбранным ЦФО. Обслуживает и
 * первичное направление (DRAFT), и повторное направление после доработки
 * (RETURNED_FOR_REVISION) — в этом случае доступно только когда все
 * замечания от вернувших ЦФО отмечены исправленными; статус
 * согласовавших ранее ЦФО не сбрасывается.
 * @summary Направить факт-пакет на проверку выбранным ЦФО
 * {@link /fact-packages/:humanId/submit}
 */
export async function submitFactPackage({ humanId, data }: { humanId: SubmitFactPackagePathParams["humanId"]; data: SubmitFactPackageMutationRequest }, config: Partial<RequestConfig<SubmitFactPackageMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = submitFactPackageMutationRequestSchema.parse(data)

  const res = await request<SubmitFactPackageMutationResponse, ResponseErrorConfig<SubmitFactPackage400>, SubmitFactPackageMutationRequest>({ method : "POST", url : getSubmitFactPackageUrl({ humanId }).url.toString(), data : requestData, ... requestConfig })
  return submitFactPackageMutationResponseSchema.parse(res.data)
}