/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ApproveCorrectionByDtoeMutationResponse, ApproveCorrectionByDtoePathParams } from "../../types/correctionsController/ApproveCorrectionByDtoe";
import { approveCorrectionByDtoeMutationResponseSchema } from "../../zod/correctionsController/approveCorrectionByDtoeSchema";

function getApproveCorrectionByDtoeUrl({ humanId }: { humanId: ApproveCorrectionByDtoePathParams["humanId"] }) {
  const res = { method: 'POST', url: `/corrections/${humanId}/dtoe-approve` as const }
  return res
}

/**
 * @description Роль DTOE. Финальное согласование.
 * @summary Финально согласовать корректировку (ДТОиР)
 * {@link /corrections/:humanId/dtoe-approve}
 */
export async function approveCorrectionByDtoe({ humanId }: { humanId: ApproveCorrectionByDtoePathParams["humanId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ApproveCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getApproveCorrectionByDtoeUrl({ humanId }).url.toString(), ... requestConfig })
  return approveCorrectionByDtoeMutationResponseSchema.parse(res.data)
}