/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CancelCfoDecisionMutationResponse, CancelCfoDecisionPathParams } from "../../types/correctionsController/CancelCfoDecision";
import { cancelCfoDecisionMutationResponseSchema } from "../../zod/correctionsController/cancelCfoDecisionSchema";

function getCancelCfoDecisionUrl({ humanId }: { humanId: CancelCfoDecisionPathParams["humanId"] }) {
  const res = { method: 'POST', url: `/corrections/${humanId}/cfo-cancel` as const }
  return res
}

/**
 * @description Роль CFO. Возвращает статус этого ЦФО (APPROVED или RETURNED) обратно в
PENDING — страховка от случайного клика по «Согласовать»/«Вернуть на
доработку». Оставленные замечания не удаляются и не меняются, это часть
истории — откатывается только статус ЦФО. Недоступно, если корректировка
уже передана в ДТОиР (`UNDER_DTOE_REVIEW`/`RETURNED_BY_DTOE`/`APPROVED_BY_DTOE`)
— тогда `400`.

 * @summary Отменить собственное решение ЦФО
 * {@link /corrections/:humanId/cfo-cancel}
 */
export async function cancelCfoDecision({ humanId }: { humanId: CancelCfoDecisionPathParams["humanId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CancelCfoDecisionMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getCancelCfoDecisionUrl({ humanId }).url.toString(), ... requestConfig })
  return cancelCfoDecisionMutationResponseSchema.parse(res.data)
}