/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeleteCorrectionMutationResponse, DeleteCorrectionPathParams } from "../../types/correctionsController/DeleteCorrection";
import { deleteCorrectionMutationResponseSchema } from "../../zod/correctionsController/deleteCorrectionSchema";

function getDeleteCorrectionUrl({ humanId }: { humanId: DeleteCorrectionPathParams["humanId"] }) {
  const res = { method: 'DELETE', url: `/corrections/${humanId}` as const }
  return res
}

/**
 * @description Роль FILIAL, только автор/владелец. Доступно только для корректировки в
статусе `DRAFT` — направленную (любой другой статус) удалить нельзя,
`400`. Удаляет корректировку целиком: слоты, версии файлов, замечания,
статусы ЦФО, историю и уведомления по каскаду. `DRAFT`-корректировка не
может иметь ни одного статуса ЦФО (они создаются только `POST
.../send`), поэтому удаление черновика не затрагивает решений
проверяющих и не требует их уведомления.

 * @summary Удалить корректировку
 * {@link /corrections/:humanId}
 */
export async function deleteCorrection({ humanId }: { humanId: DeleteCorrectionPathParams["humanId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteCorrectionMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteCorrectionUrl({ humanId }).url.toString(), ... requestConfig })
  return deleteCorrectionMutationResponseSchema.parse(res.data)
}