/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeleteRemarkMutationResponse, DeleteRemarkPathParams } from "../../types/correctionsController/DeleteRemark";
import { deleteRemarkMutationResponseSchema } from "../../zod/correctionsController/deleteRemarkSchema";

function getDeleteRemarkUrl({ humanId, remarkId }: { humanId: DeleteRemarkPathParams["humanId"]; remarkId: DeleteRemarkPathParams["remarkId"] }) {
  const res = { method: 'DELETE', url: `/corrections/${humanId}/remarks/${remarkId}` as const }
  return res
}

/**
 * @description Только автор замечания и только пока оно в статусе OPEN.
 * @summary Удалить замечание (только автор, только пока OPEN)
 * {@link /corrections/:humanId/remarks/:remarkId}
 */
export async function deleteRemark({ humanId, remarkId }: { humanId: DeleteRemarkPathParams["humanId"]; remarkId: DeleteRemarkPathParams["remarkId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteRemarkMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteRemarkUrl({ humanId, remarkId }).url.toString(), ... requestConfig })
  return deleteRemarkMutationResponseSchema.parse(res.data)
}