/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionStatsQueryResponse } from "../../types/correctionsController/GetCorrectionStats";
import { getCorrectionStatsQueryResponseSchema } from "../../zod/correctionsController/getCorrectionStatsSchema";

function getGetCorrectionStatsUrl() {
  const res = { method: 'GET', url: `/corrections/stats` as const }
  return res
}

/**
 * @summary Статистика по корректировкам для карточек дашборда
 * {@link /corrections/stats}
 */
export async function getCorrectionStats(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetCorrectionStatsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetCorrectionStatsUrl().url.toString(), ... requestConfig })
  return getCorrectionStatsQueryResponseSchema.parse(res.data)
}