/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionStatsCfoQueryResponse, GetCorrectionStatsCfo403 } from "../../types/correctionsController/GetCorrectionStatsCfo";
import { getCorrectionStatsCfoQueryResponseSchema } from "../../zod/correctionsController/getCorrectionStatsCfoSchema";

function getGetCorrectionStatsCfoUrl() {
  const res = { method: 'GET', url: `/corrections/stats/cfo` as const }
  return res
}

/**
 * @description Доступно только пользователю роли CFO.
 * @summary Статистика по корректировкам для раздела ЦФО
 * {@link /corrections/stats/cfo}
 */
export async function getCorrectionStatsCfo(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetCorrectionStatsCfoQueryResponse, ResponseErrorConfig<GetCorrectionStatsCfo403>, unknown>({ method : "GET", url : getGetCorrectionStatsCfoUrl().url.toString(), ... requestConfig })
  return getCorrectionStatsCfoQueryResponseSchema.parse(res.data)
}