/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { LeaveRemarkMutationRequest, LeaveRemarkMutationResponse, LeaveRemarkPathParams } from "../../types/correctionsController/LeaveRemark";
import { leaveRemarkMutationResponseSchema, leaveRemarkMutationRequestSchema } from "../../zod/correctionsController/leaveRemarkSchema";

function getLeaveRemarkUrl({ humanId }: { humanId: LeaveRemarkPathParams["humanId"] }) {
  const res = { method: 'POST', url: `/corrections/${humanId}/remarks` as const }
  return res
}

/**
 * @description Роли CFO и DTOE. Создаёт замечание, привязанное к элементу пакета
 * (`relatedSlotId`), не меняя статус корректировки и статус проверяющего —
 * проверяющий может оставить несколько замечаний к разным элементам за один
 * заход. Возврат пакета на доработку — отдельное действие
 * (`POST /corrections/{humanId}/cfo-return` или `.../dtoe-return`),
 * требующее хотя бы одного открытого замечания.
 * @summary Оставить замечание к элементу пакета
 * {@link /corrections/:humanId/remarks}
 */
export async function leaveRemark({ humanId, data }: { humanId: LeaveRemarkPathParams["humanId"]; data: LeaveRemarkMutationRequest }, config: Partial<RequestConfig<LeaveRemarkMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = leaveRemarkMutationRequestSchema.parse(data)

  const res = await request<LeaveRemarkMutationResponse, ResponseErrorConfig<Error>, LeaveRemarkMutationRequest>({ method : "POST", url : getLeaveRemarkUrl({ humanId }).url.toString(), data : requestData, ... requestConfig })
  return leaveRemarkMutationResponseSchema.parse(res.data)
}