/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ResubmitCorrectionMutationRequest, ResubmitCorrectionMutationResponse, ResubmitCorrectionPathParams } from "../../types/correctionsController/ResubmitCorrection";
import { resubmitCorrectionMutationResponseSchema, resubmitCorrectionMutationRequestSchema } from "../../zod/correctionsController/resubmitCorrectionSchema";

function getResubmitCorrectionUrl({ humanId }: { humanId: ResubmitCorrectionPathParams["humanId"] }) {
  const res = { method: 'POST', url: `/corrections/${humanId}/resubmit` as const }
  return res
}

/**
 * @description Повторное направление только тем ЦФО, которые вернули замечания.
 * @summary Повторно направить ЦФО после исправления замечаний
 * {@link /corrections/:humanId/resubmit}
 */
export async function resubmitCorrection({ humanId, data }: { humanId: ResubmitCorrectionPathParams["humanId"]; data: ResubmitCorrectionMutationRequest }, config: Partial<RequestConfig<ResubmitCorrectionMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = resubmitCorrectionMutationRequestSchema.parse(data)

  const res = await request<ResubmitCorrectionMutationResponse, ResponseErrorConfig<Error>, ResubmitCorrectionMutationRequest>({ method : "POST", url : getResubmitCorrectionUrl({ humanId }).url.toString(), data : requestData, ... requestConfig })
  return resubmitCorrectionMutationResponseSchema.parse(res.data)
}