/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ReturnCorrectionByCfoMutationRequest, ReturnCorrectionByCfoMutationResponse, ReturnCorrectionByCfoPathParams } from "../../types/correctionsController/ReturnCorrectionByCfo";
import { returnCorrectionByCfoMutationResponseSchema, returnCorrectionByCfoMutationRequestSchema } from "../../zod/correctionsController/returnCorrectionByCfoSchema";

function getReturnCorrectionByCfoUrl({ humanId }: { humanId: ReturnCorrectionByCfoPathParams["humanId"] }) {
  const res = { method: 'POST', url: `/corrections/${humanId}/cfo-return` as const }
  return res
}

/**
 * @description Роль CFO. Создаёт замечание и возвращает пакет на доработку.
 * @summary Вернуть на доработку от лица ЦФО (с замечанием)
 * {@link /corrections/:humanId/cfo-return}
 */
export async function returnCorrectionByCfo({ humanId, data }: { humanId: ReturnCorrectionByCfoPathParams["humanId"]; data: ReturnCorrectionByCfoMutationRequest }, config: Partial<RequestConfig<ReturnCorrectionByCfoMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = returnCorrectionByCfoMutationRequestSchema.parse(data)

  const res = await request<ReturnCorrectionByCfoMutationResponse, ResponseErrorConfig<Error>, ReturnCorrectionByCfoMutationRequest>({ method : "POST", url : getReturnCorrectionByCfoUrl({ humanId }).url.toString(), data : requestData, ... requestConfig })
  return returnCorrectionByCfoMutationResponseSchema.parse(res.data)
}