/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { SendCorrectionMutationRequest, SendCorrectionMutationResponse, SendCorrectionPathParams, SendCorrection400 } from "../../types/correctionsController/SendCorrection";
import { sendCorrectionMutationResponseSchema, sendCorrectionMutationRequestSchema } from "../../zod/correctionsController/sendCorrectionSchema";

function getSendCorrectionUrl({ humanId }: { humanId: SendCorrectionPathParams["humanId"] }) {
  const res = { method: 'POST', url: `/corrections/${humanId}/send` as const }
  return res
}

/**
 * @description Филиал направляет укомплектованный пакет выбранным ЦФО.
 * @summary Направить корректировку на проверку выбранным ЦФО
 * {@link /corrections/:humanId/send}
 */
export async function sendCorrection({ humanId, data }: { humanId: SendCorrectionPathParams["humanId"]; data: SendCorrectionMutationRequest }, config: Partial<RequestConfig<SendCorrectionMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = sendCorrectionMutationRequestSchema.parse(data)

  const res = await request<SendCorrectionMutationResponse, ResponseErrorConfig<SendCorrection400>, SendCorrectionMutationRequest>({ method : "POST", url : getSendCorrectionUrl({ humanId }).url.toString(), data : requestData, ... requestConfig })
  return sendCorrectionMutationResponseSchema.parse(res.data)
}