/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CancelPlanCfoDecisionMutationResponse, CancelPlanCfoDecisionPathParams, CancelPlanCfoDecision400 } from "../../types/plansController/CancelPlanCfoDecision";
import { cancelPlanCfoDecisionMutationResponseSchema } from "../../zod/plansController/cancelPlanCfoDecisionSchema";

function getCancelPlanCfoDecisionUrl({ humanId }: { humanId: CancelPlanCfoDecisionPathParams["humanId"] }) {
  const res = { method: 'POST', url: `/plans/${humanId}/cfo-cancel` as const }
  return res
}

/**
 * @description Роль CFO. Возвращает статус этого ЦФО (APPROVED или RETURNED) обратно в
 * PENDING — страховка от случайного клика по «Согласовать»/«Вернуть на
 * доработку». Оставленные замечания не удаляются и не меняются, это часть
 * истории — откатывается только статус ЦФО. Недоступно, если план уже
 * передан в ДТОиР (`UNDER_DTOE_REVIEW`/`RETURNED_BY_DTOE`/`APPROVED_BY_DTOE`)
 * — тогда `400`.
 * @summary Отменить собственное решение ЦФО по плану
 * {@link /plans/:humanId/cfo-cancel}
 */
export async function cancelPlanCfoDecision({ humanId }: { humanId: CancelPlanCfoDecisionPathParams["humanId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CancelPlanCfoDecisionMutationResponse, ResponseErrorConfig<CancelPlanCfoDecision400>, unknown>({ method : "POST", url : getCancelPlanCfoDecisionUrl({ humanId }).url.toString(), ... requestConfig })
  return cancelPlanCfoDecisionMutationResponseSchema.parse(res.data)
}