/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreatePlanMutationRequest, CreatePlanMutationResponse } from "../../types/plansController/CreatePlan";
import { createPlanMutationResponseSchema, createPlanMutationRequestSchema } from "../../zod/plansController/createPlanSchema";

function getCreatePlanUrl() {
  const res = { method: 'POST', url: `/plans` as const }
  return res
}

/**
 * @description Доступно только роли FILIAL. Создаёт план и ячейки пакета по типу.
 * @summary Создать план
 * {@link /plans}
 */
export async function createPlan({ data }: { data: CreatePlanMutationRequest }, config: Partial<RequestConfig<CreatePlanMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = createPlanMutationRequestSchema.parse(data)

  const res = await request<CreatePlanMutationResponse, ResponseErrorConfig<Error>, CreatePlanMutationRequest>({ method : "POST", url : getCreatePlanUrl().url.toString(), data : requestData, ... requestConfig })
  return createPlanMutationResponseSchema.parse(res.data)
}