/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeletePlanRemarkMutationResponse, DeletePlanRemarkPathParams } from "../../types/plansController/DeletePlanRemark";
import { deletePlanRemarkMutationResponseSchema } from "../../zod/plansController/deletePlanRemarkSchema";

function getDeletePlanRemarkUrl({ humanId, remarkId }: { humanId: DeletePlanRemarkPathParams["humanId"]; remarkId: DeletePlanRemarkPathParams["remarkId"] }) {
  const res = { method: 'DELETE', url: `/plans/${humanId}/remarks/${remarkId}` as const }
  return res
}

/**
 * @description Только автор замечания и только пока оно в статусе OPEN.
 * @summary Удалить замечание плана (только автор, только пока OPEN)
 * {@link /plans/:humanId/remarks/:remarkId}
 */
export async function deletePlanRemark({ humanId, remarkId }: { humanId: DeletePlanRemarkPathParams["humanId"]; remarkId: DeletePlanRemarkPathParams["remarkId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeletePlanRemarkMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeletePlanRemarkUrl({ humanId, remarkId }).url.toString(), ... requestConfig })
  return deletePlanRemarkMutationResponseSchema.parse(res.data)
}