/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeletePlanMutationResponse, DeletePlanPathParams, DeletePlan400, DeletePlan403, DeletePlan404 } from "../../types/plansController/DeletePlan";
import { deletePlanMutationResponseSchema } from "../../zod/plansController/deletePlanSchema";

function getDeletePlanUrl({ humanId }: { humanId: DeletePlanPathParams["humanId"] }) {
  const res = { method: 'DELETE', url: `/plans/${humanId}` as const }
  return res
}

/**
 * @description Роль FILIAL, только автор/владелец. Доступно только для плана в статусе
 * `DRAFT` — направленный (любой другой статус) удалить нельзя, `400`.
 * Удаляет план целиком: слоты, версии файлов, замечания, статусы ЦФО,
 * историю и уведомления по каскаду. `DRAFT`-план не может иметь ни одного
 * статуса ЦФО (они создаются только `POST .../send`), поэтому удаление
 * черновика не затрагивает решений проверяющих и не требует их уведомления.
 * @summary Удалить план
 * {@link /plans/:humanId}
 */
export async function deletePlan({ humanId }: { humanId: DeletePlanPathParams["humanId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeletePlanMutationResponse, ResponseErrorConfig<DeletePlan400 | DeletePlan403 | DeletePlan404>, unknown>({ method : "DELETE", url : getDeletePlanUrl({ humanId }).url.toString(), ... requestConfig })
  return deletePlanMutationResponseSchema.parse(res.data)
}