/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlanStatsFilialQueryResponse, GetPlanStatsFilial403 } from "../../types/plansController/GetPlanStatsFilial";
import { getPlanStatsFilialQueryResponseSchema } from "../../zod/plansController/getPlanStatsFilialSchema";

function getGetPlanStatsFilialUrl() {
  const res = { method: 'GET', url: `/plans/stats/filial` as const }
  return res
}

/**
 * @description Доступно только пользователю роли FILIAL.
 * @summary Статистика по планам для раздела филиала
 * {@link /plans/stats/filial}
 */
export async function getPlanStatsFilial(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetPlanStatsFilialQueryResponse, ResponseErrorConfig<GetPlanStatsFilial403>, unknown>({ method : "GET", url : getGetPlanStatsFilialUrl().url.toString(), ... requestConfig })
  return getPlanStatsFilialQueryResponseSchema.parse(res.data)
}