/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlanStatsDtoeQueryResponse, GetPlanStatsDtoe403 } from "../../types/plansController/GetPlanStatsDtoe";
import { getPlanStatsDtoeQueryResponseSchema } from "../../zod/plansController/getPlanStatsDtoeSchema";

function getGetPlanStatsDtoeUrl() {
  const res = { method: 'GET', url: `/plans/stats/dtoe` as const }
  return res
}

/**
 * @description Доступно только пользователю роли DTOE.
 * @summary Статистика по планам для раздела ДТОиР
 * {@link /plans/stats/dtoe}
 */
export async function getPlanStatsDtoe(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetPlanStatsDtoeQueryResponse, ResponseErrorConfig<GetPlanStatsDtoe403>, unknown>({ method : "GET", url : getGetPlanStatsDtoeUrl().url.toString(), ... requestConfig })
  return getPlanStatsDtoeQueryResponseSchema.parse(res.data)
}