/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetPlanStatsQueryResponse } from "../../types/plansController/GetPlanStats";
import { getPlanStatsQueryResponseSchema } from "../../zod/plansController/getPlanStatsSchema";

function getGetPlanStatsUrl() {
  const res = { method: 'GET', url: `/plans/stats` as const }
  return res
}

/**
 * @summary Статистика по планам для карточек дашборда
 * {@link /plans/stats}
 */
export async function getPlanStats(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetPlanStatsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetPlanStatsUrl().url.toString(), ... requestConfig })
  return getPlanStatsQueryResponseSchema.parse(res.data)
}