/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { MarkPlanRemarkFixedMutationResponse, MarkPlanRemarkFixedPathParams } from "../../types/plansController/MarkPlanRemarkFixed";
import { markPlanRemarkFixedMutationResponseSchema } from "../../zod/plansController/markPlanRemarkFixedSchema";

function getMarkPlanRemarkFixedUrl({ humanId, remarkId }: { humanId: MarkPlanRemarkFixedPathParams["humanId"]; remarkId: MarkPlanRemarkFixedPathParams["remarkId"] }) {
  const res = { method: 'POST', url: `/plans/${humanId}/remarks/${remarkId}/fix` as const }
  return res
}

/**
 * @description Роль FILIAL (владелец). Отмечает замечание исправленным, не закрывает его.
 * @summary Отметить замечание плана исправленным
 * {@link /plans/:humanId/remarks/:remarkId/fix}
 */
export async function markPlanRemarkFixed({ humanId, remarkId }: { humanId: MarkPlanRemarkFixedPathParams["humanId"]; remarkId: MarkPlanRemarkFixedPathParams["remarkId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarkPlanRemarkFixedMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getMarkPlanRemarkFixedUrl({ humanId, remarkId }).url.toString(), ... requestConfig })
  return markPlanRemarkFixedMutationResponseSchema.parse(res.data)
}