/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ReopenPlanRemarkMutationRequest, ReopenPlanRemarkMutationResponse, ReopenPlanRemarkPathParams } from "../../types/plansController/ReopenPlanRemark";
import { reopenPlanRemarkMutationResponseSchema, reopenPlanRemarkMutationRequestSchema } from "../../zod/plansController/reopenPlanRemarkSchema";

function getReopenPlanRemarkUrl({ humanId, remarkId }: { humanId: ReopenPlanRemarkPathParams["humanId"]; remarkId: ReopenPlanRemarkPathParams["remarkId"] }) {
  const res = { method: 'POST', url: `/plans/${humanId}/remarks/${remarkId}/reopen` as const }
  return res
}

/**
 * @description Роль CFO (владелец замечания). Исправление не принято — переоткрыть.
 * @summary Переоткрыть замечание плана (исправление не принято)
 * {@link /plans/:humanId/remarks/:remarkId/reopen}
 */
export async function reopenPlanRemark({ humanId, remarkId, data }: { humanId: ReopenPlanRemarkPathParams["humanId"]; remarkId: ReopenPlanRemarkPathParams["remarkId"]; data: ReopenPlanRemarkMutationRequest }, config: Partial<RequestConfig<ReopenPlanRemarkMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = reopenPlanRemarkMutationRequestSchema.parse(data)

  const res = await request<ReopenPlanRemarkMutationResponse, ResponseErrorConfig<Error>, ReopenPlanRemarkMutationRequest>({ method : "POST", url : getReopenPlanRemarkUrl({ humanId, remarkId }).url.toString(), data : requestData, ... requestConfig })
  return reopenPlanRemarkMutationResponseSchema.parse(res.data)
}