/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ResubmitPlanMutationRequest, ResubmitPlanMutationResponse, ResubmitPlanPathParams } from "../../types/plansController/ResubmitPlan";
import { resubmitPlanMutationResponseSchema, resubmitPlanMutationRequestSchema } from "../../zod/plansController/resubmitPlanSchema";

function getResubmitPlanUrl({ humanId }: { humanId: ResubmitPlanPathParams["humanId"] }) {
  const res = { method: 'POST', url: `/plans/${humanId}/resubmit` as const }
  return res
}

/**
 * @description Повторное направление только тем ЦФО, которые вернули замечания.
 * @summary Повторно направить ЦФО после исправления замечаний
 * {@link /plans/:humanId/resubmit}
 */
export async function resubmitPlan({ humanId, data }: { humanId: ResubmitPlanPathParams["humanId"]; data: ResubmitPlanMutationRequest }, config: Partial<RequestConfig<ResubmitPlanMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = resubmitPlanMutationRequestSchema.parse(data)

  const res = await request<ResubmitPlanMutationResponse, ResponseErrorConfig<Error>, ResubmitPlanMutationRequest>({ method : "POST", url : getResubmitPlanUrl({ humanId }).url.toString(), data : requestData, ... requestConfig })
  return resubmitPlanMutationResponseSchema.parse(res.data)
}