/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ReturnPlanByCfoMutationResponse, ReturnPlanByCfoPathParams } from "../../types/plansController/ReturnPlanByCfo";
import { returnPlanByCfoMutationResponseSchema } from "../../zod/plansController/returnPlanByCfoSchema";

function getReturnPlanByCfoUrl({ humanId }: { humanId: ReturnPlanByCfoPathParams["humanId"] }) {
  const res = { method: 'POST', url: `/plans/${humanId}/cfo-return` as const }
  return res
}

/**
 * @description Роль CFO. Переводит план в «Возвращено на доработку», а статус этого
 * ЦФО — в «Возвращено». Требует, чтобы у этого ЦФО уже было оставлено
 * хотя бы одно открытое замечание по этому плану
 * (`POST /plans/{humanId}/remarks`) — иначе `400`.
 * @summary Финализировать возврат плана на доработку от лица ЦФО
 * {@link /plans/:humanId/cfo-return}
 */
export async function returnPlanByCfo({ humanId }: { humanId: ReturnPlanByCfoPathParams["humanId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ReturnPlanByCfoMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getReturnPlanByCfoUrl({ humanId }).url.toString(), ... requestConfig })
  return returnPlanByCfoMutationResponseSchema.parse(res.data)
}