/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { UploadPlanFileVersionMutationRequest, UploadPlanFileVersionMutationResponse, UploadPlanFileVersionPathParams } from "../../types/plansController/UploadPlanFileVersion";
import { buildFormData } from "../../.kubb/config";
import { uploadPlanFileVersionMutationResponseSchema, uploadPlanFileVersionMutationRequestSchema } from "../../zod/plansController/uploadPlanFileVersionSchema";

function getUploadPlanFileVersionUrl({ humanId, slotId }: { humanId: UploadPlanFileVersionPathParams["humanId"]; slotId: UploadPlanFileVersionPathParams["slotId"] }) {
  const res = { method: 'POST', url: `/plans/${humanId}/slots/${slotId}/files` as const }
  return res
}

/**
 * @description Доступно только автору-владельцу (роль FILIAL, свой филиал).
 * @summary Загрузить версию файла в ячейку пакета плана
 * {@link /plans/:humanId/slots/:slotId/files}
 */
export async function uploadPlanFileVersion({ humanId, slotId, data }: { humanId: UploadPlanFileVersionPathParams["humanId"]; slotId: UploadPlanFileVersionPathParams["slotId"]; data: UploadPlanFileVersionMutationRequest }, config: Partial<RequestConfig<UploadPlanFileVersionMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = uploadPlanFileVersionMutationRequestSchema.parse(data)
  const formData = buildFormData(requestData)
  const res = await request<UploadPlanFileVersionMutationResponse, ResponseErrorConfig<Error>, UploadPlanFileVersionMutationRequest>({ method : "POST", url : getUploadPlanFileVersionUrl({ humanId, slotId }).url.toString(), data : formData as FormData, ... requestConfig })
  return uploadPlanFileVersionMutationResponseSchema.parse(res.data)
}