/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetNotificationsQueryResponse } from "../../types/notificationsController/GetNotifications";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getNotifications } from "../../clients/notificationsController/getNotifications";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getNotificationsQueryKey = () => [{ url: '/notifications' }] as const

export type GetNotificationsQueryKey = ReturnType<typeof getNotificationsQueryKey>

export function getNotificationsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getNotificationsQueryKey()
        return queryOptions<GetNotificationsQueryResponse, ResponseErrorConfig<Error>, GetNotificationsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getNotifications({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Список уведомлений текущего пользователя
 * {@link /notifications}
 */
export function useGetNotifications<TData = GetNotificationsQueryResponse, TQueryData = GetNotificationsQueryResponse, TQueryKey extends QueryKey = GetNotificationsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetNotificationsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getNotificationsQueryKey()
         

         const query = useQuery({
          ...getNotificationsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}