/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetNotificationsQueryResponse } from "../../types/notificationsController/GetNotifications";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getNotifications } from "../../clients/notificationsController/getNotifications";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getNotificationsSuspenseQueryKey = () => [{ url: '/notifications' }] as const

export type GetNotificationsSuspenseQueryKey = ReturnType<typeof getNotificationsSuspenseQueryKey>

export function getNotificationsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getNotificationsSuspenseQueryKey()
        return queryOptions<GetNotificationsQueryResponse, ResponseErrorConfig<Error>, GetNotificationsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getNotifications({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Список уведомлений текущего пользователя
 * {@link /notifications}
 */
export function useGetNotificationsSuspense<TData = GetNotificationsQueryResponse, TQueryKey extends QueryKey = GetNotificationsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetNotificationsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getNotificationsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getNotificationsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}