/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { MarkNotificationsReadByPlanMutationResponse, MarkNotificationsReadByPlanPathParams } from "../../types/notificationsController/MarkNotificationsReadByPlan";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { markNotificationsReadByPlan } from "../../clients/notificationsController/markNotificationsReadByPlan";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const markNotificationsReadByPlanMutationKey = () => [{ url: '/notifications/by-plan/:planId/read' }] as const

export type MarkNotificationsReadByPlanMutationKey = ReturnType<typeof markNotificationsReadByPlanMutationKey>

export function markNotificationsReadByPlanMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = markNotificationsReadByPlanMutationKey()
        return mutationOptions<MarkNotificationsReadByPlanMutationResponse, ResponseErrorConfig<Error>, {planId: MarkNotificationsReadByPlanPathParams["planId"]}, TContext>({
          mutationKey,
          mutationFn: async({ planId }) => {
            return markNotificationsReadByPlan({ planId }, config)
          },
        })

}

/**
 * @description Вызывается при открытии карточки плана — помечает прочитанными все
 * уведомления текущего пользователя, связанные с этим планом, независимо
 * от того, попал ли пользователь на карточку через клик по уведомлению или
 * напрямую. Идемпотентно — уже прочитанные записи повторно не
 * пересчитываются.
 * @summary Отметить прочитанными все уведомления пользователя по одному плану
 * {@link /notifications/by-plan/:planId/read}
 */
export function useMarkNotificationsReadByPlan<TContext>(options: 
{
  mutation?: UseMutationOptions<MarkNotificationsReadByPlanMutationResponse, ResponseErrorConfig<Error>, {planId: MarkNotificationsReadByPlanPathParams["planId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? markNotificationsReadByPlanMutationKey()

          const baseOptions = markNotificationsReadByPlanMutationOptions(config) as UseMutationOptions<MarkNotificationsReadByPlanMutationResponse, ResponseErrorConfig<Error>, {planId: MarkNotificationsReadByPlanPathParams["planId"]}, TContext>
          

          return useMutation<MarkNotificationsReadByPlanMutationResponse, ResponseErrorConfig<Error>, {planId: MarkNotificationsReadByPlanPathParams["planId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MarkNotificationsReadByPlanMutationResponse, ResponseErrorConfig<Error>, {planId: MarkNotificationsReadByPlanPathParams["planId"]}, TContext>
      
}