/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { MarkNotificationsReadByFactPackageMutationResponse, MarkNotificationsReadByFactPackagePathParams } from "../../types/notificationsController/MarkNotificationsReadByFactPackage";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { markNotificationsReadByFactPackage } from "../../clients/notificationsController/markNotificationsReadByFactPackage";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const markNotificationsReadByFactPackageMutationKey = () => [{ url: '/notifications/by-fact-package/:factPackageId/read' }] as const

export type MarkNotificationsReadByFactPackageMutationKey = ReturnType<typeof markNotificationsReadByFactPackageMutationKey>

export function markNotificationsReadByFactPackageMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = markNotificationsReadByFactPackageMutationKey()
        return mutationOptions<MarkNotificationsReadByFactPackageMutationResponse, ResponseErrorConfig<Error>, {factPackageId: MarkNotificationsReadByFactPackagePathParams["factPackageId"]}, TContext>({
          mutationKey,
          mutationFn: async({ factPackageId }) => {
            return markNotificationsReadByFactPackage({ factPackageId }, config)
          },
        })

}

/**
 * @description Симметрично markNotificationsReadByCorrection, для карточки факт-пакета
 * (openspec/changes/fact-package-review). Идемпотентно.
 * @summary Отметить прочитанными все уведомления пользователя по одному факт-пакету
 * {@link /notifications/by-fact-package/:factPackageId/read}
 */
export function useMarkNotificationsReadByFactPackage<TContext>(options: 
{
  mutation?: UseMutationOptions<MarkNotificationsReadByFactPackageMutationResponse, ResponseErrorConfig<Error>, {factPackageId: MarkNotificationsReadByFactPackagePathParams["factPackageId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? markNotificationsReadByFactPackageMutationKey()

          const baseOptions = markNotificationsReadByFactPackageMutationOptions(config) as UseMutationOptions<MarkNotificationsReadByFactPackageMutationResponse, ResponseErrorConfig<Error>, {factPackageId: MarkNotificationsReadByFactPackagePathParams["factPackageId"]}, TContext>
          

          return useMutation<MarkNotificationsReadByFactPackageMutationResponse, ResponseErrorConfig<Error>, {factPackageId: MarkNotificationsReadByFactPackagePathParams["factPackageId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MarkNotificationsReadByFactPackageMutationResponse, ResponseErrorConfig<Error>, {factPackageId: MarkNotificationsReadByFactPackagePathParams["factPackageId"]}, TContext>
      
}