/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { OpenNotificationMutationResponse, OpenNotificationPathParams } from "../../types/notificationsController/OpenNotification";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { openNotification } from "../../clients/notificationsController/openNotification";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const openNotificationMutationKey = () => [{ url: '/notifications/:id/open' }] as const

export type OpenNotificationMutationKey = ReturnType<typeof openNotificationMutationKey>

export function openNotificationMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = openNotificationMutationKey()
        return mutationOptions<OpenNotificationMutationResponse, ResponseErrorConfig<Error>, {id: OpenNotificationPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return openNotification({ id }, config)
          },
        })

}

/**
 * @description Помечает прочитанным и возвращает ссылку на корректировку.
 * @summary Открыть уведомление (пометить прочитанным)
 * {@link /notifications/:id/open}
 */
export function useOpenNotification<TContext>(options: 
{
  mutation?: UseMutationOptions<OpenNotificationMutationResponse, ResponseErrorConfig<Error>, {id: OpenNotificationPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? openNotificationMutationKey()

          const baseOptions = openNotificationMutationOptions(config) as UseMutationOptions<OpenNotificationMutationResponse, ResponseErrorConfig<Error>, {id: OpenNotificationPathParams["id"]}, TContext>
          

          return useMutation<OpenNotificationMutationResponse, ResponseErrorConfig<Error>, {id: OpenNotificationPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<OpenNotificationMutationResponse, ResponseErrorConfig<Error>, {id: OpenNotificationPathParams["id"]}, TContext>
      
}