/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { RefreshMutationResponse, Refresh401 } from "../../types/authController/Refresh";
import { refreshMutationResponseSchema } from "../../zod/authController/refreshSchema";

function getRefreshUrl() {
  const res = { method: 'POST', url: `/auth/refresh` as const }
  return res
}

/**
 * @summary Обновление access/refresh токенов
 * {@link /auth/refresh}
 */
export async function refresh(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<RefreshMutationResponse, ResponseErrorConfig<Refresh401>, unknown>({ method : "POST", url : getRefreshUrl().url.toString(), ... requestConfig })
  return refreshMutationResponseSchema.parse(res.data)
}