/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionDetail } from "../CorrectionDetail";

export interface ApproveCorrectionByDtoePathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Согласовано ДТОиР
*/
export type ApproveCorrectionByDtoe200 = CorrectionDetail;

export type ApproveCorrectionByDtoeMutationResponse = ApproveCorrectionByDtoe200;

export type ApproveCorrectionByDtoeMutation = {
    Response: ApproveCorrectionByDtoe200;
    PathParams: ApproveCorrectionByDtoePathParams;
    Errors: any;
};