/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionDetail } from "../CorrectionDetail";

export interface ApproveCorrectionByCfoPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Согласовано
*/
export type ApproveCorrectionByCfo200 = CorrectionDetail;

export type ApproveCorrectionByCfoMutationResponse = ApproveCorrectionByCfo200;

export type ApproveCorrectionByCfoMutation = {
    Response: ApproveCorrectionByCfo200;
    PathParams: ApproveCorrectionByCfoPathParams;
    Errors: any;
};