/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionDetail } from "../CorrectionDetail";
import type { ErrorResponse2 } from "../ErrorResponse2";

export interface CancelCfoDecisionPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Решение ЦФО отменено, статус возвращён в PENDING
*/
export type CancelCfoDecision200 = CorrectionDetail;

/**
 * @description Нечего отменять или корректировка уже вне зоны ответственности ЦФО
*/
export type CancelCfoDecision400 = ErrorResponse2;

export type CancelCfoDecisionMutationResponse = CancelCfoDecision200;

export type CancelCfoDecisionMutation = {
    Response: CancelCfoDecision200;
    PathParams: CancelCfoDecisionPathParams;
    Errors: CancelCfoDecision400;
};