/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface DeleteRemarkPathParams {
    /**
     * @type string
    */
    humanId: string;
    /**
     * @type integer
    */
    remarkId: number;
}

/**
 * @description Замечание удалено
*/
export type DeleteRemark204 = unknown;

export type DeleteRemarkMutationResponse = DeleteRemark204;

export type DeleteRemarkMutation = {
    Response: DeleteRemark204;
    PathParams: DeleteRemarkPathParams;
    Errors: any;
};