/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface DeleteCorrectionPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Корректировка удалена
*/
export type DeleteCorrection204 = unknown;

export type DeleteCorrectionMutationResponse = DeleteCorrection204;

export type DeleteCorrectionMutation = {
    Response: DeleteCorrection204;
    PathParams: DeleteCorrectionPathParams;
    Errors: any;
};