/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse2 } from "../ErrorResponse2";

export interface DownloadFileVersionPathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Бинарное содержимое файла
*/
export type DownloadFileVersion200 = Blob;

/**
 * @description Нет доступа
*/
export type DownloadFileVersion403 = ErrorResponse2;

export type DownloadFileVersionQueryResponse = DownloadFileVersion200;

export type DownloadFileVersionQuery = {
    Response: DownloadFileVersion200;
    PathParams: DownloadFileVersionPathParams;
    Errors: DownloadFileVersion403;
};