/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionStats2 } from "../CorrectionStats2";
import type { ErrorResponse2 } from "../ErrorResponse2";

/**
 * @description Агрегированные счётчики в рамках видимости роли CFO
*/
export type GetCorrectionStatsCfo200 = CorrectionStats2;

/**
 * @description У пользователя не роль CFO
*/
export type GetCorrectionStatsCfo403 = ErrorResponse2;

export type GetCorrectionStatsCfoQueryResponse = GetCorrectionStatsCfo200;

export type GetCorrectionStatsCfoQuery = {
    Response: GetCorrectionStatsCfo200;
    Errors: GetCorrectionStatsCfo403;
};