/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionDetail } from "../CorrectionDetail";
import type { ErrorResponse2 } from "../ErrorResponse2";

export interface GetCorrectionPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Детальная карточка корректировки
*/
export type GetCorrection200 = CorrectionDetail;

/**
 * @description Нет доступа к этой корректировке
*/
export type GetCorrection403 = ErrorResponse2;

/**
 * @description Не найдено
*/
export type GetCorrection404 = ErrorResponse2;

export type GetCorrectionQueryResponse = GetCorrection200;

export type GetCorrectionQuery = {
    Response: GetCorrection200;
    PathParams: GetCorrectionPathParams;
    Errors: GetCorrection403 | GetCorrection404;
};