/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionStats2 } from "../CorrectionStats2";

/**
 * @description Агрегированные счётчики для карточек дашборда (в рамках видимости роли)
*/
export type GetCorrectionStats200 = CorrectionStats2;

export type GetCorrectionStatsQueryResponse = GetCorrectionStats200;

export type GetCorrectionStatsQuery = {
    Response: GetCorrectionStats200;
    Errors: any;
};