/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Remark } from "../Remark";
import type { RemarkReopenInput } from "../RemarkReopenInput";

export interface ReopenRemarkPathParams {
    /**
     * @type string
    */
    humanId: string;
    /**
     * @type integer
    */
    remarkId: number;
}

/**
 * @description Замечание переоткрыто
*/
export type ReopenRemark200 = Remark;

export type ReopenRemarkMutationRequest = RemarkReopenInput;

export type ReopenRemarkMutationResponse = ReopenRemark200;

export type ReopenRemarkMutation = {
    Response: ReopenRemark200;
    Request: ReopenRemarkMutationRequest;
    PathParams: ReopenRemarkPathParams;
    Errors: any;
};