/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CfoSelectionInput } from "../CfoSelectionInput";
import type { CorrectionDetail } from "../CorrectionDetail";

export interface ResubmitCorrectionPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Повторно направлено
*/
export type ResubmitCorrection200 = CorrectionDetail;

export type ResubmitCorrectionMutationRequest = CfoSelectionInput;

export type ResubmitCorrectionMutationResponse = ResubmitCorrection200;

export type ResubmitCorrectionMutation = {
    Response: ResubmitCorrection200;
    Request: ResubmitCorrectionMutationRequest;
    PathParams: ResubmitCorrectionPathParams;
    Errors: any;
};