/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionDetail } from "../CorrectionDetail";

export interface ReturnCorrectionByDtoePathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Возвращено ДТОиР на доработку
*/
export type ReturnCorrectionByDtoe200 = CorrectionDetail;

export type ReturnCorrectionByDtoeMutationResponse = ReturnCorrectionByDtoe200;

export type ReturnCorrectionByDtoeMutation = {
    Response: ReturnCorrectionByDtoe200;
    PathParams: ReturnCorrectionByDtoePathParams;
    Errors: any;
};