/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionDetail } from "../CorrectionDetail";

export interface ReturnCorrectionByCfoPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Возвращено на доработку
*/
export type ReturnCorrectionByCfo200 = CorrectionDetail;

export type ReturnCorrectionByCfoMutationResponse = ReturnCorrectionByCfo200;

export type ReturnCorrectionByCfoMutation = {
    Response: ReturnCorrectionByCfo200;
    PathParams: ReturnCorrectionByCfoPathParams;
    Errors: any;
};