/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CfoSelectionInput } from "../CfoSelectionInput";
import type { CorrectionDetail } from "../CorrectionDetail";
import type { ErrorResponse2 } from "../ErrorResponse2";

export interface SendCorrectionPathParams {
    /**
     * @type string
    */
    humanId: string;
}

/**
 * @description Направлено
*/
export type SendCorrection200 = CorrectionDetail;

/**
 * @description Пакет не укомплектован либо ЦФО не выбраны/не привязаны
*/
export type SendCorrection400 = ErrorResponse2;

export type SendCorrectionMutationRequest = CfoSelectionInput;

export type SendCorrectionMutationResponse = SendCorrection200;

export type SendCorrectionMutation = {
    Response: SendCorrection200;
    Request: SendCorrectionMutationRequest;
    PathParams: SendCorrectionPathParams;
    Errors: SendCorrection400;
};