/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DownloadFactFormVersionQueryResponse, DownloadFactFormVersionPathParams, DownloadFactFormVersion403 } from "../../types/factPackagesController/DownloadFactFormVersion";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { downloadFactFormVersion } from "../../clients/factPackagesController/downloadFactFormVersion";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const downloadFactFormVersionQueryKey = ({ id }: { id: DownloadFactFormVersionPathParams["id"] | undefined }) => [{ url: '/fact-files/:id/download', params: {id:id} }] as const

export type DownloadFactFormVersionQueryKey = ReturnType<typeof downloadFactFormVersionQueryKey>

export function downloadFactFormVersionQueryOptions({ id }: { id: DownloadFactFormVersionPathParams["id"] | undefined }, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = downloadFactFormVersionQueryKey({ id })
        return queryOptions<DownloadFactFormVersionQueryResponse, ResponseErrorConfig<DownloadFactFormVersion403>, DownloadFactFormVersionQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return downloadFactFormVersion({ id: id! }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Открыть/скачать содержимое версии файла формы. Доступно ролям CFO и DTOE
 * (проверяющим) с доступом к факт-пакету, а также FILIAL-владельцу
 * факт-пакета.
 * @summary Скачать файл версии формы факт-пакета
 * {@link /fact-files/:id/download}
 */
export function useDownloadFactFormVersion<TData = DownloadFactFormVersionQueryResponse, TQueryData = DownloadFactFormVersionQueryResponse, TQueryKey extends QueryKey = DownloadFactFormVersionQueryKey>({ id }: { id: DownloadFactFormVersionPathParams["id"] | undefined }, options: 
{
  query?: Partial<QueryObserverOptions<DownloadFactFormVersionQueryResponse, ResponseErrorConfig<DownloadFactFormVersion403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? downloadFactFormVersionQueryKey({ id })
         

         const query = useQuery({
          ...downloadFactFormVersionQueryOptions({ id }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<DownloadFactFormVersion403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}