/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFactPackageStatsCfoQueryResponse, GetFactPackageStatsCfo403 } from "../../types/factPackagesController/GetFactPackageStatsCfo";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getFactPackageStatsCfo } from "../../clients/factPackagesController/getFactPackageStatsCfo";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getFactPackageStatsCfoSuspenseQueryKey = () => [{ url: '/fact-packages/stats/cfo' }] as const

export type GetFactPackageStatsCfoSuspenseQueryKey = ReturnType<typeof getFactPackageStatsCfoSuspenseQueryKey>

export function getFactPackageStatsCfoSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFactPackageStatsCfoSuspenseQueryKey()
        return queryOptions<GetFactPackageStatsCfoQueryResponse, ResponseErrorConfig<GetFactPackageStatsCfo403>, GetFactPackageStatsCfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getFactPackageStatsCfo({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Доступно только пользователю роли CFO.
 * @summary Статистика по факт-пакетам для «Рабочего стола» ЦФО
 * {@link /fact-packages/stats/cfo}
 */
export function useGetFactPackageStatsCfoSuspense<TData = GetFactPackageStatsCfoQueryResponse, TQueryKey extends QueryKey = GetFactPackageStatsCfoSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetFactPackageStatsCfoQueryResponse, ResponseErrorConfig<GetFactPackageStatsCfo403>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFactPackageStatsCfoSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getFactPackageStatsCfoSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetFactPackageStatsCfo403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}