/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFactPackageStatsFilialQueryResponse, GetFactPackageStatsFilial403 } from "../../types/factPackagesController/GetFactPackageStatsFilial";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getFactPackageStatsFilial } from "../../clients/factPackagesController/getFactPackageStatsFilial";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getFactPackageStatsFilialQueryKey = () => [{ url: '/fact-packages/stats/filial' }] as const

export type GetFactPackageStatsFilialQueryKey = ReturnType<typeof getFactPackageStatsFilialQueryKey>

export function getFactPackageStatsFilialQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFactPackageStatsFilialQueryKey()
        return queryOptions<GetFactPackageStatsFilialQueryResponse, ResponseErrorConfig<GetFactPackageStatsFilial403>, GetFactPackageStatsFilialQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getFactPackageStatsFilial({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Доступно только пользователю роли FILIAL.
 * @summary Статистика по факт-пакетам для «Рабочего стола» филиала
 * {@link /fact-packages/stats/filial}
 */
export function useGetFactPackageStatsFilial<TData = GetFactPackageStatsFilialQueryResponse, TQueryData = GetFactPackageStatsFilialQueryResponse, TQueryKey extends QueryKey = GetFactPackageStatsFilialQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetFactPackageStatsFilialQueryResponse, ResponseErrorConfig<GetFactPackageStatsFilial403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFactPackageStatsFilialQueryKey()
         

         const query = useQuery({
          ...getFactPackageStatsFilialQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetFactPackageStatsFilial403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}