/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetOrCreateFactPackageByDirectionQueryResponse, GetOrCreateFactPackageByDirectionPathParams, GetOrCreateFactPackageByDirection403 } from "../../types/factPackagesController/GetOrCreateFactPackageByDirection";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getOrCreateFactPackageByDirection } from "../../clients/factPackagesController/getOrCreateFactPackageByDirection";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getOrCreateFactPackageByDirectionSuspenseQueryKey = ({ direction }: { direction: GetOrCreateFactPackageByDirectionPathParams["direction"] | undefined }) => [{ url: '/fact-packages/by-direction/:direction', params: {direction:direction} }] as const

export type GetOrCreateFactPackageByDirectionSuspenseQueryKey = ReturnType<typeof getOrCreateFactPackageByDirectionSuspenseQueryKey>

export function getOrCreateFactPackageByDirectionSuspenseQueryOptions({ direction }: { direction: GetOrCreateFactPackageByDirectionPathParams["direction"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getOrCreateFactPackageByDirectionSuspenseQueryKey({ direction })
        return queryOptions<GetOrCreateFactPackageByDirectionQueryResponse, ResponseErrorConfig<GetOrCreateFactPackageByDirection403>, GetOrCreateFactPackageByDirectionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getOrCreateFactPackageByDirection({ direction: direction }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Доступно только роли FILIAL. Один факт-пакет на пару «Филиал × Направление»
 * без периода: если пакета для (свой филиал, направление) ещё нет, он
 * создаётся атомарно в статусе DRAFT вместе со всеми формами каталога
 * направления (без версий файлов), и возвращается. Повторные вызовы для той
 * же пары идемпотентны и возвращают тот же факт-пакет.
 * @summary Получить (или создать) факт-пакет своего филиала по направлению
 * {@link /fact-packages/by-direction/:direction}
 */
export function useGetOrCreateFactPackageByDirectionSuspense<TData = GetOrCreateFactPackageByDirectionQueryResponse, TQueryKey extends QueryKey = GetOrCreateFactPackageByDirectionSuspenseQueryKey>({ direction }: { direction: GetOrCreateFactPackageByDirectionPathParams["direction"] }, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetOrCreateFactPackageByDirectionQueryResponse, ResponseErrorConfig<GetOrCreateFactPackageByDirection403>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getOrCreateFactPackageByDirectionSuspenseQueryKey({ direction })
         

         const query = useSuspenseQuery({
          ...getOrCreateFactPackageByDirectionSuspenseQueryOptions({ direction }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetOrCreateFactPackageByDirection403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}