/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFactPackageQueryResponse, GetFactPackagePathParams, GetFactPackage403, GetFactPackage404 } from "../../types/factPackagesController/GetFactPackage";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getFactPackage } from "../../clients/factPackagesController/getFactPackage";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getFactPackageQueryKey = ({ humanId }: { humanId: GetFactPackagePathParams["humanId"] | undefined }) => [{ url: '/fact-packages/:humanId', params: {humanId:humanId} }] as const

export type GetFactPackageQueryKey = ReturnType<typeof getFactPackageQueryKey>

export function getFactPackageQueryOptions({ humanId }: { humanId: GetFactPackagePathParams["humanId"] | undefined }, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFactPackageQueryKey({ humanId })
        return queryOptions<GetFactPackageQueryResponse, ResponseErrorConfig<GetFactPackage403 | GetFactPackage404>, GetFactPackageQueryResponse, typeof queryKey>({
         enabled: !!(humanId),
         queryKey,
         queryFn: async ({ signal }) => {
            return getFactPackage({ humanId: humanId! }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Детальная карточка факт-пакета
 * {@link /fact-packages/:humanId}
 */
export function useGetFactPackage<TData = GetFactPackageQueryResponse, TQueryData = GetFactPackageQueryResponse, TQueryKey extends QueryKey = GetFactPackageQueryKey>({ humanId }: { humanId: GetFactPackagePathParams["humanId"] | undefined }, options: 
{
  query?: Partial<QueryObserverOptions<GetFactPackageQueryResponse, ResponseErrorConfig<GetFactPackage403 | GetFactPackage404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFactPackageQueryKey({ humanId })
         

         const query = useQuery({
          ...getFactPackageQueryOptions({ humanId }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetFactPackage403 | GetFactPackage404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}