/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFactPackageStatsCfoQueryResponse, GetFactPackageStatsCfo403 } from "../../types/factPackagesController/GetFactPackageStatsCfo";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getFactPackageStatsCfo } from "../../clients/factPackagesController/getFactPackageStatsCfo";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getFactPackageStatsCfoQueryKey = () => [{ url: '/fact-packages/stats/cfo' }] as const

export type GetFactPackageStatsCfoQueryKey = ReturnType<typeof getFactPackageStatsCfoQueryKey>

export function getFactPackageStatsCfoQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFactPackageStatsCfoQueryKey()
        return queryOptions<GetFactPackageStatsCfoQueryResponse, ResponseErrorConfig<GetFactPackageStatsCfo403>, GetFactPackageStatsCfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getFactPackageStatsCfo({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Доступно только пользователю роли CFO.
 * @summary Статистика по факт-пакетам для «Рабочего стола» ЦФО
 * {@link /fact-packages/stats/cfo}
 */
export function useGetFactPackageStatsCfo<TData = GetFactPackageStatsCfoQueryResponse, TQueryData = GetFactPackageStatsCfoQueryResponse, TQueryKey extends QueryKey = GetFactPackageStatsCfoQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetFactPackageStatsCfoQueryResponse, ResponseErrorConfig<GetFactPackageStatsCfo403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFactPackageStatsCfoQueryKey()
         

         const query = useQuery({
          ...getFactPackageStatsCfoQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetFactPackageStatsCfo403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}