/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFactPackageQueryResponse, GetFactPackagePathParams, GetFactPackage403, GetFactPackage404 } from "../../types/factPackagesController/GetFactPackage";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getFactPackage } from "../../clients/factPackagesController/getFactPackage";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getFactPackageSuspenseQueryKey = ({ humanId }: { humanId: GetFactPackagePathParams["humanId"] | undefined }) => [{ url: '/fact-packages/:humanId', params: {humanId:humanId} }] as const

export type GetFactPackageSuspenseQueryKey = ReturnType<typeof getFactPackageSuspenseQueryKey>

export function getFactPackageSuspenseQueryOptions({ humanId }: { humanId: GetFactPackagePathParams["humanId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFactPackageSuspenseQueryKey({ humanId })
        return queryOptions<GetFactPackageQueryResponse, ResponseErrorConfig<GetFactPackage403 | GetFactPackage404>, GetFactPackageQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getFactPackage({ humanId: humanId }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Детальная карточка факт-пакета
 * {@link /fact-packages/:humanId}
 */
export function useGetFactPackageSuspense<TData = GetFactPackageQueryResponse, TQueryKey extends QueryKey = GetFactPackageSuspenseQueryKey>({ humanId }: { humanId: GetFactPackagePathParams["humanId"] }, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetFactPackageQueryResponse, ResponseErrorConfig<GetFactPackage403 | GetFactPackage404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFactPackageSuspenseQueryKey({ humanId })
         

         const query = useSuspenseQuery({
          ...getFactPackageSuspenseQueryOptions({ humanId }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetFactPackage403 | GetFactPackage404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}