/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFactPackagesQueryResponse, GetFactPackagesQueryParams } from "../../types/factPackagesController/GetFactPackages";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getFactPackages } from "../../clients/factPackagesController/getFactPackages";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getFactPackagesSuspenseQueryKey = (params?: GetFactPackagesQueryParams) => [{ url: '/fact-packages' }, ...(params ? [params] : [])] as const

export type GetFactPackagesSuspenseQueryKey = ReturnType<typeof getFactPackagesSuspenseQueryKey>

export function getFactPackagesSuspenseQueryOptions({ params }: { params?: GetFactPackagesQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getFactPackagesSuspenseQueryKey(params)
        return queryOptions<GetFactPackagesQueryResponse, ResponseErrorConfig<Error>, GetFactPackagesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getFactPackages({ params: params }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Список автоматически ограничен ролью: FILIAL видит свои, CFO — направленные его ЦФО, DTOE/ADMIN — все (аудит).
 * @summary Список факт-пакетов (в рамках видимости роли)
 * {@link /fact-packages}
 */
export function useGetFactPackagesSuspense<TData = GetFactPackagesQueryResponse, TQueryKey extends QueryKey = GetFactPackagesSuspenseQueryKey>({ params }: { params?: GetFactPackagesQueryParams } = {}, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetFactPackagesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getFactPackagesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getFactPackagesSuspenseQueryOptions({ params }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}