/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { LeaveFactPackageRemarkMutationRequest, LeaveFactPackageRemarkMutationResponse, LeaveFactPackageRemarkPathParams, LeaveFactPackageRemark400, LeaveFactPackageRemark403 } from "../../types/factPackagesController/LeaveFactPackageRemark";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { leaveFactPackageRemark } from "../../clients/factPackagesController/leaveFactPackageRemark";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const leaveFactPackageRemarkMutationKey = () => [{ url: '/fact-packages/:humanId/remarks' }] as const

export type LeaveFactPackageRemarkMutationKey = ReturnType<typeof leaveFactPackageRemarkMutationKey>

export function leaveFactPackageRemarkMutationOptions<TContext = unknown>(config: Partial<RequestConfig<LeaveFactPackageRemarkMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = leaveFactPackageRemarkMutationKey()
        return mutationOptions<LeaveFactPackageRemarkMutationResponse, ResponseErrorConfig<LeaveFactPackageRemark400 | LeaveFactPackageRemark403>, {humanId: LeaveFactPackageRemarkPathParams["humanId"], data: LeaveFactPackageRemarkMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, data }) => {
            return leaveFactPackageRemark({ humanId, data }, config)
          },
        })

}

/**
 * @description Роли CFO и DTOE. Доступно только пока факт-пакет находится на проверке у
 * автора замечания (для ЦФО — его статус проверки PENDING; для ДТОиР —
 * статус факт-пакета UNDER_DTOE_REVIEW). Атомарно переводит факт-пакет в
 * RETURNED_FOR_REVISION и статус проверки автора — в RETURNED.
 * @summary Оставить замечание к форме факт-пакета
 * {@link /fact-packages/:humanId/remarks}
 */
export function useLeaveFactPackageRemark<TContext>(options: 
{
  mutation?: UseMutationOptions<LeaveFactPackageRemarkMutationResponse, ResponseErrorConfig<LeaveFactPackageRemark400 | LeaveFactPackageRemark403>, {humanId: LeaveFactPackageRemarkPathParams["humanId"], data: LeaveFactPackageRemarkMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<LeaveFactPackageRemarkMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? leaveFactPackageRemarkMutationKey()

          const baseOptions = leaveFactPackageRemarkMutationOptions(config) as UseMutationOptions<LeaveFactPackageRemarkMutationResponse, ResponseErrorConfig<LeaveFactPackageRemark400 | LeaveFactPackageRemark403>, {humanId: LeaveFactPackageRemarkPathParams["humanId"], data: LeaveFactPackageRemarkMutationRequest}, TContext>
          

          return useMutation<LeaveFactPackageRemarkMutationResponse, ResponseErrorConfig<LeaveFactPackageRemark400 | LeaveFactPackageRemark403>, {humanId: LeaveFactPackageRemarkPathParams["humanId"], data: LeaveFactPackageRemarkMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<LeaveFactPackageRemarkMutationResponse, ResponseErrorConfig<LeaveFactPackageRemark400 | LeaveFactPackageRemark403>, {humanId: LeaveFactPackageRemarkPathParams["humanId"], data: LeaveFactPackageRemarkMutationRequest}, TContext>
      
}