/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { SendFactPackageToDtoeMutationResponse, SendFactPackageToDtoePathParams, SendFactPackageToDtoe400, SendFactPackageToDtoe403 } from "../../types/factPackagesController/SendFactPackageToDtoe";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { sendFactPackageToDtoe } from "../../clients/factPackagesController/sendFactPackageToDtoe";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const sendFactPackageToDtoeMutationKey = () => [{ url: '/fact-packages/:humanId/send-to-dtoe' }] as const

export type SendFactPackageToDtoeMutationKey = ReturnType<typeof sendFactPackageToDtoeMutationKey>

export function sendFactPackageToDtoeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = sendFactPackageToDtoeMutationKey()
        return mutationOptions<SendFactPackageToDtoeMutationResponse, ResponseErrorConfig<SendFactPackageToDtoe400 | SendFactPackageToDtoe403>, {humanId: SendFactPackageToDtoePathParams["humanId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId }) => {
            return sendFactPackageToDtoe({ humanId }, config)
          },
        })

}

/**
 * @description Доступно любому согласовавшему ЦФО этого факт-пакета, когда все обязательные ЦФО согласовали (canSendToDtoe).
 * @summary Отправить факт-пакет в ДТОиР
 * {@link /fact-packages/:humanId/send-to-dtoe}
 */
export function useSendFactPackageToDtoe<TContext>(options: 
{
  mutation?: UseMutationOptions<SendFactPackageToDtoeMutationResponse, ResponseErrorConfig<SendFactPackageToDtoe400 | SendFactPackageToDtoe403>, {humanId: SendFactPackageToDtoePathParams["humanId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? sendFactPackageToDtoeMutationKey()

          const baseOptions = sendFactPackageToDtoeMutationOptions(config) as UseMutationOptions<SendFactPackageToDtoeMutationResponse, ResponseErrorConfig<SendFactPackageToDtoe400 | SendFactPackageToDtoe403>, {humanId: SendFactPackageToDtoePathParams["humanId"]}, TContext>
          

          return useMutation<SendFactPackageToDtoeMutationResponse, ResponseErrorConfig<SendFactPackageToDtoe400 | SendFactPackageToDtoe403>, {humanId: SendFactPackageToDtoePathParams["humanId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<SendFactPackageToDtoeMutationResponse, ResponseErrorConfig<SendFactPackageToDtoe400 | SendFactPackageToDtoe403>, {humanId: SendFactPackageToDtoePathParams["humanId"]}, TContext>
      
}