/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { SubmitFactPackageMutationRequest, SubmitFactPackageMutationResponse, SubmitFactPackagePathParams, SubmitFactPackage400 } from "../../types/factPackagesController/SubmitFactPackage";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { submitFactPackage } from "../../clients/factPackagesController/submitFactPackage";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const submitFactPackageMutationKey = () => [{ url: '/fact-packages/:humanId/submit' }] as const

export type SubmitFactPackageMutationKey = ReturnType<typeof submitFactPackageMutationKey>

export function submitFactPackageMutationOptions<TContext = unknown>(config: Partial<RequestConfig<SubmitFactPackageMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = submitFactPackageMutationKey()
        return mutationOptions<SubmitFactPackageMutationResponse, ResponseErrorConfig<SubmitFactPackage400>, {humanId: SubmitFactPackagePathParams["humanId"], data: SubmitFactPackageMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, data }) => {
            return submitFactPackage({ humanId, data }, config)
          },
        })

}

/**
 * @description Филиал направляет укомплектованный пакет выбранным ЦФО (cfoIds
 * обязателен). Обслуживает и первичное направление (DRAFT), и повторное
 * направление после доработки (RETURNED_FOR_REVISION) — в этом случае
 * доступно только когда все замечания от вернувших ЦФО отмечены
 * исправленными; статус согласовавших ранее ЦФО не сбрасывается. Для
 * пакета, созданного самим ЦФО, cfoIds не нужен — уходит сразу в ДТОиР.
 * @summary Направить факт-пакет — Филиал выбранным ЦФО, ЦФО сразу в ДТОиР
 * {@link /fact-packages/:humanId/submit}
 */
export function useSubmitFactPackage<TContext>(options: 
{
  mutation?: UseMutationOptions<SubmitFactPackageMutationResponse, ResponseErrorConfig<SubmitFactPackage400>, {humanId: SubmitFactPackagePathParams["humanId"], data: SubmitFactPackageMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<SubmitFactPackageMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? submitFactPackageMutationKey()

          const baseOptions = submitFactPackageMutationOptions(config) as UseMutationOptions<SubmitFactPackageMutationResponse, ResponseErrorConfig<SubmitFactPackage400>, {humanId: SubmitFactPackagePathParams["humanId"], data: SubmitFactPackageMutationRequest}, TContext>
          

          return useMutation<SubmitFactPackageMutationResponse, ResponseErrorConfig<SubmitFactPackage400>, {humanId: SubmitFactPackagePathParams["humanId"], data: SubmitFactPackageMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<SubmitFactPackageMutationResponse, ResponseErrorConfig<SubmitFactPackage400>, {humanId: SubmitFactPackagePathParams["humanId"], data: SubmitFactPackageMutationRequest}, TContext>
      
}