/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUser201, CreateUserMutationRequest, CreateUserMutationResponse } from "../../types/usersController/CreateUser";
import { createUser } from "../createUser";
import { createUserCreateInput } from "../createUserCreateInput";
import { faker } from "@faker-js/faker";

/**
 * @description Пользователь создан
 */
export function createCreateUser201(data?: Partial<CreateUser201>): CreateUser201 {

  return createUser(data)
}

export function createCreateUserMutationRequest(data?: Partial<CreateUserMutationRequest>): CreateUserMutationRequest {

  return createUserCreateInput(data)
}

export function createCreateUserMutationResponse(data?: Partial<CreateUserMutationResponse>): CreateUserMutationResponse {

  return data || faker.helpers.arrayElement<any>([createCreateUser201()])
}