/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateUser200, UpdateUserMutationRequest, UpdateUserMutationResponse, UpdateUserPathParams } from "../../types/usersController/UpdateUser";
import { createUser } from "../createUser";
import { createUserUpdateInput } from "../createUserUpdateInput";
import { faker } from "@faker-js/faker";

export function createUpdateUserPathParams(data?: Partial<UpdateUserPathParams>): UpdateUserPathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Пользователь обновлён
 */
export function createUpdateUser200(data?: Partial<UpdateUser200>): UpdateUser200 {

  return createUser(data)
}

export function createUpdateUserMutationRequest(data?: Partial<UpdateUserMutationRequest>): UpdateUserMutationRequest {

  return createUserUpdateInput(data)
}

export function createUpdateUserMutationResponse(data?: Partial<UpdateUserMutationResponse>): UpdateUserMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUpdateUser200()])
}