/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteUserMutationResponse, DeleteUserPathParams } from "../../types/usersController/DeleteUser";
import { faker } from "@faker-js/faker";

export function createDeleteUserPathParams(data?: Partial<DeleteUserPathParams>): DeleteUserPathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Удалено
 */
export function createDeleteUser204() {

  return undefined
}

export function createDeleteUserMutationResponse(data?: Partial<DeleteUserMutationResponse>): DeleteUserMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeleteUser204()])
}