/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUsers200, GetUsersQueryParams, GetUsersQueryResponse } from "../../types/usersController/GetUsers";
import { createRole2 } from "../createRole2";
import { createUser } from "../createUser";
import { faker } from "@faker-js/faker";

export function createGetUsersQueryParams(data?: Partial<GetUsersQueryParams>): GetUsersQueryParams {

  return { ...{get "role"() { return createRole2() },"filialId": faker.number.int(),"cfoId": faker.number.int(),"q": faker.string.alpha(),...(data || {})} }
}

/**
 * @description Список пользователей
 */
export function createGetUsers200(data?: GetUsers200): GetUsers200 {

  return [
        ...faker.helpers.multiple(() => (createUser())),
        ...data || []
      ]
}

export function createGetUsersQueryResponse(data?: Partial<GetUsersQueryResponse>): GetUsersQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetUsers200()])
}