/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreatePlanPackageRequirementMutationRequest, CreatePlanPackageRequirementMutationResponse, CreatePlanPackageRequirementPathParams } from "../../types/orgController/CreatePlanPackageRequirement";
import { createPlanPackageRequirementMutationResponseSchema, createPlanPackageRequirementMutationRequestSchema } from "../../zod/orgController/createPlanPackageRequirementSchema";

function getCreatePlanPackageRequirementUrl({ id }: { id: CreatePlanPackageRequirementPathParams["id"] }) {
  const res = { method: 'POST', url: `/org/plan-types/${id}/requirements` as const }
  return res
}

/**
 * @summary Добавить требование в пакет типа плана
 * {@link /org/plan-types/:id/requirements}
 */
export async function createPlanPackageRequirement({ id, data }: { id: CreatePlanPackageRequirementPathParams["id"]; data: CreatePlanPackageRequirementMutationRequest }, config: Partial<RequestConfig<CreatePlanPackageRequirementMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = createPlanPackageRequirementMutationRequestSchema.parse(data)

  const res = await request<CreatePlanPackageRequirementMutationResponse, ResponseErrorConfig<Error>, CreatePlanPackageRequirementMutationRequest>({ method : "POST", url : getCreatePlanPackageRequirementUrl({ id }).url.toString(), data : requestData, ... requestConfig })
  return createPlanPackageRequirementMutationResponseSchema.parse(res.data)
}