/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreateCfoMutationRequest, CreateCfoMutationResponse } from "../../types/orgController/CreateCfo";
import { createCfoMutationResponseSchema, createCfoMutationRequestSchema } from "../../zod/orgController/createCfoSchema";

function getCreateCfoUrl() {
  const res = { method: 'POST', url: `/org/cfos` as const }
  return res
}

/**
 * @summary Создать ЦФО
 * {@link /org/cfos}
 */
export async function createCfo({ data }: { data: CreateCfoMutationRequest }, config: Partial<RequestConfig<CreateCfoMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = createCfoMutationRequestSchema.parse(data)

  const res = await request<CreateCfoMutationResponse, ResponseErrorConfig<Error>, CreateCfoMutationRequest>({ method : "POST", url : getCreateCfoUrl().url.toString(), data : requestData, ... requestConfig })
  return createCfoMutationResponseSchema.parse(res.data)
}