/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeleteFilialCfoLinkMutationResponse, DeleteFilialCfoLinkPathParams } from "../../types/orgController/DeleteFilialCfoLink";
import { deleteFilialCfoLinkMutationResponseSchema } from "../../zod/orgController/deleteFilialCfoLinkSchema";

function getDeleteFilialCfoLinkUrl({ id }: { id: DeleteFilialCfoLinkPathParams["id"] }) {
  const res = { method: 'DELETE', url: `/org/filial-cfo-links/${id}` as const }
  return res
}

/**
 * @summary Удалить связь филиал-ЦФО
 * {@link /org/filial-cfo-links/:id}
 */
export async function deleteFilialCfoLink({ id }: { id: DeleteFilialCfoLinkPathParams["id"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteFilialCfoLinkMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteFilialCfoLinkUrl({ id }).url.toString(), ... requestConfig })
  return deleteFilialCfoLinkMutationResponseSchema.parse(res.data)
}