/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeleteFilialMutationResponse, DeleteFilialPathParams } from "../../types/orgController/DeleteFilial";
import { deleteFilialMutationResponseSchema } from "../../zod/orgController/deleteFilialSchema";

function getDeleteFilialUrl({ id }: { id: DeleteFilialPathParams["id"] }) {
  const res = { method: 'DELETE', url: `/org/filials/${id}` as const }
  return res
}

/**
 * @summary Удалить филиал
 * {@link /org/filials/:id}
 */
export async function deleteFilial({ id }: { id: DeleteFilialPathParams["id"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteFilialMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteFilialUrl({ id }).url.toString(), ... requestConfig })
  return deleteFilialMutationResponseSchema.parse(res.data)
}