/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DeleteCfoMutationResponse, DeleteCfoPathParams } from "../../types/orgController/DeleteCfo";
import { deleteCfoMutationResponseSchema } from "../../zod/orgController/deleteCfoSchema";

function getDeleteCfoUrl({ id }: { id: DeleteCfoPathParams["id"] }) {
  const res = { method: 'DELETE', url: `/org/cfos/${id}` as const }
  return res
}

/**
 * @summary Удалить ЦФО
 * {@link /org/cfos/:id}
 */
export async function deleteCfo({ id }: { id: DeleteCfoPathParams["id"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteCfoMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteCfoUrl({ id }).url.toString(), ... requestConfig })
  return deleteCfoMutationResponseSchema.parse(res.data)
}