/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionTypesQueryResponse, GetCorrectionTypesQueryParams } from "../../types/orgController/GetCorrectionTypes";
import { getCorrectionTypesQueryResponseSchema } from "../../zod/orgController/getCorrectionTypesSchema";

function getGetCorrectionTypesUrl() {
  const res = { method: 'GET', url: `/org/correction-types` as const }
  return res
}

/**
 * @summary Список типов корректировок
 * {@link /org/correction-types}
 */
export async function getCorrectionTypes({ params }: { params?: GetCorrectionTypesQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetCorrectionTypesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetCorrectionTypesUrl().url.toString(), params, ... requestConfig })
  return getCorrectionTypesQueryResponseSchema.parse(res.data)
}