/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionTypeQueryResponse, GetCorrectionTypePathParams } from "../../types/orgController/GetCorrectionType";
import { getCorrectionTypeQueryResponseSchema } from "../../zod/orgController/getCorrectionTypeSchema";

function getGetCorrectionTypeUrl({ id }: { id: GetCorrectionTypePathParams["id"] }) {
  const res = { method: 'GET', url: `/org/correction-types/${id}` as const }
  return res
}

/**
 * @summary Тип корректировки с требованиями пакета
 * {@link /org/correction-types/:id}
 */
export async function getCorrectionType({ id }: { id: GetCorrectionTypePathParams["id"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetCorrectionTypeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetCorrectionTypeUrl({ id }).url.toString(), ... requestConfig })
  return getCorrectionTypeQueryResponseSchema.parse(res.data)
}