/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCfosQueryResponse, GetCfosQueryParams } from "../../types/orgController/GetCfos";
import { getCfosQueryResponseSchema } from "../../zod/orgController/getCfosSchema";

function getGetCfosUrl() {
  const res = { method: 'GET', url: `/org/cfos` as const }
  return res
}

/**
 * @summary Список ЦФО
 * {@link /org/cfos}
 */
export async function getCfos({ params }: { params?: GetCfosQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetCfosQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetCfosUrl().url.toString(), params, ... requestConfig })
  return getCfosQueryResponseSchema.parse(res.data)
}