/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFilialCfoLinksQueryResponse, GetFilialCfoLinksQueryParams } from "../../types/orgController/GetFilialCfoLinks";
import { getFilialCfoLinksQueryResponseSchema } from "../../zod/orgController/getFilialCfoLinksSchema";

function getGetFilialCfoLinksUrl() {
  const res = { method: 'GET', url: `/org/filial-cfo-links` as const }
  return res
}

/**
 * @summary Список связей филиал-ЦФО
 * {@link /org/filial-cfo-links}
 */
export async function getFilialCfoLinks({ params }: { params?: GetFilialCfoLinksQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetFilialCfoLinksQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetFilialCfoLinksUrl().url.toString(), params, ... requestConfig })
  return getFilialCfoLinksQueryResponseSchema.parse(res.data)
}