/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetFilialsQueryResponse, GetFilialsQueryParams } from "../../types/orgController/GetFilials";
import { getFilialsQueryResponseSchema } from "../../zod/orgController/getFilialsSchema";

function getGetFilialsUrl() {
  const res = { method: 'GET', url: `/org/filials` as const }
  return res
}

/**
 * @summary Список филиалов
 * {@link /org/filials}
 */
export async function getFilials({ params }: { params?: GetFilialsQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetFilialsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetFilialsUrl().url.toString(), params, ... requestConfig })
  return getFilialsQueryResponseSchema.parse(res.data)
}