/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { UpdateCfoMutationRequest, UpdateCfoMutationResponse, UpdateCfoPathParams } from "../../types/orgController/UpdateCfo";
import { updateCfoMutationResponseSchema, updateCfoMutationRequestSchema } from "../../zod/orgController/updateCfoSchema";

function getUpdateCfoUrl({ id }: { id: UpdateCfoPathParams["id"] }) {
  const res = { method: 'PATCH', url: `/org/cfos/${id}` as const }
  return res
}

/**
 * @summary Обновить ЦФО
 * {@link /org/cfos/:id}
 */
export async function updateCfo({ id, data }: { id: UpdateCfoPathParams["id"]; data: UpdateCfoMutationRequest }, config: Partial<RequestConfig<UpdateCfoMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = updateCfoMutationRequestSchema.parse(data)

  const res = await request<UpdateCfoMutationResponse, ResponseErrorConfig<Error>, UpdateCfoMutationRequest>({ method : "PATCH", url : getUpdateCfoUrl({ id }).url.toString(), data : requestData, ... requestConfig })
  return updateCfoMutationResponseSchema.parse(res.data)
}