/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { UpdateFilialCfoLinkMutationRequest, UpdateFilialCfoLinkMutationResponse, UpdateFilialCfoLinkPathParams } from "../../types/orgController/UpdateFilialCfoLink";
import { updateFilialCfoLinkMutationResponseSchema, updateFilialCfoLinkMutationRequestSchema } from "../../zod/orgController/updateFilialCfoLinkSchema";

function getUpdateFilialCfoLinkUrl({ id }: { id: UpdateFilialCfoLinkPathParams["id"] }) {
  const res = { method: 'PATCH', url: `/org/filial-cfo-links/${id}` as const }
  return res
}

/**
 * @summary Обновить связь филиал-ЦФО
 * {@link /org/filial-cfo-links/:id}
 */
export async function updateFilialCfoLink({ id, data }: { id: UpdateFilialCfoLinkPathParams["id"]; data: UpdateFilialCfoLinkMutationRequest }, config: Partial<RequestConfig<UpdateFilialCfoLinkMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = updateFilialCfoLinkMutationRequestSchema.parse(data)

  const res = await request<UpdateFilialCfoLinkMutationResponse, ResponseErrorConfig<Error>, UpdateFilialCfoLinkMutationRequest>({ method : "PATCH", url : getUpdateFilialCfoLinkUrl({ id }).url.toString(), data : requestData, ... requestConfig })
  return updateFilialCfoLinkMutationResponseSchema.parse(res.data)
}