/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const cfoSelectionInputSchema = z.object({
    "cfoIds": z.array(z.int()).check(z.minLength(1))
    })