/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { correctionSchema } from "./correctionSchema";

export const correctionDetailSchema = z.lazy(() => correctionSchema)