/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { userSummarySchema } from "./userSummarySchema";

export const correctionHistoryEntry2Schema = z.object({
    "id": z.int(),
"correctionId": z.int(),
"timestamp": z.string(),
"userId": z.nullish(z.int()),
get "user"(){
                return z.optional(z.union([userSummarySchema, z.null()]))
              },
"text": z.string()
    })