/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { correctionTypeSchema } from "./correctionTypeSchema";
import { packageRequirementSchema } from "./packageRequirementSchema";

export const correctionTypeDetailSchema = z.lazy(() => correctionTypeSchema).and(z.object({
    get "requirements"(){
                return z.array(packageRequirementSchema).optional()
              }
    }))