/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { cfoSchema } from "./cfoSchema";
import { fileVersion2Schema } from "./fileVersion2Schema";

export const documentSlotSchema = z.object({
    "id": z.int(),
"correctionId": z.int(),
"requirementId": z.nullable(z.int()),
"label": z.string(),
"isFilled": z.boolean(),
"isRequired": z.boolean(),
get "responsibleCfo"(){
                return z.union([cfoSchema, z.null()])
              },
get "currentVersion"(){
                return z.optional(z.union([fileVersion2Schema, z.null()]))
              }
    })