/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { userSummarySchema } from "./userSummarySchema";

export const factPackageHistoryEntry2Schema = z.object({
    "id": z.int(),
"factPackageId": z.int(),
"userId": z.nullish(z.int()),
get "user"(){
                return z.optional(z.union([userSummarySchema, z.null()]))
              },
"timestamp": z.string(),
"text": z.string()
    })