/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const factPackageRemarkCreateInputSchema = z.object({
    "relatedFormId": z.int(),
"description": z.string(),
"requiredAction": z.string()
    })