/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const factFormCode2Schema = z.enum(["ACT_WORK", "ACT_SERVICE", "KS2", "KS3", "ACT_MATERIALS", "INVOICE", "PAYMENT_REQUEST"])