/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { factFormCode2Schema } from "./factFormCode2Schema";
import { factFormVersion2Schema } from "./factFormVersion2Schema";

export const factFormSchema = z.object({
    "id": z.int(),
"factPackageId": z.int(),
get "code"(){
                return factFormCode2Schema
              },
"label": z.string(),
"isFilled": z.boolean(),
get "currentVersion"(){
                return z.optional(z.union([factFormVersion2Schema, z.null()]))
              },
get "versions"(){
                return z.optional(z.array(factFormVersion2Schema))
              }
    })