/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { cfoSchema } from "./cfoSchema";
import { factForm2Schema } from "./factForm2Schema";
import { factPackageCfoStatus2Schema } from "./factPackageCfoStatus2Schema";
import { factPackageHistoryEntry2Schema } from "./factPackageHistoryEntry2Schema";
import { factPackageRemarkSchema } from "./factPackageRemarkSchema";
import { factPackageSchema } from "./factPackageSchema";
import { filialSchema } from "./filialSchema";
import { userSummarySchema } from "./userSummarySchema";

export const factPackageDetailSchema = z.lazy(() => factPackageSchema).and(z.object({
    get "filial"(){
                return filialSchema
              },
get "author"(){
                return userSummarySchema
              },
get "forms"(){
                return z.array(factForm2Schema)
              },
get "cfoStatuses"(){
                return z.array(factPackageCfoStatus2Schema)
              },
get "remarks"(){
                return z.array(factPackageRemarkSchema)
              },
get "history"(){
                return z.array(factPackageHistoryEntry2Schema)
              },
"packageComplete": z.boolean(),
"missingForms": z.array(z.string()),
get "myCfoStatus"(){
                return z.union([factPackageCfoStatus2Schema, z.null()]).optional()
              },
"myOpenRemarksCount": z.optional(z.int()),
"isFilialOwner": z.boolean(),
"isCfoReviewer": z.boolean(),
"isDtoe": z.boolean(),
get "availableCfos"(){
                return z.array(cfoSchema).describe("ЦФО, доступные для отправки (linked_cfos), для формы «Направить на проверку»")
              },
get "returnedCfos"(){
                return z.array(cfoSchema).describe("ЦФО в статусе RETURNED, для формы «Направить повторно»")
              }
    }))