/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const factFormVersion2Schema = z.object({
    "id": z.int(),
"formId": z.int(),
"versionNumber": z.int(),
"fileName": z.string(),
"fileSize": z.int(),
"mimeType": z.optional(z.string()),
"uploadedById": z.int(),
"uploadedAt": z.string(),
"remarkId": z.nullish(z.int()),
"note": z.optional(z.string())
    })