/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const filialCfoLinkInputSchema = z.object({
    "filialId": z.int(),
"cfoId": z.int(),
"isActive": z.optional(z.boolean())
    })