/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const filialCfoLinkSchema = z.object({
    "id": z.int(),
"filialId": z.int(),
"cfoId": z.int(),
"isActive": z.boolean()
    })