/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const loginRequestSchema = z.object({
    "username": z.string(),
"password": z.string()
    })