/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

/**
 * @description Уведомление относится ровно к одной сущности — либо к корректировке\n(correctionId), либо к факт-пакету (factPackageId); в паре полей заполнено\nровно одно, второе — null (openspec/changes/fact-package-review).\n
 */
export const notification2Schema = z.object({
    "id": z.int(),
"userId": z.int(),
"correctionId": z.nullable(z.int()),
"correctionHumanId": z.optional(z.string()),
"factPackageId": z.nullable(z.int()),
"factPackageHumanId": z.optional(z.string()),
"text": z.string(),
"isRead": z.boolean(),
"createdAt": z.string()
    })