/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const notification2Schema = z.object({
    "id": z.int(),
"userId": z.int(),
"correctionId": z.int(),
"correctionHumanId": z.optional(z.string()),
"text": z.string(),
"isRead": z.boolean(),
"createdAt": z.string()
    })