/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { packageRequirementKind2Schema } from "./packageRequirementKind2Schema";

export const packageRequirementSchema = z.object({
    "id": z.int(),
"correctionTypeId": z.int(),
get "kind"(){
                return packageRequirementKind2Schema
              },
"name": z.string(),
"isRequired": z.boolean(),
"responsibleCfoId": z.nullish(z.int()),
"namePattern": z.optional(z.string()),
"fileFormat": z.optional(z.string()),
"order": z.int()
    })