/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { packageRequirementKind2Schema } from "./packageRequirementKind2Schema";

export const packageRequirementInputSchema = z.object({
    get "kind"(){
                return packageRequirementKind2Schema
              },
"name": z.string(),
"isRequired": z.optional(z.boolean()),
"responsibleCfoId": z.nullish(z.int()),
"namePattern": z.optional(z.string()),
"fileFormat": z.optional(z.string()),
"order": z.optional(z.int())
    })