/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planListItemSchema } from "./planListItemSchema";

export const paginatedPlansSchema = z.object({
    get "items"(){
                return z.array(planListItemSchema)
              },
"total": z.int(),
"page": z.int(),
"pageSize": z.int()
    })