/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const planRemarkStatus2Schema = z.enum(["OPEN", "FIXED_BY_FILIAL", "REOPENED", "CLOSED"])