/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { cfoSchema } from "./cfoSchema";
import { planFileVersion2Schema } from "./planFileVersion2Schema";

export const planDocumentSlot2Schema = z.object({
    "id": z.int(),
"planId": z.int(),
"requirementId": z.nullable(z.int()),
"label": z.string(),
"isFilled": z.boolean(),
"isRequired": z.boolean(),
get "responsibleCfo"(){
                return z.union([cfoSchema, z.null()])
              },
get "currentVersion"(){
                return z.optional(z.union([planFileVersion2Schema, z.null()]))
              },
"choiceGroupKey": z.nullish(z.string()),
"groupLabel": z.nullish(z.string())
    })