/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { remarkStatus2Schema } from "./remarkStatus2Schema";

export const remarkSchema = z.object({
    "id": z.int(),
"humanId": z.string(),
"correctionId": z.int(),
"cfoId": z.nullish(z.int()),
"authorId": z.int(),
"createdAt": z.string(),
"relatedSlotId": z.nullish(z.int()),
"fileVersionId": z.nullish(z.int()),
"sheetName": z.string(),
"rowRef": z.string(),
"cellRef": z.string(),
"description": z.string(),
"requiredAction": z.string(),
get "status"(){
                return remarkStatus2Schema
              },
"closedById": z.nullish(z.int()),
"closedAt": z.nullish(z.string()),
"issuerLabel": z.string()
    })