/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { role2Schema } from "./role2Schema";

export const userSchema = z.object({
    "id": z.int(),
"username": z.string(),
"email": z.optional(z.string()),
"firstName": z.optional(z.string()),
"lastName": z.optional(z.string()),
"fullName": z.string(),
get "role"(){
                return role2Schema
              },
"filialId": z.nullish(z.int()),
"cfoId": z.nullish(z.int()),
"position": z.optional(z.string()),
"phone": z.optional(z.string()),
"isActive": z.boolean(),
"isLocked": z.boolean(),
"dateJoined": z.optional(z.string())
    })