/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { UpdateUserMutationRequest, UpdateUserMutationResponse, UpdateUserPathParams } from "../../types/usersController/UpdateUser";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { updateUser } from "../../clients/usersController/updateUser";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateUserMutationKey = () => [{ url: '/users/:id' }] as const

export type UpdateUserMutationKey = ReturnType<typeof updateUserMutationKey>

export function updateUserMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateUserMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateUserMutationKey()
        return mutationOptions<UpdateUserMutationResponse, ResponseErrorConfig<Error>, {id: UpdateUserPathParams["id"], data: UpdateUserMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return updateUser({ id, data }, config)
          },
        })

}

/**
 * @summary Обновить пользователя
 * {@link /users/:id}
 */
export function useUpdateUser<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateUserMutationResponse, ResponseErrorConfig<Error>, {id: UpdateUserPathParams["id"], data: UpdateUserMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateUserMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateUserMutationKey()

          const baseOptions = updateUserMutationOptions(config) as UseMutationOptions<UpdateUserMutationResponse, ResponseErrorConfig<Error>, {id: UpdateUserPathParams["id"], data: UpdateUserMutationRequest}, TContext>
          

          return useMutation<UpdateUserMutationResponse, ResponseErrorConfig<Error>, {id: UpdateUserPathParams["id"], data: UpdateUserMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateUserMutationResponse, ResponseErrorConfig<Error>, {id: UpdateUserPathParams["id"], data: UpdateUserMutationRequest}, TContext>
      
}