/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

/**
 * @description Уведомления помечены прочитанными
 */
export const markAllNotificationsRead200Schema = z.object({
    "updatedCount": z.int()
    })

export const markAllNotificationsReadMutationResponseSchema = z.lazy(() => markAllNotificationsRead200Schema)