/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const markNotificationsReadByPlanPathParamsSchema = z.object({
    "planId": z.int()
    })

/**
 * @description Уведомления помечены прочитанными
 */
export const markNotificationsReadByPlan200Schema = z.object({
    "updatedCount": z.int()
    })

export const markNotificationsReadByPlanMutationResponseSchema = z.lazy(() => markNotificationsReadByPlan200Schema)