/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { notification2Schema } from "../notification2Schema";

export const openNotificationPathParamsSchema = z.object({
    "id": z.int()
    })

/**
 * @description Уведомление прочитано
 */
export const openNotification200Schema = z.lazy(() => notification2Schema)

export const openNotificationMutationResponseSchema = z.lazy(() => openNotification200Schema)