/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanType } from "../PlanType";
import type { PlanTypeInput } from "../PlanTypeInput";

/**
 * @description Тип создан
*/
export type CreatePlanType201 = PlanType;

export type CreatePlanTypeMutationRequest = PlanTypeInput;

export type CreatePlanTypeMutationResponse = CreatePlanType201;

export type CreatePlanTypeMutation = {
    Response: CreatePlanType201;
    Request: CreatePlanTypeMutationRequest;
    Errors: any;
};