/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Cfo } from "../Cfo";
import type { CfoInput } from "../CfoInput";

/**
 * @description ЦФО создан
*/
export type CreateCfo201 = Cfo;

export type CreateCfoMutationRequest = CfoInput;

export type CreateCfoMutationResponse = CreateCfo201;

export type CreateCfoMutation = {
    Response: CreateCfo201;
    Request: CreateCfoMutationRequest;
    Errors: any;
};