/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FilialCfoLink } from "../FilialCfoLink";
import type { FilialCfoLinkInput } from "../FilialCfoLinkInput";

/**
 * @description Связь создана
*/
export type CreateFilialCfoLink201 = FilialCfoLink;

export type CreateFilialCfoLinkMutationRequest = FilialCfoLinkInput;

export type CreateFilialCfoLinkMutationResponse = CreateFilialCfoLink201;

export type CreateFilialCfoLinkMutation = {
    Response: CreateFilialCfoLink201;
    Request: CreateFilialCfoLinkMutationRequest;
    Errors: any;
};