/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface DeleteCfoPathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Удалено
*/
export type DeleteCfo204 = unknown;

export type DeleteCfoMutationResponse = DeleteCfo204;

export type DeleteCfoMutation = {
    Response: DeleteCfo204;
    PathParams: DeleteCfoPathParams;
    Errors: any;
};