/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface DeleteFilialCfoLinkPathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Удалено
*/
export type DeleteFilialCfoLink204 = unknown;

export type DeleteFilialCfoLinkMutationResponse = DeleteFilialCfoLink204;

export type DeleteFilialCfoLinkMutation = {
    Response: DeleteFilialCfoLink204;
    PathParams: DeleteFilialCfoLinkPathParams;
    Errors: any;
};