/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface DeletePackageRequirementPathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Удалено
*/
export type DeletePackageRequirement204 = unknown;

export type DeletePackageRequirementMutationResponse = DeletePackageRequirement204;

export type DeletePackageRequirementMutation = {
    Response: DeletePackageRequirement204;
    PathParams: DeletePackageRequirementPathParams;
    Errors: any;
};