/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface DeleteFilialPathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Удалено
*/
export type DeleteFilial204 = unknown;

export type DeleteFilialMutationResponse = DeleteFilial204;

export type DeleteFilialMutation = {
    Response: DeleteFilial204;
    PathParams: DeleteFilialPathParams;
    Errors: any;
};