/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Cfo } from "../Cfo";

export interface GetCfosQueryParams {
    /**
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @description Вернуть только ЦФО, привязанные к филиалу (для формы отправки на проверку)
     * @type integer | undefined
    */
    linkedToFilialId?: number;
}

/**
 * @description Список ЦФО
*/
export type GetCfos200 = Cfo[];

export type GetCfosQueryResponse = GetCfos200;

export type GetCfosQuery = {
    Response: GetCfos200;
    QueryParams: GetCfosQueryParams;
    Errors: any;
};