/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionType } from "../CorrectionType";

export interface GetCorrectionTypesQueryParams {
    /**
     * @type boolean | undefined
    */
    isActive?: boolean;
}

/**
 * @description Типы корректировок
*/
export type GetCorrectionTypes200 = CorrectionType[];

export type GetCorrectionTypesQueryResponse = GetCorrectionTypes200;

export type GetCorrectionTypesQuery = {
    Response: GetCorrectionTypes200;
    QueryParams: GetCorrectionTypesQueryParams;
    Errors: any;
};