/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FilialCfoLink } from "../FilialCfoLink";

export interface GetFilialCfoLinksQueryParams {
    /**
     * @type integer | undefined
    */
    filialId?: number;
    /**
     * @type integer | undefined
    */
    cfoId?: number;
}

/**
 * @description Связи Филиал <-> ЦФО
*/
export type GetFilialCfoLinks200 = FilialCfoLink[];

export type GetFilialCfoLinksQueryResponse = GetFilialCfoLinks200;

export type GetFilialCfoLinksQuery = {
    Response: GetFilialCfoLinks200;
    QueryParams: GetFilialCfoLinksQueryParams;
    Errors: any;
};