/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Cfo } from "../Cfo";
import type { CfoInput } from "../CfoInput";

export interface UpdateCfoPathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description ЦФО обновлён
*/
export type UpdateCfo200 = Cfo;

export type UpdateCfoMutationRequest = CfoInput;

export type UpdateCfoMutationResponse = UpdateCfo200;

export type UpdateCfoMutation = {
    Response: UpdateCfo200;
    Request: UpdateCfoMutationRequest;
    PathParams: UpdateCfoPathParams;
    Errors: any;
};