/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionType } from "../CorrectionType";
import type { CorrectionTypeInput } from "../CorrectionTypeInput";

export interface UpdateCorrectionTypePathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Тип обновлён
*/
export type UpdateCorrectionType200 = CorrectionType;

export type UpdateCorrectionTypeMutationRequest = CorrectionTypeInput;

export type UpdateCorrectionTypeMutationResponse = UpdateCorrectionType200;

export type UpdateCorrectionTypeMutation = {
    Response: UpdateCorrectionType200;
    Request: UpdateCorrectionTypeMutationRequest;
    PathParams: UpdateCorrectionTypePathParams;
    Errors: any;
};