/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Filial } from "../Filial";
import type { FilialInput } from "../FilialInput";

export interface UpdateFilialPathParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Филиал обновлён
*/
export type UpdateFilial200 = Filial;

export type UpdateFilialMutationRequest = FilialInput;

export type UpdateFilialMutationResponse = UpdateFilial200;

export type UpdateFilialMutation = {
    Response: UpdateFilial200;
    Request: UpdateFilialMutationRequest;
    PathParams: UpdateFilialPathParams;
    Errors: any;
};