/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const deleteUserPathParamsSchema = z.object({
    "id": z.int()
    })

/**
 * @description Удалено
 */
export const deleteUser204Schema = z.unknown()

export const deleteUserMutationResponseSchema = z.lazy(() => deleteUser204Schema)