/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { userSchema } from "../userSchema";
import { userUpdateInputSchema } from "../userUpdateInputSchema";

export const updateUserPathParamsSchema = z.object({
    "id": z.int()
    })

/**
 * @description Пользователь обновлён
 */
export const updateUser200Schema = z.lazy(() => userSchema)

export const updateUserMutationRequestSchema = z.lazy(() => userUpdateInputSchema)

export const updateUserMutationResponseSchema = z.lazy(() => updateUser200Schema)