/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { MarkNotificationsReadByFactPackageMutationResponse, MarkNotificationsReadByFactPackagePathParams } from "../../types/notificationsController/MarkNotificationsReadByFactPackage";
import { markNotificationsReadByFactPackageMutationResponseSchema } from "../../zod/notificationsController/markNotificationsReadByFactPackageSchema";

function getMarkNotificationsReadByFactPackageUrl({ factPackageId }: { factPackageId: MarkNotificationsReadByFactPackagePathParams["factPackageId"] }) {
  const res = { method: 'POST', url: `/notifications/by-fact-package/${factPackageId}/read` as const }
  return res
}

/**
 * @description Симметрично markNotificationsReadByCorrection, для карточки факт-пакета
 * (openspec/changes/fact-package-review). Идемпотентно.
 * @summary Отметить прочитанными все уведомления пользователя по одному факт-пакету
 * {@link /notifications/by-fact-package/:factPackageId/read}
 */
export async function markNotificationsReadByFactPackage({ factPackageId }: { factPackageId: MarkNotificationsReadByFactPackagePathParams["factPackageId"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarkNotificationsReadByFactPackageMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getMarkNotificationsReadByFactPackageUrl({ factPackageId }).url.toString(), ... requestConfig })
  return markNotificationsReadByFactPackageMutationResponseSchema.parse(res.data)
}