/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UploadFileVersion201, UploadFileVersionMutationRequest, UploadFileVersionMutationResponse, UploadFileVersionPathParams } from "../../types/correctionsController/UploadFileVersion";
import { createFileVersion2 } from "../createFileVersion2";
import { faker } from "@faker-js/faker";

export function createUploadFileVersionPathParams(data?: Partial<UploadFileVersionPathParams>): UploadFileVersionPathParams {

  return {
    ...{"humanId": faker.string.alpha(),"slotId": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Новая версия файла добавлена в ячейку
 */
export function createUploadFileVersion201(data?: Partial<UploadFileVersion201>): UploadFileVersion201 {

  return createFileVersion2(data)
}

export function createUploadFileVersionMutationRequest(data?: Partial<UploadFileVersionMutationRequest>): UploadFileVersionMutationRequest {

  return {
    ...{"file": faker.image.url() as unknown as Blob,"note": faker.string.alpha(),"remarkId": faker.number.int()},
    ...data || {}
  }
}

export function createUploadFileVersionMutationResponse(data?: Partial<UploadFileVersionMutationResponse>): UploadFileVersionMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUploadFileVersion201()])
}