/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteRemarkMutationResponse, DeleteRemarkPathParams } from "../../types/correctionsController/DeleteRemark";
import { faker } from "@faker-js/faker";

export function createDeleteRemarkPathParams(data?: Partial<DeleteRemarkPathParams>): DeleteRemarkPathParams {

  return {
    ...{"humanId": faker.string.alpha(),"remarkId": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Замечание удалено
 */
export function createDeleteRemark204() {

  return undefined
}

export function createDeleteRemarkMutationResponse(data?: Partial<DeleteRemarkMutationResponse>): DeleteRemarkMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeleteRemark204()])
}