/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DownloadFileVersion403, DownloadFileVersionPathParams, DownloadFileVersionQueryResponse } from "../../types/correctionsController/DownloadFileVersion";
import { createErrorResponse2 } from "../createErrorResponse2";
import { faker } from "@faker-js/faker";

export function createDownloadFileVersionPathParams(data?: Partial<DownloadFileVersionPathParams>): DownloadFileVersionPathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Бинарное содержимое файла
 */
export function createDownloadFileVersion200() {

  return faker.image.url() as unknown as Blob
}

/**
 * @description Нет доступа
 */
export function createDownloadFileVersion403(data?: Partial<DownloadFileVersion403>): DownloadFileVersion403 {

  return createErrorResponse2(data)
}

export function createDownloadFileVersionQueryResponse(data?: Partial<DownloadFileVersionQueryResponse>): DownloadFileVersionQueryResponse {

  return data || faker.helpers.arrayElement<any>([createDownloadFileVersion200()])
}