/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResubmitCorrection200, ResubmitCorrectionMutationRequest, ResubmitCorrectionMutationResponse, ResubmitCorrectionPathParams } from "../../types/correctionsController/ResubmitCorrection";
import { createCfoSelectionInput } from "../createCfoSelectionInput";
import { createCorrectionDetail } from "../createCorrectionDetail";
import { faker } from "@faker-js/faker";

export function createResubmitCorrectionPathParams(data?: Partial<ResubmitCorrectionPathParams>): ResubmitCorrectionPathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Повторно направлено
 */
export function createResubmitCorrection200(data?: Partial<ResubmitCorrection200>): ResubmitCorrection200 {

  return createCorrectionDetail(data)
}

export function createResubmitCorrectionMutationRequest(data?: Partial<ResubmitCorrectionMutationRequest>): ResubmitCorrectionMutationRequest {

  return createCfoSelectionInput(data)
}

export function createResubmitCorrectionMutationResponse(data?: Partial<ResubmitCorrectionMutationResponse>): ResubmitCorrectionMutationResponse {

  return data || faker.helpers.arrayElement<any>([createResubmitCorrection200()])
}