/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReturnCorrectionByCfo200, ReturnCorrectionByCfoMutationResponse, ReturnCorrectionByCfoPathParams } from "../../types/correctionsController/ReturnCorrectionByCfo";
import { createCorrectionDetail } from "../createCorrectionDetail";
import { faker } from "@faker-js/faker";

export function createReturnCorrectionByCfoPathParams(data?: Partial<ReturnCorrectionByCfoPathParams>): ReturnCorrectionByCfoPathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Возвращено на доработку
 */
export function createReturnCorrectionByCfo200(data?: Partial<ReturnCorrectionByCfo200>): ReturnCorrectionByCfo200 {

  return createCorrectionDetail(data)
}

export function createReturnCorrectionByCfoMutationResponse(data?: Partial<ReturnCorrectionByCfoMutationResponse>): ReturnCorrectionByCfoMutationResponse {

  return data || faker.helpers.arrayElement<any>([createReturnCorrectionByCfo200()])
}