/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CancelCfoDecision200, CancelCfoDecisionMutationResponse, CancelCfoDecisionPathParams } from "../../types/correctionsController/CancelCfoDecision";
import { createCorrectionDetail } from "../createCorrectionDetail";
import { faker } from "@faker-js/faker";

export function createCancelCfoDecisionPathParams(data?: Partial<CancelCfoDecisionPathParams>): CancelCfoDecisionPathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Решение ЦФО отменено, статус возвращён в PENDING
 */
export function createCancelCfoDecision200(data?: Partial<CancelCfoDecision200>): CancelCfoDecision200 {

  return createCorrectionDetail(data)
}

export function createCancelCfoDecisionMutationResponse(data?: Partial<CancelCfoDecisionMutationResponse>): CancelCfoDecisionMutationResponse {

  return data || faker.helpers.arrayElement<any>([createCancelCfoDecision200()])
}