/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetCorrections200, GetCorrectionsQueryParams, GetCorrectionsQueryResponse } from "../../types/correctionsController/GetCorrections";
import { createCorrectionStatus2 } from "../createCorrectionStatus2";
import { createPaginatedCorrections } from "../createPaginatedCorrections";
import { faker } from "@faker-js/faker";

export function createGetCorrectionsQueryParams(data?: Partial<GetCorrectionsQueryParams>): GetCorrectionsQueryParams {

  return { ...{get "status"() { return createCorrectionStatus2() },"filialId": faker.number.int(),"cfoId": faker.number.int(),"correctionTypeId": faker.number.int(),"q": faker.string.alpha(),"onlyWithRemarks": faker.datatype.boolean(),"page": faker.number.int(),"pageSize": faker.number.int(),...(data || {})} }
}

/**
 * @description Страница корректировок
 */
export function createGetCorrections200(data?: Partial<GetCorrections200>): GetCorrections200 {

  return createPaginatedCorrections(data)
}

export function createGetCorrectionsQueryResponse(data?: Partial<GetCorrectionsQueryResponse>): GetCorrectionsQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetCorrections200()])
}