/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApproveCorrectionByCfo200, ApproveCorrectionByCfoMutationResponse, ApproveCorrectionByCfoPathParams } from "../../types/correctionsController/ApproveCorrectionByCfo";
import { createCorrectionDetail } from "../createCorrectionDetail";
import { faker } from "@faker-js/faker";

export function createApproveCorrectionByCfoPathParams(data?: Partial<ApproveCorrectionByCfoPathParams>): ApproveCorrectionByCfoPathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Согласовано
 */
export function createApproveCorrectionByCfo200(data?: Partial<ApproveCorrectionByCfo200>): ApproveCorrectionByCfo200 {

  return createCorrectionDetail(data)
}

export function createApproveCorrectionByCfoMutationResponse(data?: Partial<ApproveCorrectionByCfoMutationResponse>): ApproveCorrectionByCfoMutationResponse {

  return data || faker.helpers.arrayElement<any>([createApproveCorrectionByCfo200()])
}