/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	LeaveRemark200,
	LeaveRemarkMutationRequest,
	LeaveRemarkMutationResponse,
	LeaveRemarkPathParams,
} from '../../types/correctionsController/LeaveRemark'

import { faker } from '@faker-js/faker'

import { createCorrectionDetail } from '../createCorrectionDetail'
import { createRemarkCreateInput } from '../createRemarkCreateInput'

export function createLeaveRemarkPathParams(
	data?: Partial<LeaveRemarkPathParams>,
): LeaveRemarkPathParams {
	return {
		...{ humanId: faker.string.alpha() },
		...(data || {}),
	}
}

/** Замечание создано */
export function createLeaveRemark200(data?: Partial<LeaveRemark200>): LeaveRemark200 {
	return createCorrectionDetail(data)
}

export function createLeaveRemarkMutationRequest(
	data?: Partial<LeaveRemarkMutationRequest>,
): LeaveRemarkMutationRequest {
	return createRemarkCreateInput(data)
}

export function createLeaveRemarkMutationResponse(
	data?: Partial<LeaveRemarkMutationResponse>,
): LeaveRemarkMutationResponse {
	return data || faker.helpers.arrayElement<any>([createLeaveRemark200()])
}
