/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetCorrection200, GetCorrection403, GetCorrection404, GetCorrectionPathParams, GetCorrectionQueryResponse } from "../../types/correctionsController/GetCorrection";
import { createCorrectionDetail } from "../createCorrectionDetail";
import { createErrorResponse2 } from "../createErrorResponse2";
import { faker } from "@faker-js/faker";

export function createGetCorrectionPathParams(data?: Partial<GetCorrectionPathParams>): GetCorrectionPathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Детальная карточка корректировки
 */
export function createGetCorrection200(data?: Partial<GetCorrection200>): GetCorrection200 {

  return createCorrectionDetail(data)
}

/**
 * @description Нет доступа к этой корректировке
 */
export function createGetCorrection403(data?: Partial<GetCorrection403>): GetCorrection403 {

  return createErrorResponse2(data)
}

/**
 * @description Не найдено
 */
export function createGetCorrection404(data?: Partial<GetCorrection404>): GetCorrection404 {

  return createErrorResponse2(data)
}

export function createGetCorrectionQueryResponse(data?: Partial<GetCorrectionQueryResponse>): GetCorrectionQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetCorrection200()])
}