/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResubmitCorrectionToDtoe200, ResubmitCorrectionToDtoeMutationResponse, ResubmitCorrectionToDtoePathParams } from "../../types/correctionsController/ResubmitCorrectionToDtoe";
import { createCorrectionDetail } from "../createCorrectionDetail";
import { faker } from "@faker-js/faker";

export function createResubmitCorrectionToDtoePathParams(data?: Partial<ResubmitCorrectionToDtoePathParams>): ResubmitCorrectionToDtoePathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Повторно направлено в ДТОиР
 */
export function createResubmitCorrectionToDtoe200(data?: Partial<ResubmitCorrectionToDtoe200>): ResubmitCorrectionToDtoe200 {

  return createCorrectionDetail(data)
}

export function createResubmitCorrectionToDtoeMutationResponse(data?: Partial<ResubmitCorrectionToDtoeMutationResponse>): ResubmitCorrectionToDtoeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createResubmitCorrectionToDtoe200()])
}