/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateCorrection201, CreateCorrectionMutationRequest, CreateCorrectionMutationResponse } from "../../types/correctionsController/CreateCorrection";
import { createCorrectionCreateInput } from "../createCorrectionCreateInput";
import { createCorrectionDetail } from "../createCorrectionDetail";
import { faker } from "@faker-js/faker";

/**
 * @description Корректировка создана
 */
export function createCreateCorrection201(data?: Partial<CreateCorrection201>): CreateCorrection201 {

  return createCorrectionDetail(data)
}

export function createCreateCorrectionMutationRequest(data?: Partial<CreateCorrectionMutationRequest>): CreateCorrectionMutationRequest {

  return createCorrectionCreateInput(data)
}

export function createCreateCorrectionMutationResponse(data?: Partial<CreateCorrectionMutationResponse>): CreateCorrectionMutationResponse {

  return data || faker.helpers.arrayElement<any>([createCreateCorrection201()])
}