/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetCorrectionStatsCfo200, GetCorrectionStatsCfo403, GetCorrectionStatsCfoQueryResponse } from "../../types/correctionsController/GetCorrectionStatsCfo";
import { createCorrectionStats2 } from "../createCorrectionStats2";
import { createErrorResponse2 } from "../createErrorResponse2";
import { faker } from "@faker-js/faker";

/**
 * @description Агрегированные счётчики в рамках видимости роли CFO
 */
export function createGetCorrectionStatsCfo200(data?: Partial<GetCorrectionStatsCfo200>): GetCorrectionStatsCfo200 {

  return createCorrectionStats2(data)
}

/**
 * @description У пользователя не роль CFO
 */
export function createGetCorrectionStatsCfo403(data?: Partial<GetCorrectionStatsCfo403>): GetCorrectionStatsCfo403 {

  return createErrorResponse2(data)
}

export function createGetCorrectionStatsCfoQueryResponse(data?: Partial<GetCorrectionStatsCfoQueryResponse>): GetCorrectionStatsCfoQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetCorrectionStatsCfo200()])
}