/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChangeCorrectionType200, ChangeCorrectionType400, ChangeCorrectionType403, ChangeCorrectionType404, ChangeCorrectionTypeMutationRequest, ChangeCorrectionTypeMutationResponse, ChangeCorrectionTypePathParams } from "../../types/correctionsController/ChangeCorrectionType";
import { createCorrectionDetail } from "../createCorrectionDetail";
import { createCorrectionTypeChangeInput } from "../createCorrectionTypeChangeInput";
import { createErrorResponse2 } from "../createErrorResponse2";
import { faker } from "@faker-js/faker";

export function createChangeCorrectionTypePathParams(data?: Partial<ChangeCorrectionTypePathParams>): ChangeCorrectionTypePathParams {

  return {
    ...{"humanId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Тип изменён
 */
export function createChangeCorrectionType200(data?: Partial<ChangeCorrectionType200>): ChangeCorrectionType200 {

  return createCorrectionDetail(data)
}

/**
 * @description Корректировка не в статусе «Черновик»
 */
export function createChangeCorrectionType400(data?: Partial<ChangeCorrectionType400>): ChangeCorrectionType400 {

  return createErrorResponse2(data)
}

/**
 * @description Нет доступа (не автор/не владелец филиала)
 */
export function createChangeCorrectionType403(data?: Partial<ChangeCorrectionType403>): ChangeCorrectionType403 {

  return createErrorResponse2(data)
}

/**
 * @description Корректировка или тип корректировки не найдены
 */
export function createChangeCorrectionType404(data?: Partial<ChangeCorrectionType404>): ChangeCorrectionType404 {

  return createErrorResponse2(data)
}

export function createChangeCorrectionTypeMutationRequest(data?: Partial<ChangeCorrectionTypeMutationRequest>): ChangeCorrectionTypeMutationRequest {

  return createCorrectionTypeChangeInput(data)
}

export function createChangeCorrectionTypeMutationResponse(data?: Partial<ChangeCorrectionTypeMutationResponse>): ChangeCorrectionTypeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createChangeCorrectionType200()])
}