/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetCorrectionStatsDtoe200, GetCorrectionStatsDtoe403, GetCorrectionStatsDtoeQueryResponse } from "../../types/correctionsController/GetCorrectionStatsDtoe";
import { createCorrectionStats2 } from "../createCorrectionStats2";
import { createErrorResponse2 } from "../createErrorResponse2";
import { faker } from "@faker-js/faker";

/**
 * @description Агрегированные счётчики в рамках видимости роли DTOE
 */
export function createGetCorrectionStatsDtoe200(data?: Partial<GetCorrectionStatsDtoe200>): GetCorrectionStatsDtoe200 {

  return createCorrectionStats2(data)
}

/**
 * @description У пользователя не роль DTOE
 */
export function createGetCorrectionStatsDtoe403(data?: Partial<GetCorrectionStatsDtoe403>): GetCorrectionStatsDtoe403 {

  return createErrorResponse2(data)
}

export function createGetCorrectionStatsDtoeQueryResponse(data?: Partial<GetCorrectionStatsDtoeQueryResponse>): GetCorrectionStatsDtoeQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetCorrectionStatsDtoe200()])
}