/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReopenRemark200, ReopenRemarkMutationRequest, ReopenRemarkMutationResponse, ReopenRemarkPathParams } from "../../types/correctionsController/ReopenRemark";
import { createRemark } from "../createRemark";
import { createRemarkReopenInput } from "../createRemarkReopenInput";
import { faker } from "@faker-js/faker";

export function createReopenRemarkPathParams(data?: Partial<ReopenRemarkPathParams>): ReopenRemarkPathParams {

  return {
    ...{"humanId": faker.string.alpha(),"remarkId": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Замечание переоткрыто
 */
export function createReopenRemark200(data?: Partial<ReopenRemark200>): ReopenRemark200 {

  return createRemark(data)
}

export function createReopenRemarkMutationRequest(data?: Partial<ReopenRemarkMutationRequest>): ReopenRemarkMutationRequest {

  return createRemarkReopenInput(data)
}

export function createReopenRemarkMutationResponse(data?: Partial<ReopenRemarkMutationResponse>): ReopenRemarkMutationResponse {

  return data || faker.helpers.arrayElement<any>([createReopenRemark200()])
}