/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { planDetailSchema } from "../planDetailSchema";
import { planTypeChangeInputSchema } from "../planTypeChangeInputSchema";

export const changePlanTypePathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Тип изменён
 */
export const changePlanType200Schema = z.lazy(() => planDetailSchema)

/**
 * @description План не в статусе «Черновик»
 */
export const changePlanType400Schema = z.lazy(() => errorResponse2Schema)

/**
 * @description Нет доступа (не автор/не владелец филиала)
 */
export const changePlanType403Schema = z.lazy(() => errorResponse2Schema)

/**
 * @description План или тип плана не найдены
 */
export const changePlanType404Schema = z.lazy(() => errorResponse2Schema)

export const changePlanTypeMutationRequestSchema = z.lazy(() => planTypeChangeInputSchema)

export const changePlanTypeMutationResponseSchema = z.lazy(() => changePlanType200Schema)