/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planCreateInputSchema } from "../planCreateInputSchema";
import { planDetailSchema } from "../planDetailSchema";

/**
 * @description План создан
 */
export const createPlan201Schema = z.lazy(() => planDetailSchema)

export const createPlanMutationRequestSchema = z.lazy(() => planCreateInputSchema)

export const createPlanMutationResponseSchema = z.lazy(() => createPlan201Schema)