/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const deletePlanRemarkPathParamsSchema = z.object({
    "humanId": z.string(),
"remarkId": z.int()
    })

/**
 * @description Замечание удалено
 */
export const deletePlanRemark204Schema = z.unknown()

export const deletePlanRemarkMutationResponseSchema = z.lazy(() => deletePlanRemark204Schema)