/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";

export const deletePlanPathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description План удалён
 */
export const deletePlan204Schema = z.unknown()

/**
 * @description План не в статусе «Черновик»
 */
export const deletePlan400Schema = z.lazy(() => errorResponse2Schema)

/**
 * @description Нет доступа (не автор/не владелец филиала)
 */
export const deletePlan403Schema = z.lazy(() => errorResponse2Schema)

/**
 * @description Не найдено
 */
export const deletePlan404Schema = z.lazy(() => errorResponse2Schema)

export const deletePlanMutationResponseSchema = z.lazy(() => deletePlan204Schema)