/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";

export const downloadPlanFileVersionPathParamsSchema = z.object({
    "id": z.int()
    })

/**
 * @description Бинарное содержимое файла
 */
export const downloadPlanFileVersion200Schema = z.instanceof(File)

/**
 * @description Нет доступа
 */
export const downloadPlanFileVersion403Schema = z.lazy(() => errorResponse2Schema)

export const downloadPlanFileVersionQueryResponseSchema = z.lazy(() => downloadPlanFileVersion200Schema)