/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planStats2Schema } from "../planStats2Schema";

/**
 * @description Агрегированные счётчики для карточек дашборда (в рамках видимости роли)
 */
export const getPlanStats200Schema = z.lazy(() => planStats2Schema)

export const getPlanStatsQueryResponseSchema = z.lazy(() => getPlanStats200Schema)