/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { paginatedPlansSchema } from "../paginatedPlansSchema";
import { planStatus2Schema } from "../planStatus2Schema";

export const getPlansQueryParamsSchema = z.object({
    get "status"(){
                return z.optional(planStatus2Schema)
              },
"filialId": z.optional(z.int()),
"cfoId": z.optional(z.int()),
"planTypeId": z.optional(z.int()),
"q": z.optional(z.string()),
"onlyWithRemarks": z.optional(z.boolean()),
"page": z.int(),
"pageSize": z.int()
    })

/**
 * @description Страница планов
 */
export const getPlans200Schema = z.lazy(() => paginatedPlansSchema)

export const getPlansQueryResponseSchema = z.lazy(() => getPlans200Schema)