/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { planStats2Schema } from "../planStats2Schema";

/**
 * @description Агрегированные счётчики в рамках видимости роли CFO
 */
export const getPlanStatsCfo200Schema = z.lazy(() => planStats2Schema)

/**
 * @description У пользователя не роль CFO
 */
export const getPlanStatsCfo403Schema = z.lazy(() => errorResponse2Schema)

export const getPlanStatsCfoQueryResponseSchema = z.lazy(() => getPlanStatsCfo200Schema)