/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planRemarkReopenInputSchema } from "../planRemarkReopenInputSchema";
import { planRemarkSchema } from "../planRemarkSchema";

export const reopenPlanRemarkPathParamsSchema = z.object({
    "humanId": z.string(),
"remarkId": z.int()
    })

/**
 * @description Замечание переоткрыто
 */
export const reopenPlanRemark200Schema = z.lazy(() => planRemarkSchema)

export const reopenPlanRemarkMutationRequestSchema = z.lazy(() => planRemarkReopenInputSchema)

export const reopenPlanRemarkMutationResponseSchema = z.lazy(() => reopenPlanRemark200Schema)