/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planDetailSchema } from "../planDetailSchema";

export const resubmitPlanToDtoePathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Повторно направлено в ДТОиР
 */
export const resubmitPlanToDtoe200Schema = z.lazy(() => planDetailSchema)

export const resubmitPlanToDtoeMutationResponseSchema = z.lazy(() => resubmitPlanToDtoe200Schema)