/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planCfoSelectionInputSchema } from "../planCfoSelectionInputSchema";
import { planDetailSchema } from "../planDetailSchema";

export const resubmitPlanPathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Повторно направлено
 */
export const resubmitPlan200Schema = z.lazy(() => planDetailSchema)

export const resubmitPlanMutationRequestSchema = z.lazy(() => planCfoSelectionInputSchema)

export const resubmitPlanMutationResponseSchema = z.lazy(() => resubmitPlan200Schema)