/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planDetailSchema } from "../planDetailSchema";

export const returnPlanByDtoePathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Возвращено ДТОиР на доработку
 */
export const returnPlanByDtoe200Schema = z.lazy(() => planDetailSchema)

export const returnPlanByDtoeMutationResponseSchema = z.lazy(() => returnPlanByDtoe200Schema)