/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { planDetailSchema } from "../planDetailSchema";

export const sendPlanToDtoePathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Отправлено в ДТОиР
 */
export const sendPlanToDtoe200Schema = z.lazy(() => planDetailSchema)

/**
 * @description Не все обязательные ЦФО согласовали пакет
 */
export const sendPlanToDtoe400Schema = z.lazy(() => errorResponse2Schema)

export const sendPlanToDtoeMutationResponseSchema = z.lazy(() => sendPlanToDtoe200Schema)