/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { planCfoSelectionInputSchema } from "../planCfoSelectionInputSchema";
import { planDetailSchema } from "../planDetailSchema";

export const sendPlanPathParamsSchema = z.object({
    "humanId": z.string()
    })

/**
 * @description Направлено
 */
export const sendPlan200Schema = z.lazy(() => planDetailSchema)

/**
 * @description Пакет не укомплектован либо ЦФО не выбраны/не привязаны
 */
export const sendPlan400Schema = z.lazy(() => errorResponse2Schema)

export const sendPlanMutationRequestSchema = z.lazy(() => planCfoSelectionInputSchema)

export const sendPlanMutationResponseSchema = z.lazy(() => sendPlan200Schema)