/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planFileVersion2Schema } from "../planFileVersion2Schema";

export const uploadPlanFileVersionPathParamsSchema = z.object({
    "humanId": z.string(),
"slotId": z.int()
    })

/**
 * @description Новая версия файла добавлена в ячейку
 */
export const uploadPlanFileVersion201Schema = z.lazy(() => planFileVersion2Schema)

export const uploadPlanFileVersionMutationRequestSchema = z.object({
    "file": z.instanceof(File),
"note": z.optional(z.string()),
"remarkId": z.optional(z.int())
    })

export const uploadPlanFileVersionMutationResponseSchema = z.lazy(() => uploadPlanFileVersion201Schema)