/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetMeQueryResponse, GetMe401 } from "../../types/authController/GetMe";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getMe } from "../../clients/authController/getMe";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMeSuspenseQueryKey = () => [{ url: '/auth/me' }] as const

export type GetMeSuspenseQueryKey = ReturnType<typeof getMeSuspenseQueryKey>

export function getMeSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getMeSuspenseQueryKey()
        return queryOptions<GetMeQueryResponse, ResponseErrorConfig<GetMe401>, GetMeQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getMe({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Текущий авторизованный пользователь
 * {@link /auth/me}
 */
export function useGetMeSuspense<TData = GetMeQueryResponse, TQueryKey extends QueryKey = GetMeSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetMeQueryResponse, ResponseErrorConfig<GetMe401>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getMeSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getMeSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetMe401>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}