/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { LoginMutationRequest, LoginMutationResponse, Login401 } from "../../types/authController/Login";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { login } from "../../clients/authController/login";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const loginMutationKey = () => [{ url: '/auth/login' }] as const

export type LoginMutationKey = ReturnType<typeof loginMutationKey>

export function loginMutationOptions<TContext = unknown>(config: Partial<RequestConfig<LoginMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = loginMutationKey()
        return mutationOptions<LoginMutationResponse, ResponseErrorConfig<Login401>, {data: LoginMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return login({ data }, config)
          },
        })

}

/**
 * @summary Вход по логину и паролю
 * {@link /auth/login}
 */
export function useLogin<TContext>(options: 
{
  mutation?: UseMutationOptions<LoginMutationResponse, ResponseErrorConfig<Login401>, {data: LoginMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<LoginMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? loginMutationKey()

          const baseOptions = loginMutationOptions(config) as UseMutationOptions<LoginMutationResponse, ResponseErrorConfig<Login401>, {data: LoginMutationRequest}, TContext>
          

          return useMutation<LoginMutationResponse, ResponseErrorConfig<Login401>, {data: LoginMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<LoginMutationResponse, ResponseErrorConfig<Login401>, {data: LoginMutationRequest}, TContext>
      
}