/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarkNotificationsReadByFactPackage200, MarkNotificationsReadByFactPackageMutationResponse, MarkNotificationsReadByFactPackagePathParams } from "../../types/notificationsController/MarkNotificationsReadByFactPackage";
import { faker } from "@faker-js/faker";

export function createMarkNotificationsReadByFactPackagePathParams(data?: Partial<MarkNotificationsReadByFactPackagePathParams>): MarkNotificationsReadByFactPackagePathParams {

  return {
    ...{"factPackageId": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Уведомления помечены прочитанными
 */
export function createMarkNotificationsReadByFactPackage200(data?: Partial<MarkNotificationsReadByFactPackage200>): MarkNotificationsReadByFactPackage200 {

  return {
    ...{"updatedCount": faker.number.int()},
    ...data || {}
  }
}

export function createMarkNotificationsReadByFactPackageMutationResponse(data?: Partial<MarkNotificationsReadByFactPackageMutationResponse>): MarkNotificationsReadByFactPackageMutationResponse {

  return data || faker.helpers.arrayElement<any>([createMarkNotificationsReadByFactPackage200()])
}