/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarkAllNotificationsRead200, MarkAllNotificationsReadMutationResponse } from "../../types/notificationsController/MarkAllNotificationsRead";
import { faker } from "@faker-js/faker";

/**
 * @description Уведомления помечены прочитанными
 */
export function createMarkAllNotificationsRead200(data?: Partial<MarkAllNotificationsRead200>): MarkAllNotificationsRead200 {

  return {
    ...{"updatedCount": faker.number.int()},
    ...data || {}
  }
}

export function createMarkAllNotificationsReadMutationResponse(data?: Partial<MarkAllNotificationsReadMutationResponse>): MarkAllNotificationsReadMutationResponse {

  return data || faker.helpers.arrayElement<any>([createMarkAllNotificationsRead200()])
}