/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarkNotificationsReadByCorrection200, MarkNotificationsReadByCorrectionMutationResponse, MarkNotificationsReadByCorrectionPathParams } from "../../types/notificationsController/MarkNotificationsReadByCorrection";
import { faker } from "@faker-js/faker";

export function createMarkNotificationsReadByCorrectionPathParams(data?: Partial<MarkNotificationsReadByCorrectionPathParams>): MarkNotificationsReadByCorrectionPathParams {

  return {
    ...{"correctionId": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Уведомления помечены прочитанными
 */
export function createMarkNotificationsReadByCorrection200(data?: Partial<MarkNotificationsReadByCorrection200>): MarkNotificationsReadByCorrection200 {

  return {
    ...{"updatedCount": faker.number.int()},
    ...data || {}
  }
}

export function createMarkNotificationsReadByCorrectionMutationResponse(data?: Partial<MarkNotificationsReadByCorrectionMutationResponse>): MarkNotificationsReadByCorrectionMutationResponse {

  return data || faker.helpers.arrayElement<any>([createMarkNotificationsReadByCorrection200()])
}