/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MarkNotificationsReadByPlan200, MarkNotificationsReadByPlanMutationResponse, MarkNotificationsReadByPlanPathParams } from "../../types/notificationsController/MarkNotificationsReadByPlan";
import { faker } from "@faker-js/faker";

export function createMarkNotificationsReadByPlanPathParams(data?: Partial<MarkNotificationsReadByPlanPathParams>): MarkNotificationsReadByPlanPathParams {

  return {
    ...{"planId": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Уведомления помечены прочитанными
 */
export function createMarkNotificationsReadByPlan200(data?: Partial<MarkNotificationsReadByPlan200>): MarkNotificationsReadByPlan200 {

  return {
    ...{"updatedCount": faker.number.int()},
    ...data || {}
  }
}

export function createMarkNotificationsReadByPlanMutationResponse(data?: Partial<MarkNotificationsReadByPlanMutationResponse>): MarkNotificationsReadByPlanMutationResponse {

  return data || faker.helpers.arrayElement<any>([createMarkNotificationsReadByPlan200()])
}