/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactPackageSubmitInput } from "../types/FactPackageSubmitInput";
import { faker } from "@faker-js/faker";

/**
 * @description Для пакета, созданного Филиалом, cfoIds обязателен (кому направить на проверку). Для пакета, созданного ЦФО, cfoIds не нужен — пакет уходит сразу в ДТОиР.\n
 */
export function createFactPackageSubmitInput(data?: Partial<FactPackageSubmitInput>): FactPackageSubmitInput {

  return {
    ...{"cfoIds": faker.helpers.multiple(() => (faker.number.int()))},
    ...data || {}
  }
}