/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactFormCode } from "../types/FactFormCode";
import { faker } from "@faker-js/faker";

export function createFactFormCode(data?: Partial<FactFormCode>): FactFormCode {

  return data || faker.helpers.arrayElement<FactFormCode>(["ACT_WORK", "ACT_SERVICE", "KS2", "KS3", "ACT_MATERIALS", "INVOICE", "PAYMENT_REQUEST"])
}