/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionCreateInput } from "../types/CorrectionCreateInput";
import { faker } from "@faker-js/faker";

export function createCorrectionCreateInput(data?: Partial<CorrectionCreateInput>): CorrectionCreateInput {

  return {
    ...{"correctionTypeId": faker.number.int()},
    ...data || {}
  }
}