/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanRemarkReopenInput } from "../types/PlanRemarkReopenInput";
import { faker } from "@faker-js/faker";

export function createPlanRemarkReopenInput(data?: Partial<PlanRemarkReopenInput>): PlanRemarkReopenInput {

  return {
    ...{"description": faker.string.alpha(),"requiredAction": faker.string.alpha()},
    ...data || {}
  }
}