/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionHistoryEntry2 } from "../types/CorrectionHistoryEntry2";
import { faker } from "@faker-js/faker";

export function createCorrectionHistoryEntry2(data?: Partial<CorrectionHistoryEntry2>): CorrectionHistoryEntry2 {

  return {
    ...{"id": faker.number.int(),"correctionId": faker.number.int(),"timestamp": faker.date.anytime().toISOString(),"userId": faker.number.int(),"text": faker.string.alpha()},
    ...data || {}
  }
}