/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactPackageCreateInput } from "../types/FactPackageCreateInput";
import { createDirection2 } from "./createDirection2";

export function createFactPackageCreateInput(data?: Partial<FactPackageCreateInput>): FactPackageCreateInput {

  return { ...{get "direction"() { return createDirection2() },...(data || {})} }
}