/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Cfo } from "../types/Cfo";
import { faker } from "@faker-js/faker";

export function createCfo(data?: Partial<Cfo>): Cfo {

  return {
    ...{"id": faker.number.int(),"code": faker.string.alpha(),"name": faker.string.alpha(),"isActive": faker.datatype.boolean()},
    ...data || {}
  }
}