/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RemarkStatus2 } from "../types/RemarkStatus2";
import { faker } from "@faker-js/faker";

export function createRemarkStatus2(data?: Partial<RemarkStatus2>): RemarkStatus2 {

  return data || faker.helpers.arrayElement<RemarkStatus2>(["OPEN", "FIXED_BY_FILIAL", "REOPENED", "CLOSED"])
}