/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionStats } from "../types/CorrectionStats";
import { faker } from "@faker-js/faker";

export function createCorrectionStats(data?: Partial<CorrectionStats>): CorrectionStats {

  return {
    ...{"total": faker.number.int(),"inReview": faker.number.int(),"returned": faker.number.int(),"approved": faker.number.int(),"underReview": faker.number.int(),"openRemarks": faker.number.int()},
    ...data || {}
  }
}