/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactFinalDecisionInput } from "../types/FactFinalDecisionInput";
import { faker } from "@faker-js/faker";

export function createFactFinalDecisionInput(data?: Partial<FactFinalDecisionInput>): FactFinalDecisionInput {

  return {
    ...{"decision": faker.helpers.arrayElement<NonNullable<FactFinalDecisionInput>["decision"]>(["APPROVE", "RETURN"])},
    ...data || {}
  }
}