/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionTypeInput } from "../types/CorrectionTypeInput";
import { faker } from "@faker-js/faker";

export function createCorrectionTypeInput(data?: Partial<CorrectionTypeInput>): CorrectionTypeInput {

  return {
    ...{"code": faker.string.alpha(),"name": faker.string.alpha(),"description": faker.string.alpha(),"isActive": faker.datatype.boolean()},
    ...data || {}
  }
}