/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FilialCfoLinkInput } from "../types/FilialCfoLinkInput";
import { faker } from "@faker-js/faker";

export function createFilialCfoLinkInput(data?: Partial<FilialCfoLinkInput>): FilialCfoLinkInput {

  return {
    ...{"filialId": faker.number.int(),"cfoId": faker.number.int(),"isActive": faker.datatype.boolean()},
    ...data || {}
  }
}