/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanRemarkCreateInput } from "../types/PlanRemarkCreateInput";
import { faker } from "@faker-js/faker";

export function createPlanRemarkCreateInput(data?: Partial<PlanRemarkCreateInput>): PlanRemarkCreateInput {

  return {
    ...{"description": faker.string.alpha(),"requiredAction": faker.string.alpha(),"sheetName": faker.string.alpha(),"rowRef": faker.string.alpha(),"cellRef": faker.string.alpha(),"relatedSlotId": faker.number.int(),"fileVersionId": faker.number.int()},
    ...data || {}
  }
}