/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PackageRequirementKind2 } from "../types/PackageRequirementKind2";
import { faker } from "@faker-js/faker";

export function createPackageRequirementKind2(data?: Partial<PackageRequirementKind2>): PackageRequirementKind2 {

  return data || faker.helpers.arrayElement<PackageRequirementKind2>(["MAIN_EXCEL", "EXCEL_SHEET", "DOCUMENT"])
}