/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RemarkCreateInput } from "../types/RemarkCreateInput";
import { faker } from "@faker-js/faker";

export function createRemarkCreateInput(data?: Partial<RemarkCreateInput>): RemarkCreateInput {

  return {
    ...{"description": faker.string.alpha(),"requiredAction": faker.string.alpha(),"sheetName": faker.string.alpha(),"rowRef": faker.string.alpha(),"cellRef": faker.string.alpha(),"relatedSlotId": faker.number.int(),"fileVersionId": faker.number.int()},
    ...data || {}
  }
}