/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanListItem } from "../types/PlanListItem";
import { createFilial } from "./createFilial";
import { createPlan } from "./createPlan";
import { createPlanCfoStatusValue2 } from "./createPlanCfoStatusValue2";
import { createPlanType } from "./createPlanType";
import { createUserSummary } from "./createUserSummary";
import { faker } from "@faker-js/faker";

export function createPlanListItem(data?: Partial<PlanListItem>): PlanListItem {

  return {
    ...{...createPlan(), ...{get "filial"() { return createFilial() },get "planType"() { return createPlanType() },get "author"() { return createUserSummary() },get "myCfoStatus"() { return faker.helpers.arrayElement<any>([createPlanCfoStatusValue2(), null]) }}},
    ...data || {}
  }
}