/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanStats } from "../types/PlanStats";
import { faker } from "@faker-js/faker";

export function createPlanStats(data?: Partial<PlanStats>): PlanStats {

  return {
    ...{"total": faker.number.int(),"inReview": faker.number.int(),"returned": faker.number.int(),"approved": faker.number.int(),"underReview": faker.number.int(),"openRemarks": faker.number.int()},
    ...data || {}
  }
}