/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactForm } from "../types/FactForm";
import { createFactFormCode2 } from "./createFactFormCode2";
import { createFactFormVersion2 } from "./createFactFormVersion2";
import { faker } from "@faker-js/faker";

export function createFactForm(data?: Partial<FactForm>): FactForm {

  return { ...{"id": faker.number.int(),"factPackageId": faker.number.int(),get "code"() { return createFactFormCode2() },"label": faker.string.alpha(),"isFilled": faker.datatype.boolean(),get "currentVersion"() { return faker.helpers.arrayElement<any>([createFactFormVersion2(), null]) },get "versions"() { return faker.helpers.multiple(() => (createFactFormVersion2())) },...(data || {})} }
}