/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanDocumentSlot } from "../types/PlanDocumentSlot";
import { createCfo } from "./createCfo";
import { createPlanFileVersion2 } from "./createPlanFileVersion2";
import { faker } from "@faker-js/faker";

export function createPlanDocumentSlot(data?: Partial<PlanDocumentSlot>): PlanDocumentSlot {

  return { ...{"id": faker.number.int(),"planId": faker.number.int(),"requirementId": faker.number.int(),"label": faker.string.alpha(),"isFilled": faker.datatype.boolean(),"isRequired": faker.datatype.boolean(),get "responsibleCfo"() { return faker.helpers.arrayElement<any>([createCfo(), null]) },get "currentVersion"() { return faker.helpers.arrayElement<any>([createPlanFileVersion2(), null]) },"choiceGroupKey": faker.string.alpha(),"groupLabel": faker.string.alpha(),...(data || {})} }
}