/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CfoStatusValue } from "../types/CfoStatusValue";
import { faker } from "@faker-js/faker";

export function createCfoStatusValue(data?: Partial<CfoStatusValue>): CfoStatusValue {

  return data || faker.helpers.arrayElement<CfoStatusValue>(["PENDING", "APPROVED", "RETURNED"])
}