/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Plan } from "../types/Plan";
import { createPlanStatus2 } from "./createPlanStatus2";
import { faker } from "@faker-js/faker";

export function createPlan(data?: Partial<Plan>): Plan {

  return { ...{"id": faker.number.int(),"humanId": faker.string.alpha(),"filialId": faker.number.int(),"planTypeId": faker.number.int(),"authorId": faker.number.int(),get "status"() { return createPlanStatus2() },"stageNote": faker.string.alpha(),"createdAt": faker.date.anytime().toISOString(),"updatedAt": faker.date.anytime().toISOString(),"sentToDtoeAt": faker.date.anytime().toISOString(),"decidedAt": faker.date.anytime().toISOString(),"canSend": faker.datatype.boolean(),"canSendToDtoe": faker.datatype.boolean(),"openRemarksCount": faker.number.int(),...(data || {})} }
}