/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionHistoryEntry } from "../types/CorrectionHistoryEntry";
import { faker } from "@faker-js/faker";

export function createCorrectionHistoryEntry(data?: Partial<CorrectionHistoryEntry>): CorrectionHistoryEntry {

  return {
    ...{"id": faker.number.int(),"correctionId": faker.number.int(),"timestamp": faker.date.anytime().toISOString(),"userId": faker.number.int(),"text": faker.string.alpha()},
    ...data || {}
  }
}