/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionTypeDetail } from "../types/CorrectionTypeDetail";
import { createCorrectionType } from "./createCorrectionType";
import { createPackageRequirement } from "./createPackageRequirement";
import { faker } from "@faker-js/faker";

export function createCorrectionTypeDetail(data?: Partial<CorrectionTypeDetail>): CorrectionTypeDetail {

  return {
    ...{...createCorrectionType(), ...{get "requirements"() { return faker.helpers.multiple(() => (createPackageRequirement())) }}},
    ...data || {}
  }
}