/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanPackageRequirementKind2 } from "../types/PlanPackageRequirementKind2";
import { faker } from "@faker-js/faker";

export function createPlanPackageRequirementKind2(data?: Partial<PlanPackageRequirementKind2>): PlanPackageRequirementKind2 {

  return data || faker.helpers.arrayElement<PlanPackageRequirementKind2>(["MAIN_EXCEL", "EXCEL_SHEET", "DOCUMENT"])
}