/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CfoInput } from "../types/CfoInput";
import { faker } from "@faker-js/faker";

export function createCfoInput(data?: Partial<CfoInput>): CfoInput {

  return {
    ...{"code": faker.string.alpha(),"name": faker.string.alpha(),"isActive": faker.datatype.boolean()},
    ...data || {}
  }
}