/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse } from "../types/ErrorResponse";
import { faker } from "@faker-js/faker";

export function createErrorResponse(data?: Partial<ErrorResponse>): ErrorResponse {

  return {
    ...{"statusCode": faker.number.int(),"message": faker.helpers.arrayElement<any>([faker.string.alpha(), faker.helpers.multiple(() => (faker.string.alpha()))]),"error": faker.string.alpha()},
    ...data || {}
  }
}