/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactPackageHistoryEntry2 } from "../types/FactPackageHistoryEntry2";
import { createUserSummary } from "./createUserSummary";
import { faker } from "@faker-js/faker";

export function createFactPackageHistoryEntry2(data?: Partial<FactPackageHistoryEntry2>): FactPackageHistoryEntry2 {

  return { ...{"id": faker.number.int(),"factPackageId": faker.number.int(),"userId": faker.number.int(),get "user"() { return faker.helpers.arrayElement<any>([createUserSummary(), null]) },"timestamp": faker.date.anytime().toISOString(),"text": faker.string.alpha(),...(data || {})} }
}