/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Direction } from "../types/Direction";
import { faker } from "@faker-js/faker";

export function createDirection(data?: Partial<Direction>): Direction {

  return data || faker.helpers.arrayElement<Direction>(["DO", "TOIR", "KR_PD", "KR_HS"])
}