/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionStatus } from "../types/CorrectionStatus";
import { faker } from "@faker-js/faker";

export function createCorrectionStatus(data?: Partial<CorrectionStatus>): CorrectionStatus {

  return data || faker.helpers.arrayElement<CorrectionStatus>(["DRAFT", "UNDER_CFO_REVIEW", "PARTIALLY_APPROVED", "RETURNED_FOR_REVISION", "RESUBMITTED", "ALL_CFO_APPROVED", "SENT_TO_DTOE", "UNDER_DTOE_REVIEW", "RETURNED_BY_DTOE", "APPROVED_BY_DTOE"])
}