/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactRemarkStatus2 } from "../types/FactRemarkStatus2";
import { faker } from "@faker-js/faker";

export function createFactRemarkStatus2(data?: Partial<FactRemarkStatus2>): FactRemarkStatus2 {

  return data || faker.helpers.arrayElement<FactRemarkStatus2>(["OPEN", "FIXED_BY_FILIAL", "CLOSED"])
}