/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanCfoSelectionInput } from "../types/PlanCfoSelectionInput";
import { faker } from "@faker-js/faker";

export function createPlanCfoSelectionInput(data?: Partial<PlanCfoSelectionInput>): PlanCfoSelectionInput {

  return {
    ...{"cfoIds": faker.helpers.multiple(() => (faker.number.int()), { count: 1 })},
    ...data || {}
  }
}