/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CorrectionCfoStatus2 } from "../types/CorrectionCfoStatus2";
import { createCfo } from "./createCfo";
import { createCfoStatusValue2 } from "./createCfoStatusValue2";
import { createUserSummary } from "./createUserSummary";
import { faker } from "@faker-js/faker";

export function createCorrectionCfoStatus2(data?: Partial<CorrectionCfoStatus2>): CorrectionCfoStatus2 {

  return { ...{"id": faker.number.int(),"correctionId": faker.number.int(),"cfoId": faker.number.int(),get "cfo"() { return createCfo() },get "status"() { return createCfoStatusValue2() },"isRequired": faker.datatype.boolean(),"decidedById": faker.number.int(),get "decidedBy"() { return faker.helpers.arrayElement<any>([createUserSummary(), null]) },"decidedAt": faker.date.anytime().toISOString(),...(data || {})} }
}