/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PackageRequirementInput } from "../types/PackageRequirementInput";
import { createPackageRequirementKind2 } from "./createPackageRequirementKind2";
import { faker } from "@faker-js/faker";

export function createPackageRequirementInput(data?: Partial<PackageRequirementInput>): PackageRequirementInput {

  return { ...{get "kind"() { return createPackageRequirementKind2() },"name": faker.string.alpha(),"isRequired": faker.datatype.boolean(),"responsibleCfoId": faker.number.int(),"namePattern": faker.string.alpha(),"fileFormat": faker.string.alpha(),"order": faker.number.int(),...(data || {})} }
}