/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactPackageListItem } from "../types/FactPackageListItem";
import { createFactCfoStatusValue2 } from "./createFactCfoStatusValue2";
import { createFactPackage } from "./createFactPackage";
import { createFilial } from "./createFilial";
import { createUserSummary } from "./createUserSummary";
import { faker } from "@faker-js/faker";

export function createFactPackageListItem(data?: Partial<FactPackageListItem>): FactPackageListItem {

  return {
    ...{...createFactPackage(), ...{get "filial"() { return createFilial() },get "author"() { return createUserSummary() },get "myCfoStatus"() { return faker.helpers.arrayElement<any>([createFactCfoStatusValue2(), null]) }}},
    ...data || {}
  }
}