/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileVersion2 } from "../types/FileVersion2";
import { faker } from "@faker-js/faker";

export function createFileVersion2(data?: Partial<FileVersion2>): FileVersion2 {

  return {
    ...{"id": faker.number.int(),"slotId": faker.number.int(),"versionNumber": faker.number.int(),"fileName": faker.string.alpha(),"fileSize": faker.number.int(),"mimeType": faker.string.alpha(),"uploadedById": faker.number.int(),"uploadedAt": faker.date.anytime().toISOString(),"remarkId": faker.number.int(),"note": faker.string.alpha()},
    ...data || {}
  }
}