/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactFormCode2 } from "../types/FactFormCode2";
import { faker } from "@faker-js/faker";

export function createFactFormCode2(data?: Partial<FactFormCode2>): FactFormCode2 {

  return data || faker.helpers.arrayElement<FactFormCode2>(["ACT_WORK", "ACT_SERVICE", "KS2", "KS3", "ACT_MATERIALS", "INVOICE", "PAYMENT_REQUEST"])
}