/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactCfoStatusValue } from "../types/FactCfoStatusValue";
import { faker } from "@faker-js/faker";

export function createFactCfoStatusValue(data?: Partial<FactCfoStatusValue>): FactCfoStatusValue {

  return data || faker.helpers.arrayElement<FactCfoStatusValue>(["PENDING", "APPROVED", "RETURNED"])
}