/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Notification2 } from "../types/Notification2";
import { faker } from "@faker-js/faker";

export function createNotification2(data?: Partial<Notification2>): Notification2 {

  return {
    ...{"id": faker.number.int(),"userId": faker.number.int(),"correctionId": faker.number.int(),"correctionHumanId": faker.string.alpha(),"text": faker.string.alpha(),"isRead": faker.datatype.boolean(),"createdAt": faker.date.anytime().toISOString()},
    ...data || {}
  }
}