/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanFileVersion } from "../types/PlanFileVersion";
import { faker } from "@faker-js/faker";

export function createPlanFileVersion(data?: Partial<PlanFileVersion>): PlanFileVersion {

  return {
    ...{"id": faker.number.int(),"slotId": faker.number.int(),"versionNumber": faker.number.int(),"fileName": faker.string.alpha(),"fileSize": faker.number.int(),"mimeType": faker.string.alpha(),"uploadedById": faker.number.int(),"uploadedAt": faker.date.anytime().toISOString(),"remarkId": faker.number.int(),"note": faker.string.alpha()},
    ...data || {}
  }
}