/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanRemark } from "../types/PlanRemark";
import { createPlanRemarkStatus2 } from "./createPlanRemarkStatus2";
import { faker } from "@faker-js/faker";

export function createPlanRemark(data?: Partial<PlanRemark>): PlanRemark {

  return { ...{"id": faker.number.int(),"humanId": faker.string.alpha(),"planId": faker.number.int(),"cfoId": faker.number.int(),"authorId": faker.number.int(),"createdAt": faker.date.anytime().toISOString(),"relatedSlotId": faker.number.int(),"fileVersionId": faker.number.int(),"sheetName": faker.string.alpha(),"rowRef": faker.string.alpha(),"cellRef": faker.string.alpha(),"description": faker.string.alpha(),"requiredAction": faker.string.alpha(),get "status"() { return createPlanRemarkStatus2() },"closedById": faker.number.int(),"closedAt": faker.date.anytime().toISOString(),"issuerLabel": faker.string.alpha(),...(data || {})} }
}