/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanCfoStatusValue2 } from "../types/PlanCfoStatusValue2";
import { faker } from "@faker-js/faker";

export function createPlanCfoStatusValue2(data?: Partial<PlanCfoStatusValue2>): PlanCfoStatusValue2 {

  return data || faker.helpers.arrayElement<PlanCfoStatusValue2>(["PENDING", "APPROVED", "RETURNED"])
}