/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanCfoStatus2 } from "../types/PlanCfoStatus2";
import { createCfo } from "./createCfo";
import { createPlanCfoStatusValue2 } from "./createPlanCfoStatusValue2";
import { createUserSummary } from "./createUserSummary";
import { faker } from "@faker-js/faker";

export function createPlanCfoStatus2(data?: Partial<PlanCfoStatus2>): PlanCfoStatus2 {

  return { ...{"id": faker.number.int(),"planId": faker.number.int(),"cfoId": faker.number.int(),get "cfo"() { return createCfo() },get "status"() { return createPlanCfoStatusValue2() },"isRequired": faker.datatype.boolean(),"decidedById": faker.number.int(),get "decidedBy"() { return faker.helpers.arrayElement<any>([createUserSummary(), null]) },"decidedAt": faker.date.anytime().toISOString(),...(data || {})} }
}