/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanPackageRequirementInput } from "../types/PlanPackageRequirementInput";
import { createPlanPackageRequirementKind2 } from "./createPlanPackageRequirementKind2";
import { faker } from "@faker-js/faker";

export function createPlanPackageRequirementInput(data?: Partial<PlanPackageRequirementInput>): PlanPackageRequirementInput {

  return { ...{get "kind"() { return createPlanPackageRequirementKind2() },"name": faker.string.alpha(),"isRequired": faker.datatype.boolean(),"responsibleCfoId": faker.number.int(),"namePattern": faker.string.alpha(),"fileFormat": faker.string.alpha(),"order": faker.number.int(),"choiceGroupKey": faker.string.alpha(),"groupLabel": faker.string.alpha(),...(data || {})} }
}