/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RemarkReopenInput } from "../types/RemarkReopenInput";
import { faker } from "@faker-js/faker";

export function createRemarkReopenInput(data?: Partial<RemarkReopenInput>): RemarkReopenInput {

  return {
    ...{"description": faker.string.alpha(),"requiredAction": faker.string.alpha()},
    ...data || {}
  }
}