/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanType } from "../types/PlanType";
import { faker } from "@faker-js/faker";

export function createPlanType(data?: Partial<PlanType>): PlanType {

  return {
    ...{"id": faker.number.int(),"code": faker.string.alpha(),"name": faker.string.alpha(),"description": faker.string.alpha(),"isActive": faker.datatype.boolean()},
    ...data || {}
  }
}