/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactRemarkStatus } from "../types/FactRemarkStatus";
import { faker } from "@faker-js/faker";

export function createFactRemarkStatus(data?: Partial<FactRemarkStatus>): FactRemarkStatus {

  return data || faker.helpers.arrayElement<FactRemarkStatus>(["OPEN", "FIXED_BY_FILIAL", "CLOSED"])
}