/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactCfoStatusValue2 } from "../types/FactCfoStatusValue2";
import { faker } from "@faker-js/faker";

export function createFactCfoStatusValue2(data?: Partial<FactCfoStatusValue2>): FactCfoStatusValue2 {

  return data || faker.helpers.arrayElement<FactCfoStatusValue2>(["PENDING", "APPROVED", "RETURNED"])
}