/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserCreateInput } from "../types/UserCreateInput";
import { createRole2 } from "./createRole2";
import { faker } from "@faker-js/faker";

export function createUserCreateInput(data?: Partial<UserCreateInput>): UserCreateInput {

  return { ...{"username": faker.string.alpha(),"password": faker.string.alpha({ length: 9 }),"email": faker.string.alpha(),"firstName": faker.string.alpha(),"lastName": faker.string.alpha(),get "role"() { return createRole2() },"filialId": faker.number.int(),"cfoId": faker.number.int(),"position": faker.string.alpha(),"phone": faker.string.alpha(),...(data || {})} }
}