/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FactFinalDecision } from "../types/FactFinalDecision";
import { faker } from "@faker-js/faker";

export function createFactFinalDecision(data?: Partial<FactFinalDecision>): FactFinalDecision {

  return {
    ...{"decision": faker.helpers.arrayElement<NonNullable<FactFinalDecision>["decision"]>(["APPROVE", "RETURN"])},
    ...data || {}
  }
}