/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RemarkStatus } from "../types/RemarkStatus";
import { faker } from "@faker-js/faker";

export function createRemarkStatus(data?: Partial<RemarkStatus>): RemarkStatus {

  return data || faker.helpers.arrayElement<RemarkStatus>(["OPEN", "FIXED_BY_FILIAL", "REOPENED", "CLOSED"])
}