/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanCreateInput } from "../types/PlanCreateInput";
import { faker } from "@faker-js/faker";

export function createPlanCreateInput(data?: Partial<PlanCreateInput>): PlanCreateInput {

  return {
    ...{"planTypeId": faker.number.int()},
    ...data || {}
  }
}