/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UploadFactFormVersion201, UploadFactFormVersion400, UploadFactFormVersion403, UploadFactFormVersionMutationRequest, UploadFactFormVersionMutationResponse, UploadFactFormVersionPathParams } from "../../types/factPackagesController/UploadFactFormVersion";
import { createErrorResponse2 } from "../createErrorResponse2";
import { createFactFormCode2 } from "../createFactFormCode2";
import { createFactFormVersion2 } from "../createFactFormVersion2";
import { faker } from "@faker-js/faker";

export function createUploadFactFormVersionPathParams(data?: Partial<UploadFactFormVersionPathParams>): UploadFactFormVersionPathParams {

  return { ...{"humanId": faker.string.alpha(),get "formCode"() { return createFactFormCode2() },...(data || {})} }
}

/**
 * @description Новая версия формы добавлена
 */
export function createUploadFactFormVersion201(data?: Partial<UploadFactFormVersion201>): UploadFactFormVersion201 {

  return createFactFormVersion2(data)
}

/**
 * @description Факт-пакет в финальном статусе либо formCode не входит в каталог направления
 */
export function createUploadFactFormVersion400(data?: Partial<UploadFactFormVersion400>): UploadFactFormVersion400 {

  return createErrorResponse2(data)
}

/**
 * @description Нет доступа (не автор/не владелец филиала)
 */
export function createUploadFactFormVersion403(data?: Partial<UploadFactFormVersion403>): UploadFactFormVersion403 {

  return createErrorResponse2(data)
}

export function createUploadFactFormVersionMutationRequest(data?: Partial<UploadFactFormVersionMutationRequest>): UploadFactFormVersionMutationRequest {

  return {
    ...{"file": faker.image.url() as unknown as Blob,"note": faker.string.alpha(),"remarkId": faker.number.int()},
    ...data || {}
  }
}

export function createUploadFactFormVersionMutationResponse(data?: Partial<UploadFactFormVersionMutationResponse>): UploadFactFormVersionMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUploadFactFormVersion201()])
}