/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteFactPackageRemark400, DeleteFactPackageRemark403, DeleteFactPackageRemarkMutationResponse, DeleteFactPackageRemarkPathParams } from "../../types/factPackagesController/DeleteFactPackageRemark";
import { createErrorResponse2 } from "../createErrorResponse2";
import { faker } from "@faker-js/faker";

export function createDeleteFactPackageRemarkPathParams(data?: Partial<DeleteFactPackageRemarkPathParams>): DeleteFactPackageRemarkPathParams {

  return {
    ...{"humanId": faker.string.alpha(),"remarkId": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Замечание удалено
 */
export function createDeleteFactPackageRemark204() {

  return undefined
}

/**
 * @description Замечание не в статусе OPEN
 */
export function createDeleteFactPackageRemark400(data?: Partial<DeleteFactPackageRemark400>): DeleteFactPackageRemark400 {

  return createErrorResponse2(data)
}

/**
 * @description Не автор замечания
 */
export function createDeleteFactPackageRemark403(data?: Partial<DeleteFactPackageRemark403>): DeleteFactPackageRemark403 {

  return createErrorResponse2(data)
}

export function createDeleteFactPackageRemarkMutationResponse(data?: Partial<DeleteFactPackageRemarkMutationResponse>): DeleteFactPackageRemarkMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeleteFactPackageRemark204()])
}