/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFactPackageStats200, GetFactPackageStatsQueryResponse } from "../../types/factPackagesController/GetFactPackageStats";
import { createFactPackageStats } from "../createFactPackageStats";
import { faker } from "@faker-js/faker";

/**
 * @description Агрегированные счётчики для карточек дашборда (в рамках видимости роли)
 */
export function createGetFactPackageStats200(data?: Partial<GetFactPackageStats200>): GetFactPackageStats200 {

  return createFactPackageStats(data)
}

export function createGetFactPackageStatsQueryResponse(data?: Partial<GetFactPackageStatsQueryResponse>): GetFactPackageStatsQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetFactPackageStats200()])
}