/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFactPackages200, GetFactPackagesQueryParams, GetFactPackagesQueryResponse } from "../../types/factPackagesController/GetFactPackages";
import { createDirection2 } from "../createDirection2";
import { createFactPackageStatus2 } from "../createFactPackageStatus2";
import { createPaginatedFactPackages } from "../createPaginatedFactPackages";
import { faker } from "@faker-js/faker";

export function createGetFactPackagesQueryParams(data?: Partial<GetFactPackagesQueryParams>): GetFactPackagesQueryParams {

  return { ...{get "direction"() { return createDirection2() },get "status"() { return createFactPackageStatus2() },"filialId": faker.number.int(),"cfoId": faker.number.int(),"q": faker.string.alpha(),"page": faker.number.int(),"pageSize": faker.number.int(),...(data || {})} }
}

/**
 * @description Страница факт-пакетов
 */
export function createGetFactPackages200(data?: Partial<GetFactPackages200>): GetFactPackages200 {

  return createPaginatedFactPackages(data)
}

export function createGetFactPackagesQueryResponse(data?: Partial<GetFactPackagesQueryResponse>): GetFactPackagesQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetFactPackages200()])
}