/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFactPackageStatsDtoe200, GetFactPackageStatsDtoe403, GetFactPackageStatsDtoeQueryResponse } from "../../types/factPackagesController/GetFactPackageStatsDtoe";
import { createErrorResponse2 } from "../createErrorResponse2";
import { createFactPackageStats } from "../createFactPackageStats";
import { faker } from "@faker-js/faker";

/**
 * @description Агрегированные счётчики в рамках видимости роли DTOE
 */
export function createGetFactPackageStatsDtoe200(data?: Partial<GetFactPackageStatsDtoe200>): GetFactPackageStatsDtoe200 {

  return createFactPackageStats(data)
}

/**
 * @description У пользователя не роль DTOE
 */
export function createGetFactPackageStatsDtoe403(data?: Partial<GetFactPackageStatsDtoe403>): GetFactPackageStatsDtoe403 {

  return createErrorResponse2(data)
}

export function createGetFactPackageStatsDtoeQueryResponse(data?: Partial<GetFactPackageStatsDtoeQueryResponse>): GetFactPackageStatsDtoeQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetFactPackageStatsDtoe200()])
}