/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { authUserSchema } from "../authUserSchema";
import { errorResponse2Schema } from "../errorResponse2Schema";

/**
 * @description Текущий пользователь
 */
export const getMe200Schema = z.lazy(() => authUserSchema)

/**
 * @description Не авторизован
 */
export const getMe401Schema = z.lazy(() => errorResponse2Schema)

export const getMeQueryResponseSchema = z.lazy(() => getMe200Schema)