/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { authUserSchema } from "../authUserSchema";
import { errorResponse2Schema } from "../errorResponse2Schema";
import { loginRequestSchema } from "../loginRequestSchema";

/**
 * @description Успешный вход, устанавливает httpOnly cookie с токенами
 */
export const login200Schema = z.lazy(() => authUserSchema)

/**
 * @description Неверный логин/пароль или заблокированная учётная запись
 */
export const login401Schema = z.lazy(() => errorResponse2Schema)

export const loginMutationRequestSchema = z.lazy(() => loginRequestSchema)

export const loginMutationResponseSchema = z.lazy(() => login200Schema)