/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { errorResponse2Schema } from "../errorResponse2Schema";

/**
 * @description Все сессии пользователя завершены, куки текущей сессии очищены
 */
export const logoutAll204Schema = z.unknown()

/**
 * @description Не авторизован
 */
export const logoutAll401Schema = z.lazy(() => errorResponse2Schema)

export const logoutAllMutationResponseSchema = z.lazy(() => logoutAll204Schema)