/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

/**
 * @description Куки очищены
 */
export const logout204Schema = z.unknown()

export const logoutMutationResponseSchema = z.lazy(() => logout204Schema)