/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { authUserSchema } from "../authUserSchema";
import { errorResponse2Schema } from "../errorResponse2Schema";

/**
 * @description Токены обновлены
 */
export const refresh200Schema = z.lazy(() => authUserSchema)

/**
 * @description Refresh-токен недействителен
 */
export const refresh401Schema = z.lazy(() => errorResponse2Schema)

export const refreshMutationResponseSchema = z.lazy(() => refresh200Schema)