/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetCorrectionType200, GetCorrectionTypePathParams, GetCorrectionTypeQueryResponse } from "../../types/orgController/GetCorrectionType";
import { createCorrectionTypeDetail } from "../createCorrectionTypeDetail";
import { faker } from "@faker-js/faker";

export function createGetCorrectionTypePathParams(data?: Partial<GetCorrectionTypePathParams>): GetCorrectionTypePathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Тип корректировки с требованиями пакета
 */
export function createGetCorrectionType200(data?: Partial<GetCorrectionType200>): GetCorrectionType200 {

  return createCorrectionTypeDetail(data)
}

export function createGetCorrectionTypeQueryResponse(data?: Partial<GetCorrectionTypeQueryResponse>): GetCorrectionTypeQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetCorrectionType200()])
}