/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeletePlanTypeMutationResponse, DeletePlanTypePathParams } from "../../types/orgController/DeletePlanType";
import { faker } from "@faker-js/faker";

export function createDeletePlanTypePathParams(data?: Partial<DeletePlanTypePathParams>): DeletePlanTypePathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Удалено
 */
export function createDeletePlanType204() {

  return undefined
}

export function createDeletePlanTypeMutationResponse(data?: Partial<DeletePlanTypeMutationResponse>): DeletePlanTypeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeletePlanType204()])
}