/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdatePlanType200, UpdatePlanTypeMutationRequest, UpdatePlanTypeMutationResponse, UpdatePlanTypePathParams } from "../../types/orgController/UpdatePlanType";
import { createPlanType } from "../createPlanType";
import { createPlanTypeInput } from "../createPlanTypeInput";
import { faker } from "@faker-js/faker";

export function createUpdatePlanTypePathParams(data?: Partial<UpdatePlanTypePathParams>): UpdatePlanTypePathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Тип обновлён
 */
export function createUpdatePlanType200(data?: Partial<UpdatePlanType200>): UpdatePlanType200 {

  return createPlanType(data)
}

export function createUpdatePlanTypeMutationRequest(data?: Partial<UpdatePlanTypeMutationRequest>): UpdatePlanTypeMutationRequest {

  return createPlanTypeInput(data)
}

export function createUpdatePlanTypeMutationResponse(data?: Partial<UpdatePlanTypeMutationResponse>): UpdatePlanTypeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUpdatePlanType200()])
}