/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateCfo200, UpdateCfoMutationRequest, UpdateCfoMutationResponse, UpdateCfoPathParams } from "../../types/orgController/UpdateCfo";
import { createCfo } from "../createCfo";
import { createCfoInput } from "../createCfoInput";
import { faker } from "@faker-js/faker";

export function createUpdateCfoPathParams(data?: Partial<UpdateCfoPathParams>): UpdateCfoPathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description ЦФО обновлён
 */
export function createUpdateCfo200(data?: Partial<UpdateCfo200>): UpdateCfo200 {

  return createCfo(data)
}

export function createUpdateCfoMutationRequest(data?: Partial<UpdateCfoMutationRequest>): UpdateCfoMutationRequest {

  return createCfoInput(data)
}

export function createUpdateCfoMutationResponse(data?: Partial<UpdateCfoMutationResponse>): UpdateCfoMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUpdateCfo200()])
}