/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetFilials200, GetFilialsQueryParams, GetFilialsQueryResponse } from "../../types/orgController/GetFilials";
import { createFilial } from "../createFilial";
import { faker } from "@faker-js/faker";

export function createGetFilialsQueryParams(data?: Partial<GetFilialsQueryParams>): GetFilialsQueryParams {

  return {
    ...{"isActive": faker.datatype.boolean()},
    ...data || {}
  }
}

/**
 * @description Список филиалов
 */
export function createGetFilials200(data?: GetFilials200): GetFilials200 {

  return [
        ...faker.helpers.multiple(() => (createFilial())),
        ...data || []
      ]
}

export function createGetFilialsQueryResponse(data?: Partial<GetFilialsQueryResponse>): GetFilialsQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetFilials200()])
}