/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateFilial200, UpdateFilialMutationRequest, UpdateFilialMutationResponse, UpdateFilialPathParams } from "../../types/orgController/UpdateFilial";
import { createFilial } from "../createFilial";
import { createFilialInput } from "../createFilialInput";
import { faker } from "@faker-js/faker";

export function createUpdateFilialPathParams(data?: Partial<UpdateFilialPathParams>): UpdateFilialPathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Филиал обновлён
 */
export function createUpdateFilial200(data?: Partial<UpdateFilial200>): UpdateFilial200 {

  return createFilial(data)
}

export function createUpdateFilialMutationRequest(data?: Partial<UpdateFilialMutationRequest>): UpdateFilialMutationRequest {

  return createFilialInput(data)
}

export function createUpdateFilialMutationResponse(data?: Partial<UpdateFilialMutationResponse>): UpdateFilialMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUpdateFilial200()])
}