/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateFilial201, CreateFilialMutationRequest, CreateFilialMutationResponse } from "../../types/orgController/CreateFilial";
import { createFilial } from "../createFilial";
import { createFilialInput } from "../createFilialInput";
import { faker } from "@faker-js/faker";

/**
 * @description Филиал создан
 */
export function createCreateFilial201(data?: Partial<CreateFilial201>): CreateFilial201 {

  return createFilial(data)
}

export function createCreateFilialMutationRequest(data?: Partial<CreateFilialMutationRequest>): CreateFilialMutationRequest {

  return createFilialInput(data)
}

export function createCreateFilialMutationResponse(data?: Partial<CreateFilialMutationResponse>): CreateFilialMutationResponse {

  return data || faker.helpers.arrayElement<any>([createCreateFilial201()])
}