/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeletePackageRequirementMutationResponse, DeletePackageRequirementPathParams } from "../../types/orgController/DeletePackageRequirement";
import { faker } from "@faker-js/faker";

export function createDeletePackageRequirementPathParams(data?: Partial<DeletePackageRequirementPathParams>): DeletePackageRequirementPathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Удалено
 */
export function createDeletePackageRequirement204() {

  return undefined
}

export function createDeletePackageRequirementMutationResponse(data?: Partial<DeletePackageRequirementMutationResponse>): DeletePackageRequirementMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeletePackageRequirement204()])
}