/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreatePlanPackageRequirement201, CreatePlanPackageRequirementMutationRequest, CreatePlanPackageRequirementMutationResponse, CreatePlanPackageRequirementPathParams } from "../../types/orgController/CreatePlanPackageRequirement";
import { createPlanPackageRequirement } from "../createPlanPackageRequirement";
import { createPlanPackageRequirementInput } from "../createPlanPackageRequirementInput";
import { faker } from "@faker-js/faker";

export function createCreatePlanPackageRequirementPathParams(data?: Partial<CreatePlanPackageRequirementPathParams>): CreatePlanPackageRequirementPathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Требование добавлено
 */
export function createCreatePlanPackageRequirement201(data?: Partial<CreatePlanPackageRequirement201>): CreatePlanPackageRequirement201 {

  return createPlanPackageRequirement(data)
}

export function createCreatePlanPackageRequirementMutationRequest(data?: Partial<CreatePlanPackageRequirementMutationRequest>): CreatePlanPackageRequirementMutationRequest {

  return createPlanPackageRequirementInput(data)
}

export function createCreatePlanPackageRequirementMutationResponse(data?: Partial<CreatePlanPackageRequirementMutationResponse>): CreatePlanPackageRequirementMutationResponse {

  return data || faker.helpers.arrayElement<any>([createCreatePlanPackageRequirement201()])
}