/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteCorrectionTypeMutationResponse, DeleteCorrectionTypePathParams } from "../../types/orgController/DeleteCorrectionType";
import { faker } from "@faker-js/faker";

export function createDeleteCorrectionTypePathParams(data?: Partial<DeleteCorrectionTypePathParams>): DeleteCorrectionTypePathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Удалено
 */
export function createDeleteCorrectionType204() {

  return undefined
}

export function createDeleteCorrectionTypeMutationResponse(data?: Partial<DeleteCorrectionTypeMutationResponse>): DeleteCorrectionTypeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeleteCorrectionType204()])
}