/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreatePlanType201, CreatePlanTypeMutationRequest, CreatePlanTypeMutationResponse } from "../../types/orgController/CreatePlanType";
import { createPlanType } from "../createPlanType";
import { createPlanTypeInput } from "../createPlanTypeInput";
import { faker } from "@faker-js/faker";

/**
 * @description Тип создан
 */
export function createCreatePlanType201(data?: Partial<CreatePlanType201>): CreatePlanType201 {

  return createPlanType(data)
}

export function createCreatePlanTypeMutationRequest(data?: Partial<CreatePlanTypeMutationRequest>): CreatePlanTypeMutationRequest {

  return createPlanTypeInput(data)
}

export function createCreatePlanTypeMutationResponse(data?: Partial<CreatePlanTypeMutationResponse>): CreatePlanTypeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createCreatePlanType201()])
}