/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateCorrectionType201, CreateCorrectionTypeMutationRequest, CreateCorrectionTypeMutationResponse } from "../../types/orgController/CreateCorrectionType";
import { createCorrectionType } from "../createCorrectionType";
import { createCorrectionTypeInput } from "../createCorrectionTypeInput";
import { faker } from "@faker-js/faker";

/**
 * @description Тип создан
 */
export function createCreateCorrectionType201(data?: Partial<CreateCorrectionType201>): CreateCorrectionType201 {

  return createCorrectionType(data)
}

export function createCreateCorrectionTypeMutationRequest(data?: Partial<CreateCorrectionTypeMutationRequest>): CreateCorrectionTypeMutationRequest {

  return createCorrectionTypeInput(data)
}

export function createCreateCorrectionTypeMutationResponse(data?: Partial<CreateCorrectionTypeMutationResponse>): CreateCorrectionTypeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createCreateCorrectionType201()])
}