/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteFilialCfoLinkMutationResponse, DeleteFilialCfoLinkPathParams } from "../../types/orgController/DeleteFilialCfoLink";
import { faker } from "@faker-js/faker";

export function createDeleteFilialCfoLinkPathParams(data?: Partial<DeleteFilialCfoLinkPathParams>): DeleteFilialCfoLinkPathParams {

  return {
    ...{"id": faker.number.int()},
    ...data || {}
  }
}

/**
 * @description Удалено
 */
export function createDeleteFilialCfoLink204() {

  return undefined
}

export function createDeleteFilialCfoLinkMutationResponse(data?: Partial<DeleteFilialCfoLinkMutationResponse>): DeleteFilialCfoLinkMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeleteFilialCfoLink204()])
}