/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetCorrectionTypes200, GetCorrectionTypesQueryParams, GetCorrectionTypesQueryResponse } from "../../types/orgController/GetCorrectionTypes";
import { createCorrectionType } from "../createCorrectionType";
import { faker } from "@faker-js/faker";

export function createGetCorrectionTypesQueryParams(data?: Partial<GetCorrectionTypesQueryParams>): GetCorrectionTypesQueryParams {

  return {
    ...{"isActive": faker.datatype.boolean()},
    ...data || {}
  }
}

/**
 * @description Типы корректировок
 */
export function createGetCorrectionTypes200(data?: GetCorrectionTypes200): GetCorrectionTypes200 {

  return [
        ...faker.helpers.multiple(() => (createCorrectionType())),
        ...data || []
      ]
}

export function createGetCorrectionTypesQueryResponse(data?: Partial<GetCorrectionTypesQueryResponse>): GetCorrectionTypesQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetCorrectionTypes200()])
}