/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { filialInputSchema } from "../filialInputSchema";
import { filialSchema } from "../filialSchema";

/**
 * @description Филиал создан
 */
export const createFilial201Schema = z.lazy(() => filialSchema)

export const createFilialMutationRequestSchema = z.lazy(() => filialInputSchema)

export const createFilialMutationResponseSchema = z.lazy(() => createFilial201Schema)