/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planTypeInputSchema } from "../planTypeInputSchema";
import { planTypeSchema } from "../planTypeSchema";

/**
 * @description Тип создан
 */
export const createPlanType201Schema = z.lazy(() => planTypeSchema)

export const createPlanTypeMutationRequestSchema = z.lazy(() => planTypeInputSchema)

export const createPlanTypeMutationResponseSchema = z.lazy(() => createPlanType201Schema)