/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const deleteCfoPathParamsSchema = z.object({
    "id": z.int()
    })

/**
 * @description Удалено
 */
export const deleteCfo204Schema = z.unknown()

export const deleteCfoMutationResponseSchema = z.lazy(() => deleteCfo204Schema)