/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";

export const deleteFilialPathParamsSchema = z.object({
    "id": z.int()
    })

/**
 * @description Удалено
 */
export const deleteFilial204Schema = z.unknown()

export const deleteFilialMutationResponseSchema = z.lazy(() => deleteFilial204Schema)