/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { correctionTypeDetailSchema } from "../correctionTypeDetailSchema";

export const getCorrectionTypePathParamsSchema = z.object({
    "id": z.int()
    })

/**
 * @description Тип корректировки с требованиями пакета
 */
export const getCorrectionType200Schema = z.lazy(() => correctionTypeDetailSchema)

export const getCorrectionTypeQueryResponseSchema = z.lazy(() => getCorrectionType200Schema)