/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { filialCfoLinkInputSchema } from "../filialCfoLinkInputSchema";
import { filialCfoLinkSchema } from "../filialCfoLinkSchema";

export const updateFilialCfoLinkPathParamsSchema = z.object({
    "id": z.int()
    })

/**
 * @description Связь обновлена
 */
export const updateFilialCfoLink200Schema = z.lazy(() => filialCfoLinkSchema)

export const updateFilialCfoLinkMutationRequestSchema = z.lazy(() => filialCfoLinkInputSchema)

export const updateFilialCfoLinkMutationResponseSchema = z.lazy(() => updateFilialCfoLink200Schema)