/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { planTypeInputSchema } from "../planTypeInputSchema";
import { planTypeSchema } from "../planTypeSchema";

export const updatePlanTypePathParamsSchema = z.object({
    "id": z.int()
    })

/**
 * @description Тип обновлён
 */
export const updatePlanType200Schema = z.lazy(() => planTypeSchema)

export const updatePlanTypeMutationRequestSchema = z.lazy(() => planTypeInputSchema)

export const updatePlanTypeMutationResponseSchema = z.lazy(() => updatePlanType200Schema)