/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ApproveCorrectionByDtoeMutationResponse, ApproveCorrectionByDtoePathParams } from "../../types/correctionsController/ApproveCorrectionByDtoe";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { approveCorrectionByDtoe } from "../../clients/correctionsController/approveCorrectionByDtoe";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const approveCorrectionByDtoeMutationKey = () => [{ url: '/corrections/:humanId/dtoe-approve' }] as const

export type ApproveCorrectionByDtoeMutationKey = ReturnType<typeof approveCorrectionByDtoeMutationKey>

export function approveCorrectionByDtoeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = approveCorrectionByDtoeMutationKey()
        return mutationOptions<ApproveCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ApproveCorrectionByDtoePathParams["humanId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId }) => {
            return approveCorrectionByDtoe({ humanId }, config)
          },
        })

}

/**
 * @description Роль DTOE. Финальное согласование.
 * @summary Финально согласовать корректировку (ДТОиР)
 * {@link /corrections/:humanId/dtoe-approve}
 */
export function useApproveCorrectionByDtoe<TContext>(options: 
{
  mutation?: UseMutationOptions<ApproveCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ApproveCorrectionByDtoePathParams["humanId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? approveCorrectionByDtoeMutationKey()

          const baseOptions = approveCorrectionByDtoeMutationOptions(config) as UseMutationOptions<ApproveCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ApproveCorrectionByDtoePathParams["humanId"]}, TContext>
          

          return useMutation<ApproveCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ApproveCorrectionByDtoePathParams["humanId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ApproveCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ApproveCorrectionByDtoePathParams["humanId"]}, TContext>
      
}