/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CreateCorrectionMutationRequest, CreateCorrectionMutationResponse } from "../../types/correctionsController/CreateCorrection";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { createCorrection } from "../../clients/correctionsController/createCorrection";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createCorrectionMutationKey = () => [{ url: '/corrections' }] as const

export type CreateCorrectionMutationKey = ReturnType<typeof createCorrectionMutationKey>

export function createCorrectionMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreateCorrectionMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = createCorrectionMutationKey()
        return mutationOptions<CreateCorrectionMutationResponse, ResponseErrorConfig<Error>, {data: CreateCorrectionMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return createCorrection({ data }, config)
          },
        })

}

/**
 * @description Доступно только роли FILIAL. Создаёт корректировку и ячейки пакета по типу.
 * @summary Создать корректировку
 * {@link /corrections}
 */
export function useCreateCorrection<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateCorrectionMutationResponse, ResponseErrorConfig<Error>, {data: CreateCorrectionMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateCorrectionMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? createCorrectionMutationKey()

          const baseOptions = createCorrectionMutationOptions(config) as UseMutationOptions<CreateCorrectionMutationResponse, ResponseErrorConfig<Error>, {data: CreateCorrectionMutationRequest}, TContext>
          

          return useMutation<CreateCorrectionMutationResponse, ResponseErrorConfig<Error>, {data: CreateCorrectionMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CreateCorrectionMutationResponse, ResponseErrorConfig<Error>, {data: CreateCorrectionMutationRequest}, TContext>
      
}