/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { CancelCfoDecisionMutationResponse, CancelCfoDecisionPathParams, CancelCfoDecision400 } from "../../types/correctionsController/CancelCfoDecision";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { cancelCfoDecision } from "../../clients/correctionsController/cancelCfoDecision";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const cancelCfoDecisionMutationKey = () => [{ url: '/corrections/:humanId/cfo-cancel' }] as const

export type CancelCfoDecisionMutationKey = ReturnType<typeof cancelCfoDecisionMutationKey>

export function cancelCfoDecisionMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = cancelCfoDecisionMutationKey()
        return mutationOptions<CancelCfoDecisionMutationResponse, ResponseErrorConfig<CancelCfoDecision400>, {humanId: CancelCfoDecisionPathParams["humanId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId }) => {
            return cancelCfoDecision({ humanId }, config)
          },
        })

}

/**
 * @description Роль CFO. Возвращает статус этого ЦФО (APPROVED или RETURNED) обратно в
 * PENDING — страховка от случайного клика по «Согласовать»/«Вернуть на
 * доработку». Оставленные замечания не удаляются и не меняются, это часть
 * истории — откатывается только статус ЦФО. Недоступно, если корректировка
 * уже передана в ДТОиР (`UNDER_DTOE_REVIEW`/`RETURNED_BY_DTOE`/`APPROVED_BY_DTOE`)
 * — тогда `400`.
 * @summary Отменить собственное решение ЦФО
 * {@link /corrections/:humanId/cfo-cancel}
 */
export function useCancelCfoDecision<TContext>(options: 
{
  mutation?: UseMutationOptions<CancelCfoDecisionMutationResponse, ResponseErrorConfig<CancelCfoDecision400>, {humanId: CancelCfoDecisionPathParams["humanId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? cancelCfoDecisionMutationKey()

          const baseOptions = cancelCfoDecisionMutationOptions(config) as UseMutationOptions<CancelCfoDecisionMutationResponse, ResponseErrorConfig<CancelCfoDecision400>, {humanId: CancelCfoDecisionPathParams["humanId"]}, TContext>
          

          return useMutation<CancelCfoDecisionMutationResponse, ResponseErrorConfig<CancelCfoDecision400>, {humanId: CancelCfoDecisionPathParams["humanId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CancelCfoDecisionMutationResponse, ResponseErrorConfig<CancelCfoDecision400>, {humanId: CancelCfoDecisionPathParams["humanId"]}, TContext>
      
}