/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DownloadFileVersionQueryResponse, DownloadFileVersionPathParams, DownloadFileVersion403 } from "../../types/correctionsController/DownloadFileVersion";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { downloadFileVersion } from "../../clients/correctionsController/downloadFileVersion";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const downloadFileVersionQueryKey = ({ id }: { id: DownloadFileVersionPathParams["id"] | undefined }) => [{ url: '/files/:id/download', params: {id:id} }] as const

export type DownloadFileVersionQueryKey = ReturnType<typeof downloadFileVersionQueryKey>

export function downloadFileVersionQueryOptions({ id }: { id: DownloadFileVersionPathParams["id"] | undefined }, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = downloadFileVersionQueryKey({ id })
        return queryOptions<DownloadFileVersionQueryResponse, ResponseErrorConfig<DownloadFileVersion403>, DownloadFileVersionQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return downloadFileVersion({ id: id! }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Открыть/скачать содержимое версии файла. Доступно только ролям CFO и DTOE
 * (проверяющим), имеющим доступ к соответствующей корректировке — филиал,
 * загрузивший файл, эндпоинт не использует.
 * @summary Скачать файл версии
 * {@link /files/:id/download}
 */
export function useDownloadFileVersion<TData = DownloadFileVersionQueryResponse, TQueryData = DownloadFileVersionQueryResponse, TQueryKey extends QueryKey = DownloadFileVersionQueryKey>({ id }: { id: DownloadFileVersionPathParams["id"] | undefined }, options: 
{
  query?: Partial<QueryObserverOptions<DownloadFileVersionQueryResponse, ResponseErrorConfig<DownloadFileVersion403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? downloadFileVersionQueryKey({ id })
         

         const query = useQuery({
          ...downloadFileVersionQueryOptions({ id }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<DownloadFileVersion403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}