/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { DownloadFileVersionQueryResponse, DownloadFileVersionPathParams, DownloadFileVersion403 } from "../../types/correctionsController/DownloadFileVersion";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { downloadFileVersion } from "../../clients/correctionsController/downloadFileVersion";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const downloadFileVersionSuspenseQueryKey = ({ id }: { id: DownloadFileVersionPathParams["id"] | undefined }) => [{ url: '/files/:id/download', params: {id:id} }] as const

export type DownloadFileVersionSuspenseQueryKey = ReturnType<typeof downloadFileVersionSuspenseQueryKey>

export function downloadFileVersionSuspenseQueryOptions({ id }: { id: DownloadFileVersionPathParams["id"] }, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = downloadFileVersionSuspenseQueryKey({ id })
        return queryOptions<DownloadFileVersionQueryResponse, ResponseErrorConfig<DownloadFileVersion403>, DownloadFileVersionQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return downloadFileVersion({ id: id }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Открыть/скачать содержимое версии файла. Доступно только ролям CFO и DTOE
 * (проверяющим), имеющим доступ к соответствующей корректировке — филиал,
 * загрузивший файл, эндпоинт не использует.
 * @summary Скачать файл версии
 * {@link /files/:id/download}
 */
export function useDownloadFileVersionSuspense<TData = DownloadFileVersionQueryResponse, TQueryKey extends QueryKey = DownloadFileVersionSuspenseQueryKey>({ id }: { id: DownloadFileVersionPathParams["id"] }, options: 
{
  query?: Partial<UseSuspenseQueryOptions<DownloadFileVersionQueryResponse, ResponseErrorConfig<DownloadFileVersion403>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? downloadFileVersionSuspenseQueryKey({ id })
         

         const query = useSuspenseQuery({
          ...downloadFileVersionSuspenseQueryOptions({ id }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<DownloadFileVersion403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}