/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionQueryResponse, GetCorrectionPathParams, GetCorrection403, GetCorrection404 } from "../../types/correctionsController/GetCorrection";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getCorrection } from "../../clients/correctionsController/getCorrection";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCorrectionQueryKey = ({ humanId }: { humanId: GetCorrectionPathParams["humanId"] | undefined }) => [{ url: '/corrections/:humanId', params: {humanId:humanId} }] as const

export type GetCorrectionQueryKey = ReturnType<typeof getCorrectionQueryKey>

export function getCorrectionQueryOptions({ humanId }: { humanId: GetCorrectionPathParams["humanId"] | undefined }, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCorrectionQueryKey({ humanId })
        return queryOptions<GetCorrectionQueryResponse, ResponseErrorConfig<GetCorrection403 | GetCorrection404>, GetCorrectionQueryResponse, typeof queryKey>({
         enabled: !!(humanId),
         queryKey,
         queryFn: async ({ signal }) => {
            return getCorrection({ humanId: humanId! }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Детальная карточка корректировки
 * {@link /corrections/:humanId}
 */
export function useGetCorrection<TData = GetCorrectionQueryResponse, TQueryData = GetCorrectionQueryResponse, TQueryKey extends QueryKey = GetCorrectionQueryKey>({ humanId }: { humanId: GetCorrectionPathParams["humanId"] | undefined }, options: 
{
  query?: Partial<QueryObserverOptions<GetCorrectionQueryResponse, ResponseErrorConfig<GetCorrection403 | GetCorrection404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCorrectionQueryKey({ humanId })
         

         const query = useQuery({
          ...getCorrectionQueryOptions({ humanId }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetCorrection403 | GetCorrection404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}