/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionsQueryResponse, GetCorrectionsQueryParams } from "../../types/correctionsController/GetCorrections";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getCorrections } from "../../clients/correctionsController/getCorrections";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCorrectionsQueryKey = (params?: GetCorrectionsQueryParams) => [{ url: '/corrections' }, ...(params ? [params] : [])] as const

export type GetCorrectionsQueryKey = ReturnType<typeof getCorrectionsQueryKey>

export function getCorrectionsQueryOptions({ params }: { params?: GetCorrectionsQueryParams } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCorrectionsQueryKey(params)
        return queryOptions<GetCorrectionsQueryResponse, ResponseErrorConfig<Error>, GetCorrectionsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getCorrections({ params: params }, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Список автоматически ограничен ролью: FILIAL видит свои, CFO — направленные его ЦФО, DTOE/ADMIN — все.
 * @summary Список корректировок (в рамках видимости роли)
 * {@link /corrections}
 */
export function useGetCorrections<TData = GetCorrectionsQueryResponse, TQueryData = GetCorrectionsQueryResponse, TQueryKey extends QueryKey = GetCorrectionsQueryKey>({ params }: { params?: GetCorrectionsQueryParams } = {}, options: 
{
  query?: Partial<QueryObserverOptions<GetCorrectionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCorrectionsQueryKey(params)
         

         const query = useQuery({
          ...getCorrectionsQueryOptions({ params }, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}