/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionStatsCfoQueryResponse, GetCorrectionStatsCfo403 } from "../../types/correctionsController/GetCorrectionStatsCfo";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getCorrectionStatsCfo } from "../../clients/correctionsController/getCorrectionStatsCfo";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCorrectionStatsCfoSuspenseQueryKey = () => [{ url: '/corrections/stats/cfo' }] as const

export type GetCorrectionStatsCfoSuspenseQueryKey = ReturnType<typeof getCorrectionStatsCfoSuspenseQueryKey>

export function getCorrectionStatsCfoSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCorrectionStatsCfoSuspenseQueryKey()
        return queryOptions<GetCorrectionStatsCfoQueryResponse, ResponseErrorConfig<GetCorrectionStatsCfo403>, GetCorrectionStatsCfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getCorrectionStatsCfo({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Доступно только пользователю роли CFO.
 * @summary Статистика по корректировкам для раздела ЦФО
 * {@link /corrections/stats/cfo}
 */
export function useGetCorrectionStatsCfoSuspense<TData = GetCorrectionStatsCfoQueryResponse, TQueryKey extends QueryKey = GetCorrectionStatsCfoSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetCorrectionStatsCfoQueryResponse, ResponseErrorConfig<GetCorrectionStatsCfo403>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCorrectionStatsCfoSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getCorrectionStatsCfoSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetCorrectionStatsCfo403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}