/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionStatsFilialQueryResponse, GetCorrectionStatsFilial403 } from "../../types/correctionsController/GetCorrectionStatsFilial";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getCorrectionStatsFilial } from "../../clients/correctionsController/getCorrectionStatsFilial";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCorrectionStatsFilialQueryKey = () => [{ url: '/corrections/stats/filial' }] as const

export type GetCorrectionStatsFilialQueryKey = ReturnType<typeof getCorrectionStatsFilialQueryKey>

export function getCorrectionStatsFilialQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCorrectionStatsFilialQueryKey()
        return queryOptions<GetCorrectionStatsFilialQueryResponse, ResponseErrorConfig<GetCorrectionStatsFilial403>, GetCorrectionStatsFilialQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getCorrectionStatsFilial({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Доступно только пользователю роли FILIAL.
 * @summary Статистика по корректировкам для раздела филиала
 * {@link /corrections/stats/filial}
 */
export function useGetCorrectionStatsFilial<TData = GetCorrectionStatsFilialQueryResponse, TQueryData = GetCorrectionStatsFilialQueryResponse, TQueryKey extends QueryKey = GetCorrectionStatsFilialQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetCorrectionStatsFilialQueryResponse, ResponseErrorConfig<GetCorrectionStatsFilial403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCorrectionStatsFilialQueryKey()
         

         const query = useQuery({
          ...getCorrectionStatsFilialQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetCorrectionStatsFilial403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}