/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { GetCorrectionStatsQueryResponse } from "../../types/correctionsController/GetCorrectionStats";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getCorrectionStats } from "../../clients/correctionsController/getCorrectionStats";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCorrectionStatsSuspenseQueryKey = () => [{ url: '/corrections/stats' }] as const

export type GetCorrectionStatsSuspenseQueryKey = ReturnType<typeof getCorrectionStatsSuspenseQueryKey>

export function getCorrectionStatsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getCorrectionStatsSuspenseQueryKey()
        return queryOptions<GetCorrectionStatsQueryResponse, ResponseErrorConfig<Error>, GetCorrectionStatsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getCorrectionStats({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Статистика по корректировкам для карточек дашборда
 * {@link /corrections/stats}
 */
export function useGetCorrectionStatsSuspense<TData = GetCorrectionStatsQueryResponse, TQueryKey extends QueryKey = GetCorrectionStatsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetCorrectionStatsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getCorrectionStatsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getCorrectionStatsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}