/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	LeaveRemarkMutationRequest,
	LeaveRemarkMutationResponse,
	LeaveRemarkPathParams,
} from '../../types/correctionsController/LeaveRemark'

import { mutationOptions, useMutation } from '@tanstack/react-query'

import { leaveRemark } from '../../clients/correctionsController/leaveRemark'

export const leaveRemarkMutationKey = () => [{ url: '/corrections/:humanId/remarks' }] as const

export type LeaveRemarkMutationKey = ReturnType<typeof leaveRemarkMutationKey>

export function leaveRemarkMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<LeaveRemarkMutationRequest>> & { client?: Client } = {},
) {
	const mutationKey = leaveRemarkMutationKey()
	return mutationOptions<
		LeaveRemarkMutationResponse,
		ResponseErrorConfig<Error>,
		{ humanId: LeaveRemarkPathParams['humanId']; data: LeaveRemarkMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ humanId, data }) => {
			return leaveRemark({ humanId, data }, config)
		},
	})
}

/**
 * Роли CFO и DTOE. Создаёт замечание, привязанное к элементу пакета (`relatedSlotId`), не меняя
 * статус корректировки и статус проверяющего — проверяющий может оставить несколько замечаний к
 * разным элементам за один заход. Возврат пакета на доработку — отдельное действие (`POST
 * /corrections/{humanId}/cfo-return` или `.../dtoe-return`), требующее хотя бы одного открытого
 * замечания.
 *
 * @summary Оставить замечание к элементу пакета
 * {@link /corrections/:humanId/remarks}
 */
export function useLeaveRemark<TContext>(
	options: {
		mutation?: UseMutationOptions<
			LeaveRemarkMutationResponse,
			ResponseErrorConfig<Error>,
			{ humanId: LeaveRemarkPathParams['humanId']; data: LeaveRemarkMutationRequest },
			TContext
		> & { client?: QueryClient }
		client?: Partial<RequestConfig<LeaveRemarkMutationRequest>> & { client?: Client }
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...mutationOptions } = mutation
	const mutationKey = mutationOptions.mutationKey ?? leaveRemarkMutationKey()

	const baseOptions = leaveRemarkMutationOptions(config) as UseMutationOptions<
		LeaveRemarkMutationResponse,
		ResponseErrorConfig<Error>,
		{ humanId: LeaveRemarkPathParams['humanId']; data: LeaveRemarkMutationRequest },
		TContext
	>

	return useMutation<
		LeaveRemarkMutationResponse,
		ResponseErrorConfig<Error>,
		{ humanId: LeaveRemarkPathParams['humanId']; data: LeaveRemarkMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		LeaveRemarkMutationResponse,
		ResponseErrorConfig<Error>,
		{ humanId: LeaveRemarkPathParams['humanId']; data: LeaveRemarkMutationRequest },
		TContext
	>
}
