/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { MarkRemarkFixedMutationResponse, MarkRemarkFixedPathParams } from "../../types/correctionsController/MarkRemarkFixed";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { markRemarkFixed } from "../../clients/correctionsController/markRemarkFixed";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const markRemarkFixedMutationKey = () => [{ url: '/corrections/:humanId/remarks/:remarkId/fix' }] as const

export type MarkRemarkFixedMutationKey = ReturnType<typeof markRemarkFixedMutationKey>

export function markRemarkFixedMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = markRemarkFixedMutationKey()
        return mutationOptions<MarkRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkRemarkFixedPathParams["humanId"], remarkId: MarkRemarkFixedPathParams["remarkId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, remarkId }) => {
            return markRemarkFixed({ humanId, remarkId }, config)
          },
        })

}

/**
 * @description Роль FILIAL (владелец). Отмечает замечание исправленным, не закрывает его.
 * @summary Отметить замечание исправленным
 * {@link /corrections/:humanId/remarks/:remarkId/fix}
 */
export function useMarkRemarkFixed<TContext>(options: 
{
  mutation?: UseMutationOptions<MarkRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkRemarkFixedPathParams["humanId"], remarkId: MarkRemarkFixedPathParams["remarkId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? markRemarkFixedMutationKey()

          const baseOptions = markRemarkFixedMutationOptions(config) as UseMutationOptions<MarkRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkRemarkFixedPathParams["humanId"], remarkId: MarkRemarkFixedPathParams["remarkId"]}, TContext>
          

          return useMutation<MarkRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkRemarkFixedPathParams["humanId"], remarkId: MarkRemarkFixedPathParams["remarkId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MarkRemarkFixedMutationResponse, ResponseErrorConfig<Error>, {humanId: MarkRemarkFixedPathParams["humanId"], remarkId: MarkRemarkFixedPathParams["remarkId"]}, TContext>
      
}