/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ReturnCorrectionByDtoeMutationRequest, ReturnCorrectionByDtoeMutationResponse, ReturnCorrectionByDtoePathParams } from "../../types/correctionsController/ReturnCorrectionByDtoe";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { returnCorrectionByDtoe } from "../../clients/correctionsController/returnCorrectionByDtoe";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const returnCorrectionByDtoeMutationKey = () => [{ url: '/corrections/:humanId/dtoe-return' }] as const

export type ReturnCorrectionByDtoeMutationKey = ReturnType<typeof returnCorrectionByDtoeMutationKey>

export function returnCorrectionByDtoeMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ReturnCorrectionByDtoeMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = returnCorrectionByDtoeMutationKey()
        return mutationOptions<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"], data: ReturnCorrectionByDtoeMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, data }) => {
            return returnCorrectionByDtoe({ humanId, data }, config)
          },
        })

}

/**
 * @description Роль DTOE. Создаёт замечание (cfo=null) и возвращает на доработку.
 * @summary Вернуть на доработку от лица ДТОиР (с замечанием)
 * {@link /corrections/:humanId/dtoe-return}
 */
export function useReturnCorrectionByDtoe<TContext>(options: 
{
  mutation?: UseMutationOptions<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"], data: ReturnCorrectionByDtoeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ReturnCorrectionByDtoeMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? returnCorrectionByDtoeMutationKey()

          const baseOptions = returnCorrectionByDtoeMutationOptions(config) as UseMutationOptions<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"], data: ReturnCorrectionByDtoeMutationRequest}, TContext>
          

          return useMutation<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"], data: ReturnCorrectionByDtoeMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"], data: ReturnCorrectionByDtoeMutationRequest}, TContext>
      
}