/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ReopenRemarkMutationRequest, ReopenRemarkMutationResponse, ReopenRemarkPathParams } from "../../types/correctionsController/ReopenRemark";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { reopenRemark } from "../../clients/correctionsController/reopenRemark";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const reopenRemarkMutationKey = () => [{ url: '/corrections/:humanId/remarks/:remarkId/reopen' }] as const

export type ReopenRemarkMutationKey = ReturnType<typeof reopenRemarkMutationKey>

export function reopenRemarkMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ReopenRemarkMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = reopenRemarkMutationKey()
        return mutationOptions<ReopenRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: ReopenRemarkPathParams["humanId"], remarkId: ReopenRemarkPathParams["remarkId"], data: ReopenRemarkMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, remarkId, data }) => {
            return reopenRemark({ humanId, remarkId, data }, config)
          },
        })

}

/**
 * @description Роль CFO (владелец замечания). Исправление не принято — переоткрыть.
 * @summary Переоткрыть замечание (исправление не принято)
 * {@link /corrections/:humanId/remarks/:remarkId/reopen}
 */
export function useReopenRemark<TContext>(options: 
{
  mutation?: UseMutationOptions<ReopenRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: ReopenRemarkPathParams["humanId"], remarkId: ReopenRemarkPathParams["remarkId"], data: ReopenRemarkMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ReopenRemarkMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? reopenRemarkMutationKey()

          const baseOptions = reopenRemarkMutationOptions(config) as UseMutationOptions<ReopenRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: ReopenRemarkPathParams["humanId"], remarkId: ReopenRemarkPathParams["remarkId"], data: ReopenRemarkMutationRequest}, TContext>
          

          return useMutation<ReopenRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: ReopenRemarkPathParams["humanId"], remarkId: ReopenRemarkPathParams["remarkId"], data: ReopenRemarkMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ReopenRemarkMutationResponse, ResponseErrorConfig<Error>, {humanId: ReopenRemarkPathParams["humanId"], remarkId: ReopenRemarkPathParams["remarkId"], data: ReopenRemarkMutationRequest}, TContext>
      
}