/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ReturnCorrectionByCfoMutationRequest, ReturnCorrectionByCfoMutationResponse, ReturnCorrectionByCfoPathParams } from "../../types/correctionsController/ReturnCorrectionByCfo";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { returnCorrectionByCfo } from "../../clients/correctionsController/returnCorrectionByCfo";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const returnCorrectionByCfoMutationKey = () => [{ url: '/corrections/:humanId/cfo-return' }] as const

export type ReturnCorrectionByCfoMutationKey = ReturnType<typeof returnCorrectionByCfoMutationKey>

export function returnCorrectionByCfoMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ReturnCorrectionByCfoMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = returnCorrectionByCfoMutationKey()
        return mutationOptions<ReturnCorrectionByCfoMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByCfoPathParams["humanId"], data: ReturnCorrectionByCfoMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, data }) => {
            return returnCorrectionByCfo({ humanId, data }, config)
          },
        })

}

/**
 * @description Роль CFO. Создаёт замечание и возвращает пакет на доработку.
 * @summary Вернуть на доработку от лица ЦФО (с замечанием)
 * {@link /corrections/:humanId/cfo-return}
 */
export function useReturnCorrectionByCfo<TContext>(options: 
{
  mutation?: UseMutationOptions<ReturnCorrectionByCfoMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByCfoPathParams["humanId"], data: ReturnCorrectionByCfoMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ReturnCorrectionByCfoMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? returnCorrectionByCfoMutationKey()

          const baseOptions = returnCorrectionByCfoMutationOptions(config) as UseMutationOptions<ReturnCorrectionByCfoMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByCfoPathParams["humanId"], data: ReturnCorrectionByCfoMutationRequest}, TContext>
          

          return useMutation<ReturnCorrectionByCfoMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByCfoPathParams["humanId"], data: ReturnCorrectionByCfoMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ReturnCorrectionByCfoMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByCfoPathParams["humanId"], data: ReturnCorrectionByCfoMutationRequest}, TContext>
      
}