/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { ReturnCorrectionByDtoeMutationResponse, ReturnCorrectionByDtoePathParams } from "../../types/correctionsController/ReturnCorrectionByDtoe";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { returnCorrectionByDtoe } from "../../clients/correctionsController/returnCorrectionByDtoe";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const returnCorrectionByDtoeMutationKey = () => [{ url: '/corrections/:humanId/dtoe-return' }] as const

export type ReturnCorrectionByDtoeMutationKey = ReturnType<typeof returnCorrectionByDtoeMutationKey>

export function returnCorrectionByDtoeMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = returnCorrectionByDtoeMutationKey()
        return mutationOptions<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"]}, TContext>({
          mutationKey,
          mutationFn: async({ humanId }) => {
            return returnCorrectionByDtoe({ humanId }, config)
          },
        })

}

/**
 * @description Роль DTOE. Переводит корректировку в «Возвращено ДТОиР». Требует, чтобы
 * ДТОиР уже оставил хотя бы одно открытое замечание по этой корректировке
 * (`POST /corrections/{humanId}/remarks`) — иначе `400`.
 * @summary Финализировать возврат на доработку от лица ДТОиР
 * {@link /corrections/:humanId/dtoe-return}
 */
export function useReturnCorrectionByDtoe<TContext>(options: 
{
  mutation?: UseMutationOptions<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? returnCorrectionByDtoeMutationKey()

          const baseOptions = returnCorrectionByDtoeMutationOptions(config) as UseMutationOptions<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"]}, TContext>
          

          return useMutation<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ReturnCorrectionByDtoeMutationResponse, ResponseErrorConfig<Error>, {humanId: ReturnCorrectionByDtoePathParams["humanId"]}, TContext>
      
}