/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "../../../client";
import type { UploadFileVersionMutationRequest, UploadFileVersionMutationResponse, UploadFileVersionPathParams } from "../../types/correctionsController/UploadFileVersion";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { uploadFileVersion } from "../../clients/correctionsController/uploadFileVersion";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const uploadFileVersionMutationKey = () => [{ url: '/corrections/:humanId/slots/:slotId/files' }] as const

export type UploadFileVersionMutationKey = ReturnType<typeof uploadFileVersionMutationKey>

export function uploadFileVersionMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UploadFileVersionMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = uploadFileVersionMutationKey()
        return mutationOptions<UploadFileVersionMutationResponse, ResponseErrorConfig<Error>, {humanId: UploadFileVersionPathParams["humanId"], slotId: UploadFileVersionPathParams["slotId"], data: UploadFileVersionMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ humanId, slotId, data }) => {
            return uploadFileVersion({ humanId, slotId, data }, config)
          },
        })

}

/**
 * @description Доступно только автору-владельцу (роль FILIAL, свой филиал).
 * @summary Загрузить версию файла в ячейку пакета
 * {@link /corrections/:humanId/slots/:slotId/files}
 */
export function useUploadFileVersion<TContext>(options: 
{
  mutation?: UseMutationOptions<UploadFileVersionMutationResponse, ResponseErrorConfig<Error>, {humanId: UploadFileVersionPathParams["humanId"], slotId: UploadFileVersionPathParams["slotId"], data: UploadFileVersionMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UploadFileVersionMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? uploadFileVersionMutationKey()

          const baseOptions = uploadFileVersionMutationOptions(config) as UseMutationOptions<UploadFileVersionMutationResponse, ResponseErrorConfig<Error>, {humanId: UploadFileVersionPathParams["humanId"], slotId: UploadFileVersionPathParams["slotId"], data: UploadFileVersionMutationRequest}, TContext>
          

          return useMutation<UploadFileVersionMutationResponse, ResponseErrorConfig<Error>, {humanId: UploadFileVersionPathParams["humanId"], slotId: UploadFileVersionPathParams["slotId"], data: UploadFileVersionMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UploadFileVersionMutationResponse, ResponseErrorConfig<Error>, {humanId: UploadFileVersionPathParams["humanId"], slotId: UploadFileVersionPathParams["slotId"], data: UploadFileVersionMutationRequest}, TContext>
      
}